// sparx — Moving (Premium White-Glove): a BOOKING-BACKED service-business SITE TEMPLATE.
//
// GENERATED by marketplace-catalog/_gen/gen-sparx-moving-premium.ts via the shared
// _gen/service-sites/harness.ts — do NOT hand-edit; edit the generator and regenerate.
// A blueprint is PURE DATA: the loader `import()`s this module with no workspace
// resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import scheduling from './scheduling.json' with { type: 'json' };
import emails from './emails.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };

const blueprint = {
    key: 'sparx-moving-premium',
    version: '1.3.0',
    name: 'sparx — Moving (Premium White-Glove)',
    summary:
        'A refined, premium site for a white-glove long-distance moving company — a deep charcoal palette, a warm brass accent and an elegant serif display over calm relocation photography. Installs online booking for complimentary consultations and estimates, three move managers you book by name with their own hours, and a deposit policy to reserve a move date. Ships as "Whiteglove Movers".',
    vertical: 'services',
    preview: 'media/preview.png',
    requiresModules: ['builder', 'scheduling', 'crm', 'email'],

    // Identity only (business name + tagline + fonts + the theme's hex colors). The look
    // rides site.theme + the theme decl below; the installing tenant rebrands the name.
    brand: {
        businessName: 'Whiteglove Movers',
        tagline: 'Meticulous moves, worry-free.',
        colors: {
            primary: '#1a2532',
            primaryForeground: '#f4f9ff',
            accent: '#b38a51',
            secondary: '#363e48',
        },
        fonts: {
            heading: 'Fraunces',
            body: 'Inter',
        },
    },

    // The provisioned SiteTheme the installer creates + applies — an editable saved theme
    // over a foundation base + the template's brand snapshot. The LIVE storefront look is
    // site.theme (the flat bespoke tokens), written last.
    theme: {
        name: 'whiteglove',
        basePresetKey: 'apex',
        presentation: {
            v: 2,
            containerWidth: '1152px',
        },
        brand: {
            colorPrimary: '#1a2532',
            colorAccent: '#b38a51',
            colorSecondary: '#363e48',
            fontHeading: 'Fraunces',
            fontBody: 'Inter',
            tokens: {},
        },
        apply: true,
    },

    assets,
    contentTypes: [],

    // The booking spine — policies, bookable resources (staff/rooms/stations) with weekly
    // hours, and the service menu. The installer's scheduling slice replays it into a live
    // booking flow that the site's /book page renders.
    scheduling,

    // Brand-voiced MARKETING starters (a welcome + a come-back), installed as DRAFTS the
    // tenant switches on. The transactional booking sends — confirmation, reminder,
    // reschedule, cancellation, waitlist — are platform KEYED defaults, so they are covered
    // on email-module activation and are deliberately NOT duplicated here.
    emails,
    sequences: [],

    // The composed distinct site (frame + Home + Book + About + Contact) in the bespoke
    // theme, fully stamped.
    site,
};

export default blueprint;
