// Workshop: a THEMED CLONE of the golden `sparx`
// blueprint, re-dressed in the 'workshop' silica theme. Same
// complete multi-module starter (shop · journal · booking · wholesale), captured once
// and re-themed — content, commerce, and emails are identical to the flagship; only the
// look (site.theme + brand + theme) differs.
//
// GENERATED by marketplace-catalog/_gen/gen-sparx-themed.ts — do NOT hand-edit; edit the
// generator and regenerate. A blueprint is PURE DATA: the loader `import()`s this module
// with no workspace resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import content from './content.json' with { type: 'json' };
import commerce from './commerce.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };
import welcomeEmail from './welcome-email.json' with { type: 'json' };
import welcomeEmail2 from './welcome-email-2.json' with { type: 'json' };

const blueprint = {
  key: 'sparx-workshop',
  version: '1.5.0',
  name: 'Workshop',
  summary:
    'The complete starter — a faceted shop, a journal, a booking page, and a wholesale page — in the Workshop look, tuned for fabrication, joinery, and general trade. Install it, make it yours, and launch a polished working site in minutes.',
  vertical: 'services',
  preview: 'media/preview.png',
  requiresModules: ['builder', 'commerce', 'cms', 'crm', 'email'],

  // Identity only (business name + fonts + the theme's hex colors). The look itself
  // rides site.theme (below) + this theme; the installing tenant rebrands the name.
  brand: {
    businessName: 'Alder & Ash',
    tagline: 'Everything you sell, publish, and book — in one place.',
    colors: {
      primary: '#ff992b',
      primaryForeground: '#110904',
      accent: '#006aaf',
      secondary: '#414f5d',
    },
    fonts: {
      heading: 'IBM Plex Sans',
      body: 'IBM Plex Sans',
    },
  },

  // The provisioned SiteTheme the installer creates + applies — the 'workshop'
  // look as a tenant-editable saved theme (base preset apex + this theme's brand look).
  theme: {
    name: 'workshop',
    basePresetKey: 'workshop',
    presentation: {
      v: 2,
      containerWidth: '1152px',
    },
    brand: {
      colorPrimary: '#ff992b',
      colorAccent: '#006aaf',
      colorSecondary: '#414f5d',
      fontHeading: 'IBM Plex Sans',
      fontBody: 'IBM Plex Sans',
      tokens: {},
    },
    apply: true,
  },

  assets,
  contentTypes: [],
  content,
  commerce,

  emails: [
    { name: 'Welcome', doc: welcomeEmail, publish: false },
    { name: 'Welcome — day 3', doc: welcomeEmail2, publish: false },
  ],

  sequences: [
    {
      name: 'Welcome series',
      description:
        'Greets a new customer on day 0 and follows up on day 3 with a few places to start. Stops early if they’ve already bought.',
      reentryPolicy: 'once',
      exitOnPurchase: true,
      activate: false,
      steps: [
        {
          emailName: 'Welcome',
          delaySeconds: 0,
          emailType: 'marketing',
          name: 'Day 0 — welcome',
        },
        {
          emailName: 'Welcome — day 3',
          delaySeconds: 259200,
          emailType: 'marketing',
          name: 'Day 3 — places to start',
        },
      ],
    },
  ],

  // The captured site (frame + 7 pages + symbols) verbatim from the golden template,
  // with site.theme swapped to this theme's resolved token bag (light + dark).
  site,
};

export default blueprint;
