// sparx — Pet Supplies (Premium): a reference-driven SITE TEMPLATE (docs/templates/*),
// composed distinct — its own home section sequence, example commerce, and journal —
// and dressed in the bespoke theme its DESIGN.md pins.
//
// GENERATED by marketplace-catalog/_gen/gen-template-retail-pet-supplies.ts
// via the shared _gen/template-sites/harness.ts — do NOT hand-edit; edit the generator
// and regenerate. A blueprint is PURE DATA: the loader `import()`s this module with no
// workspace resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import content from './content.json' with { type: 'json' };
import authors from './authors.json' with { type: 'json' };
import commerce from './commerce.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };
import emails from './emails.json' with { type: 'json' };

const blueprint = {
  key: 'sparx-retail-pet-supplies',
  version: '1.4.0',
  name: 'sparx — Pet Supplies (Premium)',
  summary:
    'A complete, working shop for a premium modern pet brand: a real catalogue of a hand-stitched leather collar and matching lead, an adventure harness, an orthopedic dog bed, a ceramic bowl, natural treats, a rope toy, a travel bottle, a grooming brush and a flexible subscription box, with categories, collections, a bespoke pet-shop PDP and a full merchandised home page. Warm, friendly-but-premium theme — a cream ground, a deep teal primary and a warm coral accent. Shipped as Barkwell.',
  vertical: 'retail',
  preview: 'media/preview.png',
  requiresModules: ['builder', 'commerce', 'cms', 'crm', 'email'],

  // Identity only (business name + tagline + fonts + the theme's hex colours). The look
  // itself rides site.theme + the theme decl below; the installing tenant rebrands the name.
  brand: {
    businessName: 'Barkwell',
    tagline: 'The good stuff your pet actually deserves.',
    colors: {
      primary: '#006768',
      primaryForeground: '#f1fbfa',
      accent: '#b2392b',
      secondary: '#594a3c',
    },
    fonts: {
      heading: 'Fraunces',
      body: 'Nunito',
    },
  },

  // The provisioned SiteTheme the installer creates + applies — the bespoke template
  // look as a tenant-editable saved theme (base preset = the template's own theme key,
  // plus its brand snapshot).
  theme: {
    name: 'retail-pet-supplies',
    basePresetKey: 'retail-pet-supplies',
    presentation: {
      v: 2,
      containerWidth: '1152px',
    },
    brand: {
      colorPrimary: '#006768',
      colorAccent: '#b2392b',
      colorSecondary: '#594a3c',
      fontHeading: 'Fraunces',
      fontBody: 'Nunito',
      tokens: {},
    },
    apply: true,
  },

  assets,
  contentTypes: [],
  authors,
  content,
  commerce,

  // A shop's brand-voiced MARKETING starters (a welcome + a win-back), tokenized so a fork
  // re-themes to the tenant and installed as DRAFTS — the platform's keyed transactional
  // defaults (order/shipping/dunning) are separate and never duplicated here. Content
  // templates ship an empty set.
  emails,
  sequences: [],

  // The composed distinct site (frame + a template-specific home + standard commerce/
  // cms/about/contact pages + the /journal index), in the bespoke theme, fully stamped.
  site,
};

export default blueprint;
