// sparx marketplace component — 'Email sign-up' (Get in touch). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'mx-auto flex w-full max-w-xl flex-col gap-5',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content',
                children: ['One email a month'],
              },
              {
                kind: 'element',
                tag: 'p',
                class: 'text-base text-base-content',
                children: [
                  'What we made, what we learned, and anything we got wrong. Unsubscribe in one click.',
                ],
              },
              {
                kind: 'element',
                tag: 'form',
                class: 'flex flex-col gap-5',
                children: [
                  {
                    kind: 'element',
                    tag: 'label',
                    class: 'flex flex-col gap-2',
                    children: [
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-base font-medium text-base-content',
                        children: ['Email address'],
                      },
                      {
                        kind: 'element',
                        tag: 'input',
                        class: 'input input-bordered w-full',
                        attrs: {
                          type: 'email',
                          name: 'email',
                          placeholder: '',
                          required: true,
                        },
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'button',
                    class: 'btn btn-primary btn-lg',
                    attrs: {
                      type: 'submit',
                    },
                    children: ['Sign me up'],
                  },
                ],
                behavior: {
                  type: 'form',
                },
                data: {
                  kind: 'action',
                  ref: 'submit',
                },
              },
              {
                kind: 'element',
                tag: 'p',
                class: 'text-sm text-base-content',
                children: [
                  'We never pass your address to anyone, and we do not email more than monthly.',
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
