// sparx marketplace component — 'Alternating picture rows' (Page structure). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 items-center gap-10 @3xl:grid-cols-2',
            children: [
              {
                kind: 'element',
                tag: 'img',
                class:
                  'aspect-video w-full rounded-box border border-base-300 bg-base-200 object-cover',
                attrs: {
                  src: '',
                  alt: 'We dry our own timber',
                  loading: 'lazy',
                },
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['We dry our own timber'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: [
                      'Which is unusual for a workshop our size, and the reason our lead times are four weeks rather than twelve.',
                    ],
                  },
                ],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 items-center gap-10 @3xl:grid-cols-2',
            children: [
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['The person who makes it, fits it'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: [
                      'Nobody hands a problem over the wall to somebody else. If something is wrong, the person who built it puts it right.',
                    ],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'img',
                class:
                  'aspect-video w-full rounded-box border border-base-300 bg-base-200 object-cover',
                attrs: {
                  src: '',
                  alt: 'The person who makes it, fits it',
                  loading: 'lazy',
                },
              },
            ],
          },
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 items-center gap-10 @3xl:grid-cols-2',
            children: [
              {
                kind: 'element',
                tag: 'img',
                class:
                  'aspect-video w-full rounded-box border border-base-300 bg-base-200 object-cover',
                attrs: {
                  src: '',
                  alt: 'Fixed prices, published',
                  loading: 'lazy',
                },
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['Fixed prices, published'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: [
                      'The quote is the invoice. If we find something unexpected, you decide before anything is spent.',
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
