import { notFound } from 'next/navigation';
import { statusLabel, statusTone } from '@sparx/ui';
import { Badge, Card, CardBody } from '@wizeworks/silicaui-react';
import { api, type ApiRestError } from '@/lib/api-rest-client';
import { AssetEditForm } from './edit-form';

// Detail content for a CMS media asset. Mounted by both the full-page
// route and the dashboard shell's drawer / modal panel. Container width +
// back button + CmsTabs live in page.tsx.

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export const dynamic = 'force-dynamic';

interface MediaAssetDetail {
  id: string;
  key: string;
  original_filename: string;
  mime_type: string;
  byte_size: string;
  width: number | null;
  height: number | null;
  blurhash: string | null;
  dominant_color: string | null;
  focal_point: { x: number; y: number };
  alt_text: string | null;
  caption: string | null;
  status: string;
  processing_error: string | null;
  usage_count: number;
  variants: {
    id: string;
    format: string;
    width: number;
    height: number;
    byte_size: string;
    url: string;
  }[];
  original_url: string | null;
  created_at: string;
  updated_at: string;
}

interface Props {
  id: string;
}

export async function MediaAssetDetailContent({ id }: Props) {
  if (!UUID_RE.test(id)) notFound();
  let asset: MediaAssetDetail;
  try {
    asset = await api.get<MediaAssetDetail>(`/v1/media/assets/${id}`);
  } catch (err) {
    const status = (err as ApiRestError).status;
    if (status === 404 || status >= 400) notFound();
    throw err;
  }

  const isImage = asset.mime_type.startsWith('image/');
  const preview =
    asset.variants.find((v) => v.format === 'webp' && v.width >= 800)?.url ??
    asset.variants[0]?.url ??
    asset.original_url;

  return (
    // @container so the two-column body responds to its OWN width — full-page
    // (wide → 3-col) vs. the detail drawer (narrow → stacked), where viewport
    // breakpoints would keep it 3-up and force a horizontal scroll.
    <div className="@container flex flex-col gap-6">
      <div className="flex flex-col gap-2">
        <h1 className="text-3xl font-semibold">{asset.original_filename}</h1>
        <div className="flex flex-row items-center gap-2">
          <Badge color={statusTone(asset.status)} variant="soft" size="sm">
            {statusLabel(asset.status)}
          </Badge>
          <p className="text-base-content/70 text-sm">
            {asset.width && asset.height && `${asset.width}×${asset.height} · `}
            {asset.mime_type}
          </p>
        </div>
        {asset.processing_error && (
          <p className="text-danger text-sm">Transcode failed: {asset.processing_error}</p>
        )}
      </div>

      <div className="grid grid-cols-1 gap-6 @[820px]:grid-cols-3">
        <div className="@[820px]:col-span-2">
          <Card className="bg-module bg-soft">
            <CardBody>
              <h3 className="text-xl font-semibold">Preview &amp; focal point</h3>
              <p className="opacity-70">
                Click anywhere on the image to set the focal point — crops in non-uniform aspect
                ratios will center on that pixel.
              </p>
              <AssetEditForm
                assetId={asset.id}
                isImage={isImage}
                previewUrl={preview}
                altText={asset.alt_text}
                caption={asset.caption}
                focalPoint={asset.focal_point}
              />
            </CardBody>
          </Card>
        </div>

        <Card>
          <CardBody>
            <h3 className="text-xl font-semibold">Variants</h3>
            <p className="opacity-70">
              Auto-generated by the media-worker — drop these into <code>&lt;picture&gt;</code> with
              AVIF first.
            </p>
            {asset.variants.length === 0 ? (
              <p className="text-base-content/70 text-sm">
                No variants yet. {asset.status === 'uploading' && 'Transcode pending.'}
              </p>
            ) : (
              <div className="flex flex-col gap-2">
                {asset.variants.map((v) => (
                  <div
                    key={v.id}
                    className="bg-base-200 flex flex-row items-center gap-3 rounded-md px-3 py-2 text-sm"
                  >
                    <Badge color="neutral" variant="soft" size="sm">
                      {v.format.toUpperCase()}
                    </Badge>
                    <p className="text-sm">{v.width}px</p>
                    <p className="text-base-content/70 ml-auto text-xs">
                      {formatBytes(Number(v.byte_size))}
                    </p>
                  </div>
                ))}
              </div>
            )}
          </CardBody>
        </Card>
      </div>
    </div>
  );
}

function formatBytes(n: number): string {
  if (!n || n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / (1024 * 1024)).toFixed(1)} MB`;
}
