// sparx marketplace component — 'Book a time' (Get in touch). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-200 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-col items-start gap-5',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                children: ['Pick a time that suits you'],
              },
              {
                kind: 'element',
                tag: 'p',
                class: 'max-w-2xl text-lg text-base-content',
                children: [
                  'Choose a slot and it is confirmed straight away. Change or cancel it yourself up to 24 hours before.',
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-wrap items-center gap-3',
                children: [
                  {
                    kind: 'element',
                    tag: 'a',
                    class: 'btn btn-primary btn-lg',
                    attrs: {
                      href: '/book',
                    },
                    children: ['See available times'],
                  },
                  {
                    kind: 'element',
                    tag: 'a',
                    class: 'btn btn-neutral btn-outline btn-lg',
                    attrs: {
                      href: 'tel:+441233000000',
                    },
                    children: ['Call instead'],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
