// Coast — a Sparx first-party marketplace theme (docs/85). The payload is a
// complete DataThemePreset (v1 storefront tokens + v2 preset); the ingest
// validates it and writes it to storage as the applied-at-runtime artifact.
export default {
  v: 1,
  v1: {
    light: {
      colorPrimary: '#0e7490',
      colorPrimaryForeground: '#ffffff',
      colorAccent: '#f4a259',
      colorBackground: '#fbfdfe',
      colorForeground: '#11303a',
      colorMuted: '#e8f3f6',
      colorBorder: '#cfe6ec',
      fontHeading: 'Poppins',
      fontBody: 'Inter',
      radiusBase: '1rem',
      containerWidth: 'wide',
    },
    dark: {
      colorPrimary: '#22a7c4',
      colorPrimaryForeground: '#052730',
      colorAccent: '#f4a259',
      colorBackground: '#06212a',
      colorForeground: '#ddeef2',
      colorMuted: '#0c2e38',
      colorBorder: '#144450',
      fontHeading: 'Poppins',
      fontBody: 'Inter',
      radiusBase: '1rem',
      containerWidth: 'wide',
    },
  },
  v2: {
    shared: {
      fontHeading: 'Poppins',
      fontBody: 'Inter',
      radiusSelector: '9999px',
      radiusField: '0.625rem',
      radiusBox: '1rem',
      borderWidth: '1px',
      spaceBase: '0.27rem',
      sizeField: '2.75rem',
      sizeSelector: '2rem',
      depth: 1,
      containerWidth: 'wide',
    },
    light: {
      base100: '#fbfdfe',
      base200: '#ffffff',
      base300: '#e8f3f6',
      baseContent: '#11303a',
      primary: '#0e7490',
      primaryContent: '#ffffff',
      secondary: '#2a9d8f',
      accent: '#f4a259',
      neutral: '#11303a',
      border: '#cfe6ec',
      info: '#0284c7',
      success: '#16a34a',
      warning: '#d97706',
      danger: '#dc2626',
    },
    dark: {
      base100: '#06212a',
      base200: '#0b2c36',
      base300: '#123a46',
      baseContent: '#ddeef2',
      primary: '#22a7c4',
      primaryContent: '#052730',
      secondary: '#2dd4bf',
      accent: '#f4a259',
      neutral: '#ddeef2',
      border: '#144450',
      info: '#38bdf8',
      success: '#4ade80',
      warning: '#fbbf24',
      danger: '#f87171',
    },
  },
};
