// GENERATED by scripts/ingest.mjs — do not edit.
//
// Source of truth: the batch manifests under piggles/images/mascot/. To change a
// pose's metadata, edit the manifest and re-run `pnpm --filter @piggles/mascot
// ingest`. Batches ingested: 01.

/** Every pose whose artwork exists and ships today. */
export type MascotPoseId =
  | 'calendar'
  | 'celebrate'
  | 'desk'
  | 'invoice'
  | 'laptop'
  | 'neutral'
  | 'point-left'
  | 'thinking'
  | 'wave';

/** Every pose that is specified but not yet drawn. */
export type PlannedPoseId =
  | '404'
  | 'automate'
  | 'camera'
  | 'chart-up'
  | 'clap'
  | 'coffee'
  | 'concerned'
  | 'confused'
  | 'connection'
  | 'customer'
  | 'email'
  | 'heart'
  | 'high-five'
  | 'late-night'
  | 'loading'
  | 'maintenance'
  | 'megaphone'
  | 'message'
  | 'money'
  | 'oops'
  | 'package'
  | 'paint'
  | 'party-hat'
  | 'peek-left'
  | 'peek-right'
  | 'phone'
  | 'point-down'
  | 'point-right'
  | 'point-up'
  | 'product'
  | 'receipt'
  | 'searching'
  | 'shield'
  | 'site'
  | 'sleeping'
  | 'stock'
  | 'store'
  | 'sunrise'
  | 'support'
  | 'thumbs-up';

export type AnyPoseId = MascotPoseId | PlannedPoseId;

/** A pose whose artwork exists and ships today. */
export interface MascotPose {
  id: MascotPoseId;
  /** Which delivered batch this cut came from. Provenance only — never branch on
   *  it. A re-cut supersedes a pose in place and this is the only thing that
   *  changes. */
  batch: string;
  category: string;
  /** The manifest's description of the artwork, used when the mascot is
   *  MEANINGFUL. She is usually decorative, so <PigglesMascot> defaults to an
   *  empty alt and this goes unused — see src/react/mascot.tsx. */
  alt: string;
  /** Emotional register, from the character bible. Reference for whoever is
   *  choosing a pose; nothing reads it at runtime. */
  energy: string;
  /** Where the weight of the artwork sits, for placing her against an edge. */
  anchor: string;
  /** The manifest's own keywords. Human reference — the binding map from a
   *  product situation to a pose is MASCOT_INTENTS in ./intents. */
  intent: readonly string[];
  /** Served from each app's own public/ directory. */
  src: string;
  /** TRUE intrinsic size of the trimmed artwork, not the delivery canvas. */
  width: number;
  height: number;
}

/** A pose that is specified but not yet drawn. Naming one in an intent chain is
 *  how a surface says what it WANTS: the chain falls through to real art today
 *  and upgrades itself the day the batch lands, with no edit at the call site. */
export interface PlannedPose {
  id: PlannedPoseId;
  category: string;
  alt: string;
  intent: readonly string[];
}

export const MASCOT_POSES: Record<MascotPoseId, MascotPose> = {
  calendar: {
    id: 'calendar',
    batch: '01',
    category: 'business',
    alt: 'Piggles presenting a calendar.',
    energy: 'helpful',
    anchor: 'bottom',
    intent: ['bookings', 'calendar', 'schedule', 'appointments'],
    src: '/mascot/calendar.webp',
    width: 1052,
    height: 1196,
  },
  celebrate: {
    id: 'celebrate',
    batch: '01',
    category: 'state',
    alt: 'Piggles jumping in celebration.',
    energy: 'high',
    anchor: 'center',
    intent: ['success', 'celebrate', 'milestone', 'complete'],
    src: '/mascot/celebrate.webp',
    width: 1024,
    height: 1185,
  },
  desk: {
    id: 'desk',
    batch: '01',
    category: 'scene',
    alt: 'Piggles working at a laptop at a desk with a plant and coffee mug.',
    energy: 'warm',
    anchor: 'bottom',
    intent: ['login', 'hero', 'marketing', 'workspace'],
    src: '/mascot/desk.webp',
    width: 1200,
    height: 683,
  },
  invoice: {
    id: 'invoice',
    batch: '01',
    category: 'business',
    alt: 'Piggles holding and pointing to an invoice.',
    energy: 'helpful',
    anchor: 'bottom',
    intent: ['invoice', 'money', 'billing', 'paid'],
    src: '/mascot/invoice.webp',
    width: 1092,
    height: 1188,
  },
  laptop: {
    id: 'laptop',
    batch: '01',
    category: 'work',
    alt: 'Piggles sitting with a laptop and working.',
    energy: 'focused',
    anchor: 'bottom',
    intent: ['login', 'work', 'workspace', 'productivity'],
    src: '/mascot/laptop.webp',
    width: 1127,
    height: 1083,
  },
  neutral: {
    id: 'neutral',
    batch: '01',
    category: 'core',
    alt: 'Piggles standing and smiling.',
    energy: 'calm',
    anchor: 'center',
    intent: ['default', 'welcome', 'about', 'empty-state'],
    src: '/mascot/neutral.webp',
    width: 857,
    height: 1179,
  },
  'point-left': {
    id: 'point-left',
    batch: '01',
    category: 'directional',
    alt: 'Piggles smiling and pointing to the left.',
    energy: 'friendly',
    anchor: 'bottom',
    intent: ['point', 'cta', 'callout', 'guide'],
    src: '/mascot/point-left.webp',
    width: 1052,
    height: 1151,
  },
  thinking: {
    id: 'thinking',
    batch: '01',
    category: 'state',
    alt: 'Piggles thinking with one hoof under the chin.',
    energy: 'thoughtful',
    anchor: 'bottom',
    intent: ['thinking', 'help', 'question', 'empty-state'],
    src: '/mascot/thinking.webp',
    width: 809,
    height: 1188,
  },
  wave: {
    id: 'wave',
    batch: '01',
    category: 'core',
    alt: 'Piggles smiling and waving.',
    energy: 'friendly',
    anchor: 'bottom',
    intent: ['welcome', 'hello', 'onboarding', 'success'],
    src: '/mascot/wave.webp',
    width: 937,
    height: 1200,
  },
};

export const PLANNED_POSES: Record<PlannedPoseId, PlannedPose> = {
  '404': {
    id: '404',
    category: 'system',
    alt: 'Piggles looking at a simple map/sign.',
    intent: ['404', 'lost', 'not-found'],
  },
  automate: {
    id: 'automate',
    category: 'work',
    alt: 'Piggles beside simple connected workflow nodes.',
    intent: ['automations', 'workflow', 'time-saving'],
  },
  camera: {
    id: 'camera',
    category: 'work',
    alt: 'Piggles holding a camera.',
    intent: ['media', 'photos', 'content'],
  },
  'chart-up': {
    id: 'chart-up',
    category: 'business',
    alt: 'Piggles pointing at an upward chart.',
    intent: ['analytics', 'growth', 'reports'],
  },
  clap: {
    id: 'clap',
    category: 'state',
    alt: 'Piggles clapping happily.',
    intent: ['celebrate', 'success', 'milestone'],
  },
  coffee: {
    id: 'coffee',
    category: 'lifestyle',
    alt: 'Piggles holding a coffee mug.',
    intent: ['break', 'morning', 'welcome'],
  },
  concerned: {
    id: 'concerned',
    category: 'state',
    alt: 'Piggles looking concerned but calm.',
    intent: ['warning', 'attention', 'problem'],
  },
  confused: {
    id: 'confused',
    category: 'state',
    alt: 'Piggles looking mildly confused.',
    intent: ['confused', 'help', 'error-recovery'],
  },
  connection: {
    id: 'connection',
    category: 'work',
    alt: 'Piggles connecting two plugs/blocks.',
    intent: ['connections', 'integration', 'mcp'],
  },
  customer: {
    id: 'customer',
    category: 'business',
    alt: 'Piggles presenting a customer/contact card.',
    intent: ['customers', 'crm', 'contacts'],
  },
  email: {
    id: 'email',
    category: 'business',
    alt: 'Piggles holding an envelope.',
    intent: ['email', 'campaign', 'messages'],
  },
  heart: {
    id: 'heart',
    category: 'state',
    alt: 'Piggles holding a heart.',
    intent: ['love', 'thanks', 'customer'],
  },
  'high-five': {
    id: 'high-five',
    category: 'state',
    alt: 'Piggles offering a high five.',
    intent: ['success', 'team', 'celebrate'],
  },
  'late-night': {
    id: 'late-night',
    category: 'lifestyle',
    alt: 'Piggles working late at a laptop.',
    intent: ['dark-mode', 'work', 'night'],
  },
  loading: {
    id: 'loading',
    category: 'system',
    alt: 'Piggles busily working or jogging in place.',
    intent: ['loading', 'working', 'processing'],
  },
  maintenance: {
    id: 'maintenance',
    category: 'system',
    alt: 'Piggles with a tiny tool kit.',
    intent: ['maintenance', 'status', 'downtime'],
  },
  megaphone: {
    id: 'megaphone',
    category: 'work',
    alt: 'Piggles using a small megaphone.',
    intent: ['marketing', 'announce', 'campaign'],
  },
  message: {
    id: 'message',
    category: 'business',
    alt: 'Piggles presenting a message bubble.',
    intent: ['messages', 'chat', 'reply'],
  },
  money: {
    id: 'money',
    category: 'business',
    alt: 'Piggles holding a coin or small stack of coins.',
    intent: ['money', 'revenue', 'paid'],
  },
  oops: {
    id: 'oops',
    category: 'state',
    alt: 'Piggles reacting to a small mistake.',
    intent: ['error', 'failed', 'retry'],
  },
  package: {
    id: 'package',
    category: 'business',
    alt: 'Piggles holding a package.',
    intent: ['orders', 'shipping', 'fulfillment'],
  },
  paint: {
    id: 'paint',
    category: 'work',
    alt: 'Piggles holding a paint roller or palette.',
    intent: ['design', 'branding', 'site'],
  },
  'party-hat': {
    id: 'party-hat',
    category: 'state',
    alt: 'Piggles wearing a small party hat.',
    intent: ['milestone', 'birthday', 'celebrate'],
  },
  'peek-left': {
    id: 'peek-left',
    category: 'directional',
    alt: 'Piggles peeking in from the left edge.',
    intent: ['peek', 'callout', 'sidebar'],
  },
  'peek-right': {
    id: 'peek-right',
    category: 'directional',
    alt: 'Piggles peeking in from the right edge.',
    intent: ['peek', 'callout', 'sidebar'],
  },
  phone: {
    id: 'phone',
    category: 'work',
    alt: 'Piggles holding a smartphone.',
    intent: ['messages', 'mobile', 'call'],
  },
  'point-down': {
    id: 'point-down',
    category: 'directional',
    alt: 'Piggles pointing downward.',
    intent: ['point', 'cta', 'scroll'],
  },
  'point-right': {
    id: 'point-right',
    category: 'directional',
    alt: 'Piggles pointing to the right.',
    intent: ['point', 'cta', 'guide'],
  },
  'point-up': {
    id: 'point-up',
    category: 'directional',
    alt: 'Piggles pointing upward.',
    intent: ['point', 'callout', 'tip'],
  },
  product: {
    id: 'product',
    category: 'business',
    alt: 'Piggles presenting a product box.',
    intent: ['products', 'sell', 'catalog'],
  },
  receipt: {
    id: 'receipt',
    category: 'business',
    alt: 'Piggles holding a receipt.',
    intent: ['expenses', 'receipt', 'money'],
  },
  searching: {
    id: 'searching',
    category: 'system',
    alt: 'Piggles looking through a magnifying glass.',
    intent: ['search', 'find', 'empty-state'],
  },
  shield: {
    id: 'shield',
    category: 'trust',
    alt: 'Piggles holding a shield.',
    intent: ['security', 'privacy', 'safe'],
  },
  site: {
    id: 'site',
    category: 'business',
    alt: 'Piggles presenting a web page or browser window.',
    intent: ['site', 'builder', 'publish'],
  },
  sleeping: {
    id: 'sleeping',
    category: 'state',
    alt: 'Piggles sleeping peacefully.',
    intent: ['empty-state', 'quiet', 'after-hours'],
  },
  stock: {
    id: 'stock',
    category: 'business',
    alt: 'Piggles carrying small boxes.',
    intent: ['inventory', 'stock', 'restock'],
  },
  store: {
    id: 'store',
    category: 'business',
    alt: 'Piggles standing beside a small storefront.',
    intent: ['site', 'store', 'commerce'],
  },
  sunrise: {
    id: 'sunrise',
    category: 'lifestyle',
    alt: 'Piggles greeting the morning.',
    intent: ['morning', 'home', 'daily'],
  },
  support: {
    id: 'support',
    category: 'trust',
    alt: 'Piggles wearing a support headset.',
    intent: ['support', 'help', 'human'],
  },
  'thumbs-up': {
    id: 'thumbs-up',
    category: 'state',
    alt: 'Piggles giving a thumbs-up style hoof gesture.',
    intent: ['success', 'approval', 'done'],
  },
};

export const MASCOT_POSE_IDS: readonly MascotPoseId[] = [
  'calendar',
  'celebrate',
  'desk',
  'invoice',
  'laptop',
  'neutral',
  'point-left',
  'thinking',
  'wave',
];

export function isAvailable(id: AnyPoseId): id is MascotPoseId {
  return id in MASCOT_POSES;
}
