// GENERATED by scripts/ingest.mjs — do not edit.
//
// Source of truth: the batch manifests under piggles/images/mascot/. To change a
// pose's metadata, edit the manifest and re-run `pnpm --filter @piggles/mascot
// ingest`. Batches ingested: 01, 02, 03, 04, 05.

/** Every pose whose artwork exists and ships today. */
export type MascotPoseId =
  | 'analyst'
  | 'announcement'
  | 'builder'
  | 'calendar-desk'
  | 'chart'
  | 'checklist'
  | 'cheerleader'
  | 'coffee'
  | 'communicator'
  | 'desk-celebrate'
  | 'desk-workspace'
  | 'desktop-computer'
  | 'download'
  | 'email-desk'
  | 'empty'
  | 'error'
  | 'food-truck'
  | 'front-counter'
  | 'home-office'
  | 'idea'
  | 'laptop-coffee'
  | 'laptop-focus'
  | 'loading'
  | 'mail'
  | 'maintenance'
  | 'mascot-base'
  | 'meeting-table'
  | 'money-minder'
  | 'no-results'
  | 'orders-desk'
  | 'organizer'
  | 'package'
  | 'phone'
  | 'phone-desk'
  | 'planner'
  | 'point-right'
  | 'protector'
  | 'reports-desk'
  | 'retail-shop'
  | 'salon-station'
  | 'security'
  | 'shipping-station'
  | 'sidekick'
  | 'support'
  | 'tablet-desk'
  | 'thumbs-up'
  | 'upload'
  | 'video-call'
  | 'welcome-sign'
  | 'workshop';

/** Every pose that is specified but not yet drawn. */
export type PlannedPoseId = never;

export type AnyPoseId = MascotPoseId;

/** A pose whose artwork exists and ships today. */
export interface MascotPose {
  id: MascotPoseId;
  /** Which delivered batch this cut came from. Provenance only — never branch on
   *  it. A re-cut supersedes a pose in place and this is the only thing that
   *  changes. */
  batch: string;
  category: string;
  /** The manifest's description of the artwork, used when the mascot is
   *  MEANINGFUL. She is usually decorative, so <PigglesMascot> defaults to an
   *  empty alt and this goes unused — see src/react/mascot.tsx. */
  alt: string;
  /** Emotional register, from the character bible. Reference for whoever is
   *  choosing a pose; nothing reads it at runtime. */
  energy: string;
  /** Where the weight of the artwork sits, for placing her against an edge. */
  anchor: string;
  /** The manifest's own keywords. Human reference — the binding map from a
   *  product situation to a pose is MASCOT_INTENTS in ./intents. */
  intent: readonly string[];
  /** Served from each app's own public/ directory. */
  src: string;
  /** TRUE intrinsic size of the trimmed artwork, not the delivery canvas. */
  width: number;
  height: number;
  /** Fraction of `height` that the CHARACTER occupies, measured from her own
   *  pink mass rather than from the frame.
   *
   *  This is what makes a named size mean the same thing across poses that are
   *  framed differently. `builder` is the figure alone at ratio 0.72; a desk
   *  scene is a table at ratio 1.49. Sized to one WIDTH they put two characters
   *  on screen at nearly 2x each other. Sized so this fraction lands on the same
   *  number of pixels, they match — see <PigglesMascot>, which does the
   *  arithmetic so no call site has to know a pose apart from its id. */
  subject: number;
}

/** A pose that is specified but not yet drawn. Naming one in an intent chain is
 *  how a surface says what it WANTS: the chain falls through to real art today
 *  and upgrades itself the day the batch lands, with no edit at the call site. */
export interface PlannedPose {
  id: PlannedPoseId;
  category: string;
  alt: string;
  intent: readonly string[];
}

export const MASCOT_POSES: Record<MascotPoseId, MascotPose> = {
  analyst: {
    id: 'analyst',
    batch: '01',
    category: 'analytics',
    alt: 'Piggles examining a growth chart',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/analyst.webp',
    width: 787,
    height: 849,
    subject: 0.8869,
  },
  announcement: {
    id: 'announcement',
    batch: '03',
    category: 'communication',
    alt: 'Piggles making an announcement',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/announcement.webp',
    width: 961,
    height: 852,
    subject: 0.8721,
  },
  builder: {
    id: 'builder',
    batch: '01',
    category: 'building',
    alt: 'Piggles building with a laptop',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/builder.webp',
    width: 653,
    height: 903,
    subject: 0.8339,
  },
  'calendar-desk': {
    id: 'calendar-desk',
    batch: '05',
    category: 'scheduling',
    alt: 'Piggles scheduling work at a laptop',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/calendar-desk.webp',
    width: 1158,
    height: 778,
    subject: 0.9075,
  },
  chart: {
    id: 'chart',
    batch: '02',
    category: 'analytics',
    alt: 'Piggles presenting a growth chart',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/chart.webp',
    width: 906,
    height: 791,
    subject: 0.8571,
  },
  checklist: {
    id: 'checklist',
    batch: '02',
    category: 'productivity',
    alt: 'Piggles completing a checklist',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/checklist.webp',
    width: 750,
    height: 836,
    subject: 0.86,
  },
  cheerleader: {
    id: 'cheerleader',
    batch: '01',
    category: 'success',
    alt: 'Piggles celebrating a win',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/cheerleader.webp',
    width: 982,
    height: 852,
    subject: 0.885,
  },
  coffee: {
    id: 'coffee',
    batch: '02',
    category: 'lifestyle',
    alt: 'Piggles holding a coffee mug',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/coffee.webp',
    width: 675,
    height: 961,
    subject: 0.8543,
  },
  communicator: {
    id: 'communicator',
    batch: '01',
    category: 'communication',
    alt: 'Piggles ready to communicate',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/communicator.webp',
    width: 808,
    height: 856,
    subject: 0.8867,
  },
  'desk-celebrate': {
    id: 'desk-celebrate',
    batch: '05',
    category: 'success',
    alt: 'Piggles celebrating a business win at a laptop',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/desk-celebrate.webp',
    width: 1150,
    height: 836,
    subject: 0.8959,
  },
  'desk-workspace': {
    id: 'desk-workspace',
    batch: '04',
    category: 'workspace',
    alt: 'Piggles working at a writing desk',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/desk-workspace.webp',
    width: 1099,
    height: 925,
    subject: 0.613,
  },
  'desktop-computer': {
    id: 'desktop-computer',
    batch: '04',
    category: 'workspace',
    alt: 'Piggles working at a desktop computer',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/desktop-computer.webp',
    width: 1057,
    height: 919,
    subject: 0.8215,
  },
  download: {
    id: 'download',
    batch: '03',
    category: 'files',
    alt: 'Piggles receiving a downloaded document',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/download.webp',
    width: 550,
    height: 1040,
    subject: 0.8923,
  },
  'email-desk': {
    id: 'email-desk',
    batch: '05',
    category: 'communication',
    alt: 'Piggles handling email at a laptop',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/email-desk.webp',
    width: 1158,
    height: 788,
    subject: 0.8871,
  },
  empty: {
    id: 'empty',
    batch: '03',
    category: 'system-state',
    alt: 'Piggles looking inside an empty box',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/empty.webp',
    width: 838,
    height: 900,
    subject: 0.8856,
  },
  error: {
    id: 'error',
    batch: '03',
    category: 'system-state',
    alt: 'Piggles beside an error warning',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/error.webp',
    width: 997,
    height: 886,
    subject: 0.8646,
  },
  'food-truck': {
    id: 'food-truck',
    batch: '04',
    category: 'small-business',
    alt: 'Piggles welcoming customers beside a food truck',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/food-truck.webp',
    width: 1158,
    height: 786,
    subject: 0.8448,
  },
  'front-counter': {
    id: 'front-counter',
    batch: '04',
    category: 'commerce',
    alt: 'Piggles welcoming customers at a service counter',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/front-counter.webp',
    width: 1084,
    height: 776,
    subject: 0.9162,
  },
  'home-office': {
    id: 'home-office',
    batch: '04',
    category: 'workspace',
    alt: 'Piggles working in a compact home office',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/home-office.webp',
    width: 1065,
    height: 781,
    subject: 0.9104,
  },
  idea: {
    id: 'idea',
    batch: '02',
    category: 'discovery',
    alt: 'Piggles having a bright idea',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/idea.webp',
    width: 695,
    height: 885,
    subject: 0.7706,
  },
  'laptop-coffee': {
    id: 'laptop-coffee',
    batch: '05',
    category: 'tabletop-work',
    alt: 'Piggles reviewing a laptop with a mug',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/laptop-coffee.webp',
    width: 1150,
    height: 909,
    subject: 0.8559,
  },
  'laptop-focus': {
    id: 'laptop-focus',
    batch: '05',
    category: 'tabletop-work',
    alt: 'Piggles focused on work at a laptop',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/laptop-focus.webp',
    width: 1158,
    height: 789,
    subject: 0.9189,
  },
  loading: {
    id: 'loading',
    batch: '03',
    category: 'system-state',
    alt: 'Piggles with a loading wheel',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/loading.webp',
    width: 1080,
    height: 808,
    subject: 0.8676,
  },
  mail: {
    id: 'mail',
    batch: '02',
    category: 'communication',
    alt: 'Piggles offering an envelope',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/mail.webp',
    width: 697,
    height: 960,
    subject: 0.8979,
  },
  maintenance: {
    id: 'maintenance',
    batch: '03',
    category: 'system-state',
    alt: 'Piggles maintaining a gear',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/maintenance.webp',
    width: 846,
    height: 877,
    subject: 0.8643,
  },
  'mascot-base': {
    id: 'mascot-base',
    batch: '01',
    category: 'canonical',
    alt: 'Piggles welcoming the user',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/mascot-base.webp',
    width: 809,
    height: 804,
    subject: 0.8806,
  },
  'meeting-table': {
    id: 'meeting-table',
    batch: '04',
    category: 'collaboration',
    alt: 'Piggles leading a meeting at a conference table',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/meeting-table.webp',
    width: 1143,
    height: 877,
    subject: 0.6534,
  },
  'money-minder': {
    id: 'money-minder',
    batch: '01',
    category: 'finance',
    alt: 'Piggles watching the numbers',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/money-minder.webp',
    width: 773,
    height: 937,
    subject: 0.8965,
  },
  'no-results': {
    id: 'no-results',
    batch: '03',
    category: 'search',
    alt: 'Piggles searching an empty tray',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/no-results.webp',
    width: 976,
    height: 918,
    subject: 0.866,
  },
  'orders-desk': {
    id: 'orders-desk',
    batch: '05',
    category: 'commerce',
    alt: 'Piggles organizing an order at a laptop',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/orders-desk.webp',
    width: 1158,
    height: 893,
    subject: 0.8936,
  },
  organizer: {
    id: 'organizer',
    batch: '01',
    category: 'organization',
    alt: 'Piggles organizing a checklist',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/organizer.webp',
    width: 814,
    height: 850,
    subject: 0.86,
  },
  package: {
    id: 'package',
    batch: '02',
    category: 'commerce',
    alt: 'Piggles carrying a package',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/package.webp',
    width: 800,
    height: 892,
    subject: 0.8587,
  },
  phone: {
    id: 'phone',
    batch: '02',
    category: 'communication',
    alt: 'Piggles using a phone',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/phone.webp',
    width: 746,
    height: 970,
    subject: 0.8876,
  },
  'phone-desk': {
    id: 'phone-desk',
    batch: '05',
    category: 'communication',
    alt: 'Piggles checking a phone beside a laptop',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/phone-desk.webp',
    width: 1104,
    height: 872,
    subject: 0.9117,
  },
  planner: {
    id: 'planner',
    batch: '01',
    category: 'planning',
    alt: 'Piggles planning with a clipboard',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/planner.webp',
    width: 835,
    height: 831,
    subject: 0.8833,
  },
  'point-right': {
    id: 'point-right',
    batch: '02',
    category: 'guidance',
    alt: 'Piggles presenting toward the right',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/point-right.webp',
    width: 1010,
    height: 953,
    subject: 0.8573,
  },
  protector: {
    id: 'protector',
    batch: '01',
    category: 'security',
    alt: 'Piggles protecting the business',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/protector.webp',
    width: 928,
    height: 931,
    subject: 0.8894,
  },
  'reports-desk': {
    id: 'reports-desk',
    batch: '05',
    category: 'analytics',
    alt: 'Piggles reviewing reports at a laptop',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/reports-desk.webp',
    width: 1158,
    height: 832,
    subject: 0.9087,
  },
  'retail-shop': {
    id: 'retail-shop',
    batch: '04',
    category: 'commerce',
    alt: 'Piggles beside a small retail display',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/retail-shop.webp',
    width: 1086,
    height: 845,
    subject: 0.7728,
  },
  'salon-station': {
    id: 'salon-station',
    batch: '04',
    category: 'small-business',
    alt: 'Piggles beside a salon workstation',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/salon-station.webp',
    width: 1043,
    height: 958,
    subject: 0.858,
  },
  security: {
    id: 'security',
    batch: '03',
    category: 'trust',
    alt: 'Piggles presenting a secure shield',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/security.webp',
    width: 910,
    height: 895,
    subject: 0.9095,
  },
  'shipping-station': {
    id: 'shipping-station',
    batch: '04',
    category: 'operations',
    alt: 'Piggles packing an order at a shipping station',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/shipping-station.webp',
    width: 886,
    height: 1008,
    subject: 0.8085,
  },
  sidekick: {
    id: 'sidekick',
    batch: '01',
    category: 'companion',
    alt: 'Piggles sitting by your side',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/sidekick.webp',
    width: 675,
    height: 910,
    subject: 0.8352,
  },
  support: {
    id: 'support',
    batch: '03',
    category: 'help',
    alt: 'Piggles ready to provide support',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/support.webp',
    width: 1002,
    height: 878,
    subject: 0.836,
  },
  'tablet-desk': {
    id: 'tablet-desk',
    batch: '05',
    category: 'content',
    alt: 'Piggles working with a tablet and stylus',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/tablet-desk.webp',
    width: 1155,
    height: 944,
    subject: 0.8962,
  },
  'thumbs-up': {
    id: 'thumbs-up',
    batch: '02',
    category: 'success',
    alt: 'Piggles giving a thumbs up',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/thumbs-up.webp',
    width: 933,
    height: 1000,
    subject: 0.887,
  },
  upload: {
    id: 'upload',
    batch: '03',
    category: 'files',
    alt: 'Piggles uploading a document',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/upload.webp',
    width: 833,
    height: 824,
    subject: 0.875,
  },
  'video-call': {
    id: 'video-call',
    batch: '05',
    category: 'communication',
    alt: 'Piggles joining a video call at a laptop',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/video-call.webp',
    width: 1158,
    height: 882,
    subject: 0.8605,
  },
  'welcome-sign': {
    id: 'welcome-sign',
    batch: '02',
    category: 'onboarding',
    alt: 'Piggles holding a welcome sign',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/welcome-sign.webp',
    width: 874,
    height: 790,
    subject: 0.8734,
  },
  workshop: {
    id: 'workshop',
    batch: '04',
    category: 'workspace',
    alt: 'Piggles beside a compact workbench',
    energy: 'friendly',
    anchor: 'bottom',
    intent: [],
    src: '/mascot/workshop.webp',
    width: 1001,
    height: 737,
    subject: 0.7829,
  },
};

export const PLANNED_POSES: Record<PlannedPoseId, PlannedPose> = {};

export const MASCOT_POSE_IDS: readonly MascotPoseId[] = [
  'analyst',
  'announcement',
  'builder',
  'calendar-desk',
  'chart',
  'checklist',
  'cheerleader',
  'coffee',
  'communicator',
  'desk-celebrate',
  'desk-workspace',
  'desktop-computer',
  'download',
  'email-desk',
  'empty',
  'error',
  'food-truck',
  'front-counter',
  'home-office',
  'idea',
  'laptop-coffee',
  'laptop-focus',
  'loading',
  'mail',
  'maintenance',
  'mascot-base',
  'meeting-table',
  'money-minder',
  'no-results',
  'orders-desk',
  'organizer',
  'package',
  'phone',
  'phone-desk',
  'planner',
  'point-right',
  'protector',
  'reports-desk',
  'retail-shop',
  'salon-station',
  'security',
  'shipping-station',
  'sidekick',
  'support',
  'tablet-desk',
  'thumbs-up',
  'upload',
  'video-call',
  'welcome-sign',
  'workshop',
];

export function isAvailable(id: AnyPoseId): id is MascotPoseId {
  return id in MASCOT_POSES;
}
