// The Sparx first-party DATA themes (docs/85 — the creator-marketplace dogfood).
//
// Each theme is the marketplace `tokens` payload — a complete `DataThemePreset`
// (v1 storefront tokens + v2 preset) — plus the curated catalog facets/copy the
// browse cards render. These are PURE DATA: the runtime applies them with no code
// preset and no deploy (the apply path writes the preset into the tenant's
// draftSettings; the compile engine reads it via the `compile-from-data` seam).
//
// This is the seed-side authoring source for Phase 1; the same shape is what the
// Phase-2 submission pipeline compiles an uploaded `theme.ts` down to.

import type { DataThemePreset } from '@sparx/marketplace-schemas';

const STATUS_LIGHT = { info: '#0284c7', success: '#16a34a', warning: '#d97706', danger: '#dc2626' };
const STATUS_DARK = { info: '#38bdf8', success: '#4ade80', warning: '#fbbf24', danger: '#f87171' };

export interface DataThemeRow {
  slug: string;
  name: string;
  accent: string;
  mood: string;
  colorFamily: string;
  density: string;
  industry: string;
  tagline: string;
  description: string;
  sortWeight: number;
  preset: DataThemePreset;
}

export const SPARX_DATA_THEMES: DataThemeRow[] = [
  {
    slug: 'noir',
    name: 'Noir',
    accent: '#b08d57',
    mood: 'Luxe',
    colorFamily: 'Black',
    density: 'Spacious',
    industry: 'Jewelry & Luxury',
    tagline: 'Dark, high-contrast luxury — restrained type and a single gold accent.',
    description:
      'A black-on-black luxury theme with a warm gold accent and elegant serif headings. Noir suits fine jewelry, premium fashion, and brands that sell on restraint and craftsmanship.',
    sortWeight: 58,
    preset: {
      v: 1,
      v1: {
        light: {
          colorPrimary: '#0a0a0a',
          colorPrimaryForeground: '#f5f0e6',
          colorAccent: '#b08d57',
          colorBackground: '#fafaf8',
          colorForeground: '#1a1a1a',
          colorMuted: '#f0eee9',
          colorBorder: '#e2ded4',
          fontHeading: 'Cormorant Garamond',
          fontBody: 'Inter',
          radiusBase: '0px',
          containerWidth: 'wide',
        },
        dark: {
          colorPrimary: '#f5f0e6',
          colorPrimaryForeground: '#0a0a0a',
          colorAccent: '#c9a86a',
          colorBackground: '#0b0b0c',
          colorForeground: '#eceae4',
          colorMuted: '#161617',
          colorBorder: '#26262a',
          fontHeading: 'Cormorant Garamond',
          fontBody: 'Inter',
          radiusBase: '0px',
          containerWidth: 'wide',
        },
      },
      v2: {
        shared: {
          fontHeading: 'Cormorant Garamond',
          fontBody: 'Inter',
          radiusSelector: '0px',
          radiusField: '0px',
          radiusBox: '0px',
          borderWidth: '1px',
          spaceBase: '0.28rem',
          sizeField: '2.875rem',
          sizeSelector: '2.125rem',
          depth: 0.5,
          containerWidth: 'wide',
        },
        light: {
          base100: '#fafaf8',
          base200: '#ffffff',
          base300: '#f0eee9',
          baseContent: '#1a1a1a',
          primary: '#0a0a0a',
          primaryContent: '#f5f0e6',
          secondary: '#6b6256',
          accent: '#b08d57',
          neutral: '#0a0a0a',
          border: '#e2ded4',
          ...STATUS_LIGHT,
        },
        dark: {
          base100: '#0b0b0c',
          base200: '#141416',
          base300: '#1d1d20',
          baseContent: '#eceae4',
          primary: '#f5f0e6',
          primaryContent: '#0a0a0a',
          secondary: '#a89b85',
          accent: '#c9a86a',
          neutral: '#eceae4',
          border: '#26262a',
          ...STATUS_DARK,
        },
      },
    },
  },
  {
    slug: 'sage',
    name: 'Sage',
    accent: '#4d7c5a',
    mood: 'Calm',
    colorFamily: 'Green',
    density: 'Spacious',
    industry: 'Wellness & Beauty',
    tagline: 'Calm and botanical — soft greens, warm serif headings, easy spacing.',
    description:
      'Soft greens, generous whitespace, and warm serif headings make Sage feel grounded and unhurried — a natural fit for wellness, plants, beauty, and slow-living brands.',
    sortWeight: 52,
    preset: {
      v: 1,
      v1: {
        light: {
          colorPrimary: '#4d7c5a',
          colorPrimaryForeground: '#ffffff',
          colorAccent: '#a3b18a',
          colorBackground: '#fbfcfa',
          colorForeground: '#1f2a22',
          colorMuted: '#eef2ea',
          colorBorder: '#dce5d5',
          fontHeading: 'Fraunces',
          fontBody: 'Nunito Sans',
          radiusBase: '0.75rem',
          containerWidth: 'medium',
        },
        dark: {
          colorPrimary: '#6fa67e',
          colorPrimaryForeground: '#0e1611',
          colorAccent: '#b6c49c',
          colorBackground: '#0e1611',
          colorForeground: '#e7ede3',
          colorMuted: '#16211a',
          colorBorder: '#233127',
          fontHeading: 'Fraunces',
          fontBody: 'Nunito Sans',
          radiusBase: '0.75rem',
          containerWidth: 'medium',
        },
      },
      v2: {
        shared: {
          fontHeading: 'Fraunces',
          fontBody: 'Nunito Sans',
          radiusSelector: '9999px',
          radiusField: '0.5rem',
          radiusBox: '0.75rem',
          borderWidth: '1px',
          spaceBase: '0.26rem',
          sizeField: '2.75rem',
          sizeSelector: '2rem',
          depth: 0.9,
          containerWidth: 'medium',
        },
        light: {
          base100: '#fbfcfa',
          base200: '#ffffff',
          base300: '#eef2ea',
          baseContent: '#1f2a22',
          primary: '#4d7c5a',
          primaryContent: '#ffffff',
          secondary: '#7a8b6f',
          accent: '#a3b18a',
          neutral: '#1f2a22',
          border: '#dce5d5',
          ...STATUS_LIGHT,
        },
        dark: {
          base100: '#0e1611',
          base200: '#141f18',
          base300: '#1c2a21',
          baseContent: '#e7ede3',
          primary: '#6fa67e',
          primaryContent: '#0e1611',
          secondary: '#8ba07d',
          accent: '#b6c49c',
          neutral: '#e7ede3',
          border: '#233127',
          ...STATUS_DARK,
        },
      },
    },
  },
  {
    slug: 'coast',
    name: 'Coast',
    accent: '#0e7490',
    mood: 'Fresh',
    colorFamily: 'Teal',
    density: 'Standard',
    industry: 'Travel & Hospitality',
    tagline: 'Airy and coastal — teal-blue with a warm sand accent and rounded shapes.',
    description:
      'A breezy teal-blue palette with a sand accent and rounded shapes. Coast is built for travel, hospitality, home, and lifestyle brands that want light, open, and inviting.',
    sortWeight: 48,
    preset: {
      v: 1,
      v1: {
        light: {
          colorPrimary: '#0e7490',
          colorPrimaryForeground: '#ffffff',
          colorAccent: '#f4a259',
          colorBackground: '#fbfdfe',
          colorForeground: '#11303a',
          colorMuted: '#e8f3f6',
          colorBorder: '#cfe6ec',
          fontHeading: 'Poppins',
          fontBody: 'Inter',
          radiusBase: '1rem',
          containerWidth: 'wide',
        },
        dark: {
          colorPrimary: '#22a7c4',
          colorPrimaryForeground: '#052730',
          colorAccent: '#f4a259',
          colorBackground: '#06212a',
          colorForeground: '#ddeef2',
          colorMuted: '#0c2e38',
          colorBorder: '#144450',
          fontHeading: 'Poppins',
          fontBody: 'Inter',
          radiusBase: '1rem',
          containerWidth: 'wide',
        },
      },
      v2: {
        shared: {
          fontHeading: 'Poppins',
          fontBody: 'Inter',
          radiusSelector: '9999px',
          radiusField: '0.625rem',
          radiusBox: '1rem',
          borderWidth: '1px',
          spaceBase: '0.27rem',
          sizeField: '2.75rem',
          sizeSelector: '2rem',
          depth: 1.0,
          containerWidth: 'wide',
        },
        light: {
          base100: '#fbfdfe',
          base200: '#ffffff',
          base300: '#e8f3f6',
          baseContent: '#11303a',
          primary: '#0e7490',
          primaryContent: '#ffffff',
          secondary: '#2a9d8f',
          accent: '#f4a259',
          neutral: '#11303a',
          border: '#cfe6ec',
          ...STATUS_LIGHT,
        },
        dark: {
          base100: '#06212a',
          base200: '#0b2c36',
          base300: '#123a46',
          baseContent: '#ddeef2',
          primary: '#22a7c4',
          primaryContent: '#052730',
          secondary: '#2dd4bf',
          accent: '#f4a259',
          neutral: '#ddeef2',
          border: '#144450',
          ...STATUS_DARK,
        },
      },
    },
  },
  {
    slug: 'ember',
    name: 'Ember',
    accent: '#e8590c',
    mood: 'Vibrant',
    colorFamily: 'Orange',
    density: 'Standard',
    industry: 'Food & Beverage',
    tagline: 'Warm and energetic — ember orange and raspberry, punchy and appetizing.',
    description:
      'A warm, high-energy palette of ember orange and raspberry. Ember is tuned for food, drink, fitness, and events that want appetite, momentum, and a little heat.',
    sortWeight: 50,
    preset: {
      v: 1,
      v1: {
        light: {
          colorPrimary: '#e8590c',
          colorPrimaryForeground: '#ffffff',
          colorAccent: '#c2255c',
          colorBackground: '#fffcf9',
          colorForeground: '#2b1a12',
          colorMuted: '#fbefe7',
          colorBorder: '#f3dccb',
          fontHeading: 'Sora',
          fontBody: 'Inter',
          radiusBase: '0.5rem',
          containerWidth: 'medium',
        },
        dark: {
          colorPrimary: '#ff7a33',
          colorPrimaryForeground: '#1a0e07',
          colorAccent: '#f35e94',
          colorBackground: '#1a0e07',
          colorForeground: '#f3e7de',
          colorMuted: '#24140c',
          colorBorder: '#3a2114',
          fontHeading: 'Sora',
          fontBody: 'Inter',
          radiusBase: '0.5rem',
          containerWidth: 'medium',
        },
      },
      v2: {
        shared: {
          fontHeading: 'Sora',
          fontBody: 'Inter',
          radiusSelector: '9999px',
          radiusField: '0.5rem',
          radiusBox: '0.625rem',
          borderWidth: '1px',
          spaceBase: '0.25rem',
          sizeField: '2.75rem',
          sizeSelector: '2rem',
          depth: 1.2,
          containerWidth: 'medium',
        },
        light: {
          base100: '#fffcf9',
          base200: '#ffffff',
          base300: '#fbefe7',
          baseContent: '#2b1a12',
          primary: '#e8590c',
          primaryContent: '#ffffff',
          secondary: '#c2255c',
          accent: '#f59f00',
          neutral: '#2b1a12',
          border: '#f3dccb',
          ...STATUS_LIGHT,
        },
        dark: {
          base100: '#1a0e07',
          base200: '#24140c',
          base300: '#301b10',
          baseContent: '#f3e7de',
          primary: '#ff7a33',
          primaryContent: '#1a0e07',
          secondary: '#f35e94',
          accent: '#ffc94d',
          neutral: '#f3e7de',
          border: '#3a2114',
          ...STATUS_DARK,
        },
      },
    },
  },
  {
    slug: 'mono',
    name: 'Mono',
    accent: '#111111',
    mood: 'Minimal',
    colorFamily: 'Mono',
    density: 'Standard',
    industry: 'Agency & Portfolio',
    tagline: 'Strict monochrome — black, white, and grey with square edges.',
    description:
      'Black, white, and grey with zero radius and confident type. Mono gets out of the way so content and imagery carry the page — ideal for agencies, portfolios, and photographers.',
    sortWeight: 46,
    preset: {
      v: 1,
      v1: {
        light: {
          colorPrimary: '#111111',
          colorPrimaryForeground: '#ffffff',
          colorAccent: '#111111',
          colorBackground: '#ffffff',
          colorForeground: '#111111',
          colorMuted: '#f4f4f5',
          colorBorder: '#e4e4e7',
          fontHeading: 'Archivo',
          fontBody: 'Inter',
          radiusBase: '0px',
          containerWidth: 'wide',
        },
        dark: {
          colorPrimary: '#fafafa',
          colorPrimaryForeground: '#111111',
          colorAccent: '#fafafa',
          colorBackground: '#0a0a0a',
          colorForeground: '#fafafa',
          colorMuted: '#161616',
          colorBorder: '#262626',
          fontHeading: 'Archivo',
          fontBody: 'Inter',
          radiusBase: '0px',
          containerWidth: 'wide',
        },
      },
      v2: {
        shared: {
          fontHeading: 'Archivo',
          fontBody: 'Inter',
          radiusSelector: '0px',
          radiusField: '0px',
          radiusBox: '0px',
          borderWidth: '1px',
          spaceBase: '0.25rem',
          sizeField: '2.75rem',
          sizeSelector: '2rem',
          depth: 0.3,
          containerWidth: 'wide',
        },
        light: {
          base100: '#ffffff',
          base200: '#fafafa',
          base300: '#f4f4f5',
          baseContent: '#111111',
          primary: '#111111',
          primaryContent: '#ffffff',
          secondary: '#52525b',
          accent: '#111111',
          neutral: '#111111',
          border: '#e4e4e7',
          ...STATUS_LIGHT,
        },
        dark: {
          base100: '#0a0a0a',
          base200: '#141414',
          base300: '#1f1f1f',
          baseContent: '#fafafa',
          primary: '#fafafa',
          primaryContent: '#111111',
          secondary: '#a1a1aa',
          accent: '#fafafa',
          neutral: '#fafafa',
          border: '#262626',
          ...STATUS_DARK,
        },
      },
    },
  },
  {
    slug: 'bloom',
    name: 'Bloom',
    accent: '#db2777',
    mood: 'Playful',
    colorFamily: 'Pink',
    density: 'Standard',
    industry: 'Crafts & Kids',
    tagline: 'Playful and soft — pink and violet, generous rounding, friendly type.',
    description:
      'Pink and violet over soft surfaces, rounded shapes, and friendly type. Bloom brings warmth and joy to kids, crafts, bakeries, and any brand that wants to feel approachable.',
    sortWeight: 44,
    preset: {
      v: 1,
      v1: {
        light: {
          colorPrimary: '#db2777',
          colorPrimaryForeground: '#ffffff',
          colorAccent: '#8b5cf6',
          colorBackground: '#fffbfe',
          colorForeground: '#3a1e33',
          colorMuted: '#fbeef6',
          colorBorder: '#f4d9ea',
          fontHeading: 'Quicksand',
          fontBody: 'Nunito',
          radiusBase: '1.25rem',
          containerWidth: 'medium',
        },
        dark: {
          colorPrimary: '#f472b6',
          colorPrimaryForeground: '#2a0e1f',
          colorAccent: '#a78bfa',
          colorBackground: '#1c0e18',
          colorForeground: '#f6e6f0',
          colorMuted: '#271020',
          colorBorder: '#3d1c33',
          fontHeading: 'Quicksand',
          fontBody: 'Nunito',
          radiusBase: '1.25rem',
          containerWidth: 'medium',
        },
      },
      v2: {
        shared: {
          fontHeading: 'Quicksand',
          fontBody: 'Nunito',
          radiusSelector: '9999px',
          radiusField: '0.875rem',
          radiusBox: '1.25rem',
          borderWidth: '1px',
          spaceBase: '0.27rem',
          sizeField: '2.75rem',
          sizeSelector: '2rem',
          depth: 1.3,
          containerWidth: 'medium',
        },
        light: {
          base100: '#fffbfe',
          base200: '#ffffff',
          base300: '#fbeef6',
          baseContent: '#3a1e33',
          primary: '#db2777',
          primaryContent: '#ffffff',
          secondary: '#ec4899',
          accent: '#8b5cf6',
          neutral: '#3a1e33',
          border: '#f4d9ea',
          ...STATUS_LIGHT,
        },
        dark: {
          base100: '#1c0e18',
          base200: '#271020',
          base300: '#34182b',
          baseContent: '#f6e6f0',
          primary: '#f472b6',
          primaryContent: '#2a0e1f',
          secondary: '#f9a8d4',
          accent: '#a78bfa',
          neutral: '#f6e6f0',
          border: '#3d1c33',
          ...STATUS_DARK,
        },
      },
    },
  },
  {
    slug: 'meridian',
    name: 'Meridian',
    accent: '#1e3a8a',
    mood: 'Professional',
    colorFamily: 'Blue',
    density: 'Wide',
    industry: 'Professional Services',
    tagline: 'Professional and trustworthy — navy with a sky accent, crisp and wide.',
    description:
      'Navy with a sky-blue accent, tight corners, and a wide, structured layout. Meridian reads as competent and trustworthy — made for professional services, SaaS, and B2B.',
    sortWeight: 54,
    preset: {
      v: 1,
      v1: {
        light: {
          colorPrimary: '#1e3a8a',
          colorPrimaryForeground: '#ffffff',
          colorAccent: '#0ea5e9',
          colorBackground: '#ffffff',
          colorForeground: '#0f1b33',
          colorMuted: '#f1f5fb',
          colorBorder: '#dce5f1',
          fontHeading: 'Manrope',
          fontBody: 'Inter',
          radiusBase: '0.375rem',
          containerWidth: 'wide',
        },
        dark: {
          colorPrimary: '#3b5bdb',
          colorPrimaryForeground: '#ffffff',
          colorAccent: '#38bdf8',
          colorBackground: '#0a1124',
          colorForeground: '#dce6f5',
          colorMuted: '#111a33',
          colorBorder: '#1e2a48',
          fontHeading: 'Manrope',
          fontBody: 'Inter',
          radiusBase: '0.375rem',
          containerWidth: 'wide',
        },
      },
      v2: {
        shared: {
          fontHeading: 'Manrope',
          fontBody: 'Inter',
          radiusSelector: '0.375rem',
          radiusField: '0.375rem',
          radiusBox: '0.5rem',
          borderWidth: '1px',
          spaceBase: '0.24rem',
          sizeField: '2.625rem',
          sizeSelector: '2rem',
          depth: 0.6,
          containerWidth: 'wide',
        },
        light: {
          base100: '#ffffff',
          base200: '#f8fafc',
          base300: '#f1f5fb',
          baseContent: '#0f1b33',
          primary: '#1e3a8a',
          primaryContent: '#ffffff',
          secondary: '#0e7490',
          accent: '#0ea5e9',
          neutral: '#0f1b33',
          border: '#dce5f1',
          ...STATUS_LIGHT,
        },
        dark: {
          base100: '#0a1124',
          base200: '#111a33',
          base300: '#18233f',
          baseContent: '#dce6f5',
          primary: '#3b5bdb',
          primaryContent: '#ffffff',
          secondary: '#22d3ee',
          accent: '#38bdf8',
          neutral: '#dce6f5',
          border: '#1e2a48',
          ...STATUS_DARK,
        },
      },
    },
  },
  {
    slug: 'terra',
    name: 'Terra',
    accent: '#9a3412',
    mood: 'Earthy',
    colorFamily: 'Terracotta',
    density: 'Standard',
    industry: 'Makers & Home',
    tagline: 'Earthy and handmade — terracotta and olive over warm sandy neutrals.',
    description:
      'Terracotta and olive over warm, sandy neutrals with a serif headline. Terra feels handmade and grounded — a natural fit for makers, pottery, home goods, and roasters.',
    sortWeight: 42,
    preset: {
      v: 1,
      v1: {
        light: {
          colorPrimary: '#9a3412',
          colorPrimaryForeground: '#fff7ed',
          colorAccent: '#4d7c0f',
          colorBackground: '#fdfbf7',
          colorForeground: '#2e2016',
          colorMuted: '#f4ebdf',
          colorBorder: '#e6d6c2',
          fontHeading: 'Fraunces',
          fontBody: 'Inter',
          radiusBase: '0.5rem',
          containerWidth: 'medium',
        },
        dark: {
          colorPrimary: '#c2410c',
          colorPrimaryForeground: '#fff7ed',
          colorAccent: '#84cc16',
          colorBackground: '#1a120a',
          colorForeground: '#efe3d5',
          colorMuted: '#241910',
          colorBorder: '#382616',
          fontHeading: 'Fraunces',
          fontBody: 'Inter',
          radiusBase: '0.5rem',
          containerWidth: 'medium',
        },
      },
      v2: {
        shared: {
          fontHeading: 'Fraunces',
          fontBody: 'Inter',
          radiusSelector: '0.5rem',
          radiusField: '0.375rem',
          radiusBox: '0.5rem',
          borderWidth: '1px',
          spaceBase: '0.26rem',
          sizeField: '2.75rem',
          sizeSelector: '2rem',
          depth: 0.9,
          containerWidth: 'medium',
        },
        light: {
          base100: '#fdfbf7',
          base200: '#ffffff',
          base300: '#f4ebdf',
          baseContent: '#2e2016',
          primary: '#9a3412',
          primaryContent: '#fff7ed',
          secondary: '#b45309',
          accent: '#4d7c0f',
          neutral: '#2e2016',
          border: '#e6d6c2',
          ...STATUS_LIGHT,
        },
        dark: {
          base100: '#1a120a',
          base200: '#241910',
          base300: '#312316',
          baseContent: '#efe3d5',
          primary: '#c2410c',
          primaryContent: '#fff7ed',
          secondary: '#d97706',
          accent: '#84cc16',
          neutral: '#efe3d5',
          border: '#382616',
          ...STATUS_DARK,
        },
      },
    },
  },
  {
    slug: 'pulse',
    name: 'Pulse',
    accent: '#6d28d9',
    mood: 'Bold',
    colorFamily: 'Violet',
    density: 'Standard',
    industry: 'Tech & Electronics',
    tagline: 'Electric and modern — violet and cyan, glowing over deep ink in dark mode.',
    description:
      'Violet and cyan that glow against deep ink, with a technical sans headline. Pulse is built for tech, gaming, electronics, and hype-driven DTC that want a modern, electric edge.',
    sortWeight: 47,
    preset: {
      v: 1,
      v1: {
        light: {
          colorPrimary: '#6d28d9',
          colorPrimaryForeground: '#ffffff',
          colorAccent: '#06b6d4',
          colorBackground: '#ffffff',
          colorForeground: '#18122b',
          colorMuted: '#f3f0fb',
          colorBorder: '#e4def5',
          fontHeading: 'Space Grotesk',
          fontBody: 'Inter',
          radiusBase: '0.75rem',
          containerWidth: 'wide',
        },
        dark: {
          colorPrimary: '#8b5cf6',
          colorPrimaryForeground: '#0b0716',
          colorAccent: '#22d3ee',
          colorBackground: '#0a0712',
          colorForeground: '#ede9f7',
          colorMuted: '#130c24',
          colorBorder: '#241a3d',
          fontHeading: 'Space Grotesk',
          fontBody: 'Inter',
          radiusBase: '0.75rem',
          containerWidth: 'wide',
        },
      },
      v2: {
        shared: {
          fontHeading: 'Space Grotesk',
          fontBody: 'Inter',
          radiusSelector: '9999px',
          radiusField: '0.5rem',
          radiusBox: '0.75rem',
          borderWidth: '1px',
          spaceBase: '0.25rem',
          sizeField: '2.875rem',
          sizeSelector: '2.125rem',
          depth: 1.4,
          containerWidth: 'wide',
        },
        light: {
          base100: '#ffffff',
          base200: '#faf9fe',
          base300: '#f3f0fb',
          baseContent: '#18122b',
          primary: '#6d28d9',
          primaryContent: '#ffffff',
          secondary: '#db2777',
          accent: '#06b6d4',
          neutral: '#18122b',
          border: '#e4def5',
          ...STATUS_LIGHT,
        },
        dark: {
          base100: '#0a0712',
          base200: '#130c24',
          base300: '#1c1335',
          baseContent: '#ede9f7',
          primary: '#8b5cf6',
          primaryContent: '#0b0716',
          secondary: '#f472b6',
          accent: '#22d3ee',
          neutral: '#ede9f7',
          border: '#241a3d',
          ...STATUS_DARK,
        },
      },
    },
  },
  {
    slug: 'linen',
    name: 'Linen',
    accent: '#a8755a',
    mood: 'Editorial',
    colorFamily: 'Stone',
    density: 'Spacious',
    industry: 'Apparel & Lifestyle',
    tagline: 'Soft and editorial — warm charcoal and clay over creamy neutrals.',
    description:
      'Warm charcoal and clay over creamy linen neutrals, with classic serif headings. Linen has a quiet editorial polish suited to apparel, lifestyle, and stationery brands.',
    sortWeight: 49,
    preset: {
      v: 1,
      v1: {
        light: {
          colorPrimary: '#44403c',
          colorPrimaryForeground: '#faf8f5',
          colorAccent: '#a8755a',
          colorBackground: '#faf8f4',
          colorForeground: '#292524',
          colorMuted: '#f1ede6',
          colorBorder: '#e4ddd2',
          fontHeading: 'Libre Baskerville',
          fontBody: 'Inter',
          radiusBase: '0.25rem',
          containerWidth: 'wide',
        },
        dark: {
          colorPrimary: '#e7e2da',
          colorPrimaryForeground: '#1c1a17',
          colorAccent: '#c18f73',
          colorBackground: '#161412',
          colorForeground: '#ece7df',
          colorMuted: '#201d18',
          colorBorder: '#322d25',
          fontHeading: 'Libre Baskerville',
          fontBody: 'Inter',
          radiusBase: '0.25rem',
          containerWidth: 'wide',
        },
      },
      v2: {
        shared: {
          fontHeading: 'Libre Baskerville',
          fontBody: 'Inter',
          radiusSelector: '0.25rem',
          radiusField: '0.25rem',
          radiusBox: '0.25rem',
          borderWidth: '1px',
          spaceBase: '0.28rem',
          sizeField: '2.875rem',
          sizeSelector: '2.125rem',
          depth: 0.4,
          containerWidth: 'wide',
        },
        light: {
          base100: '#faf8f4',
          base200: '#ffffff',
          base300: '#f1ede6',
          baseContent: '#292524',
          primary: '#44403c',
          primaryContent: '#faf8f5',
          secondary: '#78716c',
          accent: '#a8755a',
          neutral: '#292524',
          border: '#e4ddd2',
          ...STATUS_LIGHT,
        },
        dark: {
          base100: '#161412',
          base200: '#201d18',
          base300: '#2a261f',
          baseContent: '#ece7df',
          primary: '#e7e2da',
          primaryContent: '#1c1a17',
          secondary: '#a8a29e',
          accent: '#c18f73',
          neutral: '#ece7df',
          border: '#322d25',
          ...STATUS_DARK,
        },
      },
    },
  },
];
