// sparx — Playful Mission: a reference-driven SITE TEMPLATE (docs/templates/*),
// composed distinct — its own home section sequence, example commerce, and journal —
// and dressed in the bespoke theme its DESIGN.md pins.
//
// GENERATED by marketplace-catalog/_gen/gen-template-playful-mission.ts
// via the shared _gen/template-sites/harness.ts — do NOT hand-edit; edit the generator
// and regenerate. A blueprint is PURE DATA: the loader `import()`s this module with no
// workspace resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import content from './content.json' with { type: 'json' };
import authors from './authors.json' with { type: 'json' };
import commerce from './commerce.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };
import emails from './emails.json' with { type: 'json' };

const blueprint = {
    key: 'sparx-playful-mission',
    version: '1.4.0',
    name: 'sparx — Playful Mission',
    summary:
        'A playful, colorful, mission-driven DTC storefront for a give-back brand — a warm-cream page broken up by saturated color bands (a marigold buy-one-give-one band, a navy impact stat, a sage "the rest" band) over a rhythm of shoppable carousels, in a bright `romp` theme. Modelled on the playful give-back DTC archetype; shipped as Rally, a pet-supplies brand that gives one item to a shelter for every one sold.',
    vertical: 'retail',
    preview: 'media/preview.png',
    requiresModules: ['builder', 'commerce', 'cms', 'crm', 'email'],

    // Identity only (business name + tagline + fonts + the theme's hex colors). The look
    // itself rides site.theme + the theme decl below; the installing tenant rebrands the name.
    brand: {
        businessName: 'Rally',
        tagline: 'Every wag does some good.',
        colors: {
            primary: '#eab532',
            primaryForeground: '#0f0a03',
            accent: '#a6c99f',
            secondary: '#2e4362',
        },
        fonts: {
            heading: 'Syne',
            body: 'Nunito',
        },
    },

    // The provisioned SiteTheme the installer creates + applies — the bespoke template
    // look as a tenant-editable saved theme (base preset = the template's own theme key,
    // plus its brand snapshot).
    theme: {
        name: 'playful-mission',
        basePresetKey: 'playful-mission',
        presentation: {
            v: 2,
            containerWidth: '1152px',
        },
        brand: {
            colorPrimary: '#eab532',
            colorAccent: '#a6c99f',
            colorSecondary: '#2e4362',
            fontHeading: 'Syne',
            fontBody: 'Nunito',
            tokens: {},
        },
        apply: true,
    },

    assets,
    contentTypes: [],
    authors,
    content,
    commerce,

    // A shop's brand-voiced MARKETING starters (a welcome + a win-back), tokenized so a fork
    // re-themes to the tenant and installed as DRAFTS — the platform's keyed transactional
    // defaults (order/shipping/dunning) are separate and never duplicated here. Content
    // templates ship an empty set.
    emails,
    sequences: [],

    // The composed distinct site (frame + a template-specific home + standard commerce/
    // cms/about/contact pages + the /journal index), in the bespoke theme, fully stamped.
    site,
};

export default blueprint;
