// @sparx/operator — dependency-free operator contracts shared across the admin
// console (apps/admin), the operator auth package (@sparx/operator-auth), and
// api-rest's /internal/operator/* handlers. See docs/apps/admin/build-plan.md.

export {
  OPERATOR_CAPABILITIES,
  OPERATOR_CAPABILITY_LABELS,
  CAPABILITY_BUNDLES,
  bundleCapabilities,
  isOperatorCapability,
  type OperatorCapability,
  type CapabilityBundle,
} from './capabilities';

export {
  createOperatorApiClient,
  OperatorApiError,
  INTERNAL_OPERATOR_TOKEN_HEADER,
  OPERATOR_ID_HEADER,
  type OperatorApiClient,
  type OperatorApiClientConfig,
  type OperatorApiRequestOptions,
} from './api-client';

export type {
  OperatorIdentity,
  OperatorWhoAmIResult,
  OperatorApiErrorBody,
  OperatorBillingInterval,
  OperatorTenantListItem,
  OperatorTenantListResult,
  OperatorTenantListParams,
  OperatorTenantModule,
  OperatorTenantBilling,
  OperatorTenantDomain,
  OperatorTenantStorage,
  OperatorTenantActivity,
  OperatorTenantDetail,
  OperatorMetricsLifecycle,
  OperatorMetricsModule,
  OperatorMetricsRevenue,
  OperatorMetricsSignupPoint,
  OperatorMetricsSignups,
  OperatorMetricsChurn,
  OperatorMetricsResult,
  OperatorMetricsParams,
  OperatorStripeEvent,
  OperatorCharge,
  OperatorCoupon,
  OperatorRefundReason,
  OperatorRefundInput,
  OperatorRefundResult,
  OperatorCouponInput,
  OperatorInvoiceLine,
  OperatorInvoiceInput,
  OperatorInvoiceResult,
  OperatorTenantBillingView,
  OperatorDomainSslStatus,
  OperatorDomainListItem,
  OperatorDomainCounts,
  OperatorDomainListResult,
  OperatorDomainListParams,
  OperatorDomainDnsRecord,
  OperatorDomainDnsProbe,
  OperatorDomainPurchase,
  OperatorDomainVerificationMethod,
  OperatorDomainDetail,
  OperatorDomainReverifyResult,
  OperatorOrderHit,
  OperatorOrderSearchResult,
  OperatorCustomerHit,
  OperatorCustomerSearchResult,
  OperatorSupportSearchParams,
  OperatorSearchIndexCollection,
  OperatorSearchIndexStatus,
  OperatorReindexCollection,
  OperatorReindexInput,
  OperatorReindexResult,
  OperatorEmailEvent,
  OperatorEmailLogParams,
  OperatorEmailLogResult,
  OperatorResendConfirmationResult,
  OperatorFeedbackStatus,
  OperatorFeedbackCategory,
  OperatorFeedbackItem,
  OperatorFeedbackCounts,
  OperatorFeedbackListResult,
  OperatorFeedbackListParams,
  OperatorFeedbackMessage,
  OperatorFeedbackDetail,
  OperatorFeedbackTriageInput,
  OperatorFeedbackReplyInput,
  OperatorModuleToggleInput,
  OperatorModuleToggleResult,
  OperatorSuspendInput,
  OperatorTenantStatusResult,
  OperatorStorageLimitInput,
  OperatorStorageLimitResult,
  OperatorPartnerTier,
  OperatorPartnerApplication,
  OperatorPartnerListItem,
  OperatorPartnerReferral,
  OperatorPartnerCommission,
  OperatorPartnerPayoutRun,
  OperatorPartnerKpis,
  OperatorPartnerDetail,
  OperatorPartnerApproveInput,
  OperatorPartnerRejectInput,
  OperatorPartnerTierInput,
  OperatorPartnerStatusInput,
  OperatorPayoutRunResult,
  OperatorCommissionApproveResult,
  OperatorBootcampCard,
  OperatorBootcampListResult,
} from './types';
