// @sparx/inventory — the supply-domain service layer (warehouses, stock levels +
// movement ledger, reservations, lots/serials, low-stock). The single source of
// truth for stock; Commerce/B2B/Dropship are consumers. Extracted from
// @sparx/commerce per docs/100.

export { inventoryService } from './services';

export {
  InventoryNotFoundError,
  InventoryValidationError,
  InventoryConflictError,
  InventoryOutOfStockError,
} from './errors';
export type {
  ServiceContext,
  NotFoundError,
  ValidationError,
  ConflictError,
  OutOfStockError,
} from './errors';

export { publishInventoryEvent, indexInventoryEntity } from './events';
export type { InventoryTopic, InventoryEventInput } from './events';

export { computeAvailability } from './services/availability';
export type { AvailabilityLevel, VariantAvailability } from './services/availability';

// Resync a product's denormalized `inStock`/`lowStock` flags from current levels +
// variant policies. `Product.inStock` defaults to false and was previously only ever
// corrected by an inventory MOVEMENT (ledger/reservation) — so a variant created, or
// flipped to a sell-without-stock policy (`continue`/`preorder`), stayed stuck at
// "Sold out" on the search-backed PLP until an unrelated movement happened. Commerce
// (variant create/update) and the blueprint installer call this so the flag is correct
// the moment the product is sellable, with no inventory setup required.
export { syncProductInStock } from './services/internal';

// The one definition of "sellable" and "running low" — a raw-SQL fragment for
// database-side filters and a JS twin for rows already in memory. Every read
// path that decides whether a level is low routes through these.
export { SELLABLE_SQL, LOW_STOCK_SQL, sellableUnits, isLowStock } from './services/low-stock';

export type {
  WarehouseRow,
  InventoryLevelRow,
  ReservationResult,
  LotBatchRow,
  LowStockRow,
  SellLine,
  CommittedSale,
  SupplierRow,
  SupplierVariantRow,
  PurchaseOrderRow,
  PurchaseOrderLineRow,
  PurchaseOrderDetail,
  PurchaseOrderDocumentBrand,
  // Picking + packing (docs/146 Phase 4)
  PickListRow,
  PickListLineRow,
  PickListDetail,
  PickActionResult,
  PackageRow,
  PackageLineRow,
  PackageDetail,
  PackingSlipBrand,
  PackingSlipData,
  PackingSlipLine,
  PickThroughputReport,
  PickerThroughput,
  BinShortfall,
  PackThroughput,
  PickStrategy,
  GoodsReceiptRow,
  GoodsReceiptLineRow,
  GoodsReceiptDetail,
  ReorderFilter,
  ReorderSuggestions,
  ReorderGroup,
  ReorderSuggestionLine,
  UnsuppliedSuggestion,
  DraftReorderResult,
  DraftedPurchaseOrder,
  AutoDraftResult,
  AutoDraftOutcome,
  InventoryCountRow,
  InventoryCountLineRow,
  InventoryCountDetail,
  InventoryTransferRow,
  InventoryTransferLineRow,
  InventoryTransferDetail,
  MovementRow,
  ListMovementsFilter,
  LotRow,
  LotDetail,
  SerialRow,
  ListLotsFilter,
  ListSerialsFilter,
  FeedRow,
  IngestFeedInput,
  IngestFeedResult,
  SyncRunRow,
  UnmappedSkuRow,
  SyncHealth,
  ListSyncRunsFilter,
  ListUnmappedFilter,
  AgentEnrollmentState,
  PublicInventoryRow,
  ListInventoryFilter,
  LevelCountResult,
  BulkAdjustResult,
  BulkAdjustResultRow,
  InventoryValuationReport,
  TurnoverReport,
  AgingReport,
  AgingBucket,
  DeadStockItem,
  ReorderAnalysisReport,
  ReorderAnalysisRow,
  FleetHoldRow,
  AccountAvailabilityRow,
  ListFleetHoldsFilter,
  // Integrity + provenance (docs/146 Phase 1)
  ReconciliationRunRow,
  ReconciliationDriftRow,
  ListReconciliationRunsFilter,
  ListDriftsFilter,
  OversellIncidentInput,
  OversellIncidentRow,
  ListOversellIncidentsFilter,
  OversellSummary,
  StockProvenance,
  ProvenanceMovement,
  ProvenanceHold,
  ProvenanceSource,
  ProvenanceOptions,
  ChannelBufferRow,
  ListChannelBuffersFilter,
  ResolvedChannelBuffer,
  SourceFreshnessRow,
  FreshnessSweepResult,
  StalenessPenalty,
  ShrinkageReport,
  ShrinkageFilter,
  ShrinkageByReason,
  ShrinkageByWarehouse,
  ShrinkageTopVariant,
  ShrinkagePeriod,
  MovementExport,
  // Bins (docs/146 Phase 2)
  BinRow,
  BinContentRow,
  VariantBinRow,
  ListBinsFilter,
  PutAwaySuggestion,
  BinMovementInput,
  BinMovementResult,
  // Barcodes + scanning (docs/146 Phase 3)
  BarcodeRow,
  BarcodeMatch,
  BarcodeConflictRow,
  GeneratedBarcode,
  GenerateBarcodesResult,
  ScanKind,
  ScanMatch,
  ScanResolution,
  ResolveScanOptions,
  VariantScanMatch,
  BinScanMatch,
  DocumentScanMatch,
  LotScanMatch,
  SerialScanMatch,
  ScanContextType,
  ScanOutcome,
  ScanEnvelope,
  ScanActionResult,
  ReceivingSession,
  ReceivingSessionLine,
  ScanToReceiveInput,
  PostScannedReceiptInput,
  ScanToCountInput,
  ScanToTransferInput,
  ScanPutAwayInput,
  QueuedScan,
  ReplayResult,
  ScanEventRow,
  ListScanEventsFilter,
  // True cost (docs/146 Phase 5)
  CostingPolicyRow,
  ResolvedCosting,
  ChargeRow,
  ReceiptLandedCost,
  LineLandedCost,
  ChargeBreakdownRow,
  AllocatableLine,
  AllocatableCharge,
  ChargeAllocation,
  RevaluationResult,
  CostLayerRow,
  CostLayerSource,
  MovementCostBreakdownRow,
  AsOfValuationReport,
  AsOfValuationRow,
  PriceVarianceReport,
  PriceVarianceRow,
  CogsReport,
  CogsRow,
  GoodsReceiptChargeRow,
  // Units of measure + assembly (docs/146 Phase 6)
  UnitOfMeasureRow,
  VariantUomRow,
  VariantUomSetup,
  ResolvedLineUom,
  BomRow,
  BomDetail,
  BomComponentRow,
  BuildableReport,
  BuildableComponentRow,
  AssemblyOrderRow,
  AssemblyOrderDetail,
  AssemblyLineRow,
  // Planning intelligence (docs/146 Phase 7)
  PlanningPolicyRow,
  DemandVelocityRow,
  DemandSweepResult,
  LeadTimeRow,
  LeadTimeSweepResult,
  ListLeadTimesFilter,
  ResolvedLeadTime,
  ClassificationRow,
  ClassificationSweepResult,
  ListClassificationsFilter,
  ReorderPolicyRow,
  ReorderPlanResult,
  ListReorderPlansFilter,
  CountScheduleRow,
  ScheduleGenerationResult,
  PlanningSweepResult,
  PlanningSweepStage,
  PlanningSweepOptions,
  StockoutRiskReport,
  StockoutRiskRow,
  StockoutRiskFilter,
  SlowMoverReport,
  SlowMoverRow,
  SlowMoverKind,
  HoldingCostReport,
  PlanningProvenance,
  PlanningInput,
  InputConfidence,
} from './services/inventory-service';
