// sparx marketplace component — 'Text beside a ticked list' (Page structure). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 gap-10 @3xl:grid-cols-2',
            children: [
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-4',
                children: [
                  {
                    kind: 'element',
                    tag: 'h2',
                    class: 'text-3xl font-semibold text-base-content',
                    children: ['Why people choose us over a bigger firm'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: [
                      'We are not cheaper and we do not pretend to be. What we are is answerable — there is no call centre, no subcontractor, and no version of this where you cannot reach the person who did the work.',
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'div',
                    class: 'flex flex-wrap items-center gap-3',
                    children: [
                      {
                        kind: 'element',
                        tag: 'a',
                        class: 'btn btn-neutral btn-outline btn-lg',
                        attrs: {
                          href: '#',
                        },
                        children: ['Read about us'],
                      },
                    ],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'ul',
                class: 'flex flex-col',
                children: [
                  {
                    kind: 'element',
                    tag: 'li',
                    class: 'flex items-start gap-3 border-t border-base-300 py-4',
                    children: [
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-success',
                        children: ['✓'],
                      },
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-base text-base-content',
                        children: ['The same two people from quote to handover'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'li',
                    class: 'flex items-start gap-3 border-t border-base-300 py-4',
                    children: [
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-success',
                        children: ['✓'],
                      },
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-base text-base-content',
                        children: ['No subcontractors, ever'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'li',
                    class: 'flex items-start gap-3 border-t border-base-300 py-4',
                    children: [
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-success',
                        children: ['✓'],
                      },
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-base text-base-content',
                        children: ['Insurance certificates before you book'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'li',
                    class: 'flex items-start gap-3 border-t border-base-300 py-4',
                    children: [
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-success',
                        children: ['✓'],
                      },
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-base text-base-content',
                        children: ['References from jobs within five miles of you'],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
