// sparx marketplace component — 'Specification' (Comparison). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-col gap-3',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                children: ['Specification'],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'dl',
            class: 'grid grid-cols-1 gap-x-10 @2xl:grid-cols-2',
            children: [
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-1 border-t border-base-300 py-4',
                children: [
                  {
                    kind: 'element',
                    tag: 'dt',
                    class: 'text-base font-semibold text-base-content',
                    children: ['Material'],
                  },
                  {
                    kind: 'element',
                    tag: 'dd',
                    class: 'text-base text-base-content',
                    children: ['Solid European oak, 40 mm'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-1 border-t border-base-300 py-4',
                children: [
                  {
                    kind: 'element',
                    tag: 'dt',
                    class: 'text-base font-semibold text-base-content',
                    children: ['Finish'],
                  },
                  {
                    kind: 'element',
                    tag: 'dd',
                    class: 'text-base text-base-content',
                    children: ['Hardwax oil, three coats'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-1 border-t border-base-300 py-4',
                children: [
                  {
                    kind: 'element',
                    tag: 'dt',
                    class: 'text-base font-semibold text-base-content',
                    children: ['Dimensions'],
                  },
                  {
                    kind: 'element',
                    tag: 'dd',
                    class: 'text-base text-base-content',
                    children: ['Made to your measurements'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-1 border-t border-base-300 py-4',
                children: [
                  {
                    kind: 'element',
                    tag: 'dt',
                    class: 'text-base font-semibold text-base-content',
                    children: ['Lead time'],
                  },
                  {
                    kind: 'element',
                    tag: 'dd',
                    class: 'text-base text-base-content',
                    children: ['Four to six weeks'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-1 border-t border-base-300 py-4',
                children: [
                  {
                    kind: 'element',
                    tag: 'dt',
                    class: 'text-base font-semibold text-base-content',
                    children: ['Delivery'],
                  },
                  {
                    kind: 'element',
                    tag: 'dd',
                    class: 'text-base text-base-content',
                    children: ['Included within 50 miles'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-1 border-t border-base-300 py-4',
                children: [
                  {
                    kind: 'element',
                    tag: 'dt',
                    class: 'text-base font-semibold text-base-content',
                    children: ['Guarantee'],
                  },
                  {
                    kind: 'element',
                    tag: 'dd',
                    class: 'text-base text-base-content',
                    children: ['Ten years against defects'],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
