// sparx — Culture Bold: a reference-driven SITE TEMPLATE (docs/templates/*),
// composed distinct — its own home section sequence, example commerce, and journal —
// and dressed in the bespoke theme its DESIGN.md pins.
//
// GENERATED by marketplace-catalog/_gen/gen-template-culture-bold.ts
// via the shared _gen/template-sites/harness.ts — do NOT hand-edit; edit the generator
// and regenerate. A blueprint is PURE DATA: the loader `import()`s this module with no
// workspace resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import content from './content.json' with { type: 'json' };
import authors from './authors.json' with { type: 'json' };
import commerce from './commerce.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };
import emails from './emails.json' with { type: 'json' };

const blueprint = {
  key: 'sparx-culture-bold',
  version: '1.4.1',
  name: 'sparx — Culture Bold',
  summary:
    'A loud music & pop-culture magazine — a full-bleed feature lead over a dense feed, a signature ranked “most read” countdown, and a bespoke bylined article page, on a near-black ground with one hot crimson-magenta accent and heavy condensed display type. Modelled on the bold-culture-magazine archetype; shipped as Static. Ships a light store (vinyl + merch) to demonstrate content + commerce together.',
  vertical: 'content',
  preview: 'media/preview.png',
  requiresModules: ['builder', 'commerce', 'cms', 'crm', 'email'],

  // Identity only (business name + tagline + fonts + the theme's hex colors). The look
  // itself rides site.theme + the theme decl below; the installing tenant rebrands the name.
  brand: {
    businessName: 'Static',
    tagline: 'Loud, on purpose.',
    colors: {
      primary: '#eb3062',
      primaryForeground: '#130809',
      accent: '#f24e71',
      secondary: '#b7a6a7',
    },
    fonts: {
      heading: 'Oswald',
      body: 'Inter',
    },
  },

  // The provisioned SiteTheme the installer creates + applies — the bespoke template
  // look as a tenant-editable saved theme (base preset = the template's own theme key,
  // plus its brand snapshot).
  theme: {
    name: 'culture-bold',
    basePresetKey: 'culture-bold',
    presentation: {
      v: 2,
      containerWidth: '1152px',
    },
    brand: {
      colorPrimary: '#eb3062',
      colorAccent: '#f24e71',
      colorSecondary: '#b7a6a7',
      fontHeading: 'Oswald',
      fontBody: 'Inter',
      tokens: {},
    },
    apply: true,
  },

  assets,
  contentTypes: [],
  authors,
  content,
  commerce,

  // A shop's brand-voiced MARKETING starters (a welcome + a win-back), tokenized so a fork
  // re-themes to the tenant and installed as DRAFTS — the platform's keyed transactional
  // defaults (order/shipping/dunning) are separate and never duplicated here. Content
  // templates ship an empty set.
  emails,
  sequences: [],

  // The composed distinct site (frame + a template-specific home + standard commerce/
  // cms/about/contact pages + the /journal index), in the bespoke theme, fully stamped.
  site,
};

export default blueprint;
