// sparx marketplace component — 'The team' (People & proof). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-col gap-3',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                children: ['The people you will actually meet'],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 gap-6 @2xl:grid-cols-2 @4xl:grid-cols-3',
            children: [
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3',
                children: [
                  {
                    kind: 'element',
                    tag: 'img',
                    class:
                      'aspect-square w-full rounded-box border border-base-300 bg-base-200 object-cover',
                    attrs: {
                      src: '',
                      alt: 'Ada Mercer, Founder',
                      loading: 'lazy',
                    },
                  },
                  {
                    kind: 'element',
                    tag: 'div',
                    class: 'flex flex-col gap-1',
                    children: [
                      {
                        kind: 'element',
                        tag: 'h3',
                        class: 'text-lg font-semibold text-base-content',
                        children: ['Ada Mercer'],
                      },
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-base text-base-content',
                        children: ['Founder'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: [
                      'Started the workshop in 2016 and still does the measuring on every job.',
                    ],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3',
                children: [
                  {
                    kind: 'element',
                    tag: 'img',
                    class:
                      'aspect-square w-full rounded-box border border-base-300 bg-base-200 object-cover',
                    attrs: {
                      src: '',
                      alt: 'Tom Whitlock, Workshop lead',
                      loading: 'lazy',
                    },
                  },
                  {
                    kind: 'element',
                    tag: 'div',
                    class: 'flex flex-col gap-1',
                    children: [
                      {
                        kind: 'element',
                        tag: 'h3',
                        class: 'text-lg font-semibold text-base-content',
                        children: ['Tom Whitlock'],
                      },
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-base text-base-content',
                        children: ['Workshop lead'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: ['Twenty years on the bench. If it has a joint in it, he cut it.'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3',
                children: [
                  {
                    kind: 'element',
                    tag: 'img',
                    class:
                      'aspect-square w-full rounded-box border border-base-300 bg-base-200 object-cover',
                    attrs: {
                      src: '',
                      alt: 'Priya Raman, Project manager',
                      loading: 'lazy',
                    },
                  },
                  {
                    kind: 'element',
                    tag: 'div',
                    class: 'flex flex-col gap-1',
                    children: [
                      {
                        kind: 'element',
                        tag: 'h3',
                        class: 'text-lg font-semibold text-base-content',
                        children: ['Priya Raman'],
                      },
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-base text-base-content',
                        children: ['Project manager'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: ['The person who calls you before you have to call us.'],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
