export { prisma } from './client';
export { withTenant, withSystem } from './tenant-context';
export type { TenantContext, TxClient } from './tenant-context';

export type {
  Tenant,
  OnboardingChecklist,
  User,
  Session,
  Account,
  Verification,
  AuditLog,
  // CMS
  Page,
  ContentType,
  ContentEntry,
  ContentRevision,
  ContentReference,
  Taxonomy,
  TaxonomyTerm,
  EntryTaxonomyTerm,
  Author,
  Redirect,
  NavigationMenu,
  NavigationItem,
  PreviewToken,
  WebhookSubscription,
  WebhookDelivery,
  MediaAsset,
  MediaVariant,
  // CRM
  Customer,
  CustomerAddress,
  B2BAccount,
  Pipeline,
  PipelineStage,
  // Invoicing (docs/87)
  DocumentWorkflow,
  DocumentStage,
  BillingDocumentLineType,
  BillingDocument,
  BillingDocumentLine,
  BillingDocumentSnapshot,
  BillingDocumentPayment,
  BillingDocumentTemplate,
  Deal,
  DealOrder,
  DealQuote,
  CrmActivity,
  Task,
  Segment,
  SegmentMember,
  SavedView,
  // CRM — orders + child tables
  Order,
  OrderItem,
  OrderPayment,
  OrderRefund,
  OrderRefundItem,
  OrderFulfillment,
  OrderFulfillmentItem,
  // CRM — quotes
  Quote,
  QuoteItem,
  // Commerce — catalog
  Product,
  ProductTranslation,
  ProductOption,
  ProductOptionValue,
  ProductVariant,
  VariantImage,
  ProductCategory,
  CategoryProduct,
  ProductCollection,
  CollectionProduct,
  FitmentDomain,
  FitmentNode,
  ProductFitment,
  ProductFitmentRange,
  // Inventory module
  Warehouse,
  InventoryLevel,
  InventoryMovement,
  InventoryReservation,
  LotBatch,
  SerialUnit,
  Supplier,
  SupplierVariant,
  PurchaseOrder,
  PurchaseOrderLine,
  GoodsReceipt,
  GoodsReceiptLine,
  InventoryCount,
  InventoryCountLine,
  InventoryTransfer,
  InventoryTransferLine,
  // Commerce — pricing + promotions
  PriceList,
  PriceListEntry,
  BulkPriceTier,
  ContractPrice,
  MarkupRule,
  SurchargeRule,
  Discount,
  DiscountUsage,
  GiftCard,
  GiftCardTransaction,
  AccountCredit,
  AccountCreditTransaction,
  // Commerce — bundles + configurator
  Bundle,
  BundleComponent,
  ConfigurationTemplate,
  ConfigurationOption,
  ConfigurationRule,
  ConfigurationAddOn,
  // Commerce — cart + checkout + subscriptions
  Cart,
  CartItem,
  CartDiscount,
  CheckoutSession,
  Subscription,
  SubscriptionItem,
  SubscriptionEvent,
  DunningAttempt,
  // Commerce — reviews, returns, shipping, tax, providers, storefront
  ProductReview,
  ReviewMedia,
  ReviewHelpfulVote,
  ReviewModerationLog,
  ProductQuestion,
  ProductAnswer,
  Wishlist,
  WishlistItem,
  ReturnRequest,
  ReturnLineItem,
  ReturnInspection,
  ReturnLabel,
  ShippingZone,
  ShippingProfile,
  ShippingRate,
  TaxZone,
  TaxRate,
  TaxExemption,
  ProviderInstallation,
  ProviderWebhookEvent,
  CommerceSiteSettings,
  CommerceSiteTheme,
  // Sitebuilder
  SiteConfig,
  SiteVersion,
  PageLayout,
  SiteSection,
  SiteLayoutBlock,
  SitePublishSchedule,
  SiteTheme,
  SiteLayoutDefault,
  SiteLayoutAssignment,
  TenantSectionDefinition,
  // Builder
  BuilderPage,
  BuilderLayout,
  BuilderEmail,
  BuilderComponent,
  BuilderComponentVersion,
  BuilderGovernance,
  BuilderArchetype,
  // Platform component catalog (global, docs/98 §5)
  PlatformComponent,
  // Email platform
  EmailSettings,
  SendingDomain,
  ScheduledSend,
  Broadcast,
  EmailEvent,
  EmailSuppression,
  // Live Chat
  ChatConversation,
  ChatMessage,
  ChatQuickReply,
  // Scheduling (docs/79)
  SchedulingResource,
  SchedulingService,
  Booking,
  BookingResource,
  BookingAttendee,
  AvailabilityWindow,
  AvailabilityException,
  BookingSeries,
  WaitlistEntry,
  BookingPolicy,
  IntakeForm,
  IntakeSubmission,
  CalendarConnection,
  ExternalBusyBlock,
  BookingNotification,
  BusinessLocation,
} from '@prisma/client';

// `Prisma` is exported as a VALUE (not type-only) because callers need the
// runtime members — Prisma.DbNull / Prisma.JsonNull / Prisma.sql — in addition
// to the type namespace (Prisma.TransactionClient, Prisma.*WhereInput, …).
// Type-only consumers keep using `import type { Prisma } from '@sparx/db'`.
export { Prisma } from '@prisma/client';
