export { prisma } from './client';
export { withTenant } from './tenant-context';
export type { TenantContext, TxClient } from './tenant-context';

export type {
  Tenant,
  OnboardingChecklist,
  User,
  Session,
  Account,
  Verification,
  AuditLog,
  // CMS
  Page,
  ContentType,
  ContentEntry,
  ContentRevision,
  ContentReference,
  Taxonomy,
  TaxonomyTerm,
  EntryTaxonomyTerm,
  Author,
  Redirect,
  NavigationMenu,
  NavigationItem,
  PreviewToken,
  WebhookSubscription,
  WebhookDelivery,
  MediaAsset,
  MediaVariant,
  // CRM
  Customer,
  CustomerAddress,
  B2BAccount,
  Pipeline,
  PipelineStage,
  Deal,
  DealOrder,
  DealQuote,
  CrmActivity,
  Task,
  Segment,
  SegmentMember,
  SavedView,
  // CRM — orders + child tables
  Order,
  OrderItem,
  OrderPayment,
  OrderRefund,
  OrderRefundItem,
  OrderFulfillment,
  OrderFulfillmentItem,
  // CRM — quotes
  Quote,
  QuoteItem,
  // Commerce — catalog
  Product,
  ProductTranslation,
  ProductOption,
  ProductOptionValue,
  ProductVariant,
  VariantImage,
  ProductCategory,
  CategoryProduct,
  ProductCollection,
  CollectionProduct,
  FitmentDomain,
  FitmentCategory,
  FitmentItem,
  FitmentVariant,
  ProductFitment,
  // Commerce — inventory
  Warehouse,
  InventoryLevel,
  InventoryAdjustment,
  InventoryReservation,
  LotBatch,
  SerialUnit,
  // Commerce — pricing + promotions
  PriceList,
  PriceListEntry,
  BulkPriceTier,
  ContractPrice,
  MarkupRule,
  SurchargeRule,
  Discount,
  DiscountUsage,
  GiftCard,
  GiftCardTransaction,
  StoreCredit,
  StoreCreditTransaction,
  // Commerce — bundles + configurator
  Bundle,
  BundleComponent,
  ConfigurationTemplate,
  ConfigurationOption,
  ConfigurationRule,
  ConfigurationAddOn,
  // Commerce — cart + checkout + subscriptions
  Cart,
  CartItem,
  CartDiscount,
  CheckoutSession,
  Subscription,
  SubscriptionItem,
  SubscriptionEvent,
  DunningAttempt,
  // Commerce — reviews, returns, shipping, tax, providers, storefront
  ProductReview,
  ReviewMedia,
  ReviewHelpfulVote,
  ReviewModerationLog,
  ProductQuestion,
  ProductAnswer,
  Wishlist,
  WishlistItem,
  ReturnRequest,
  ReturnLineItem,
  ReturnInspection,
  ReturnLabel,
  ShippingZone,
  ShippingProfile,
  ShippingRate,
  TaxZone,
  TaxRate,
  TaxExemption,
  ProviderInstallation,
  ProviderWebhookEvent,
  StorefrontSettings,
  StorefrontTheme,
  // Sitebuilder
  SiteConfig,
  SiteVersion,
  PageLayout,
  SiteSection,
  SiteLayoutBlock,
  SitePublishSchedule,
  SiteTheme,
  SiteLayoutDefault,
  SiteLayoutAssignment,
  TenantSectionDefinition,
  // Builder
  BuilderPage,
  BuilderLayout,
  BuilderEmail,
  BuilderComponent,
  BuilderComponentVersion,
  // Email platform
  EmailSettings,
  SendingDomain,
  EmailTemplate,
  EmailAutomation,
  ScheduledSend,
  Broadcast,
  EmailEvent,
  EmailSuppression,
} from '@prisma/client';

// `Prisma` is exported as a VALUE (not type-only) because callers need the
// runtime members — Prisma.DbNull / Prisma.JsonNull / Prisma.sql — in addition
// to the type namespace (Prisma.TransactionClient, Prisma.*WhereInput, …).
// Type-only consumers keep using `import type { Prisma } from '@sparx/db'`.
export { Prisma } from '@prisma/client';
