// Meridian — a Sparx first-party marketplace theme (docs/85). The payload is a
// complete DataThemePreset (v1 storefront tokens + v2 preset); the ingest
// validates it and writes it to storage as the applied-at-runtime artifact.
export default {
  v: 1,
  v1: {
    light: {
      colorPrimary: '#1e3a8a',
      colorPrimaryForeground: '#ffffff',
      colorAccent: '#0ea5e9',
      colorBackground: '#ffffff',
      colorForeground: '#0f1b33',
      colorMuted: '#f1f5fb',
      colorBorder: '#dce5f1',
      fontHeading: 'Manrope',
      fontBody: 'Inter',
      radiusBase: '0.375rem',
      containerWidth: 'wide',
    },
    dark: {
      colorPrimary: '#3b5bdb',
      colorPrimaryForeground: '#ffffff',
      colorAccent: '#38bdf8',
      colorBackground: '#0a1124',
      colorForeground: '#dce6f5',
      colorMuted: '#111a33',
      colorBorder: '#1e2a48',
      fontHeading: 'Manrope',
      fontBody: 'Inter',
      radiusBase: '0.375rem',
      containerWidth: 'wide',
    },
  },
  v2: {
    shared: {
      fontHeading: 'Manrope',
      fontBody: 'Inter',
      radiusSelector: '0.375rem',
      radiusField: '0.375rem',
      radiusBox: '0.5rem',
      borderWidth: '1px',
      spaceBase: '0.24rem',
      sizeField: '2.625rem',
      sizeSelector: '2rem',
      depth: 0.6,
      containerWidth: 'wide',
    },
    light: {
      base100: '#ffffff',
      base200: '#f8fafc',
      base300: '#f1f5fb',
      baseContent: '#0f1b33',
      primary: '#1e3a8a',
      primaryContent: '#ffffff',
      secondary: '#0e7490',
      accent: '#0ea5e9',
      neutral: '#0f1b33',
      border: '#dce5f1',
      info: '#0284c7',
      success: '#16a34a',
      warning: '#d97706',
      danger: '#dc2626',
    },
    dark: {
      base100: '#0a1124',
      base200: '#111a33',
      base300: '#18233f',
      baseContent: '#dce6f5',
      primary: '#3b5bdb',
      primaryContent: '#ffffff',
      secondary: '#22d3ee',
      accent: '#38bdf8',
      neutral: '#dce6f5',
      border: '#1e2a48',
      info: '#38bdf8',
      success: '#4ade80',
      warning: '#fbbf24',
      danger: '#f87171',
    },
  },
};
