// Pulse — a Sparx first-party marketplace theme (docs/85). The payload is a
// complete DataThemePreset (v1 storefront tokens + v2 preset); the ingest
// validates it and writes it to storage as the applied-at-runtime artifact.
export default {
  v: 1,
  v1: {
    light: {
      colorPrimary: '#6d28d9',
      colorPrimaryForeground: '#ffffff',
      colorAccent: '#06b6d4',
      colorBackground: '#ffffff',
      colorForeground: '#18122b',
      colorMuted: '#f3f0fb',
      colorBorder: '#e4def5',
      fontHeading: 'Space Grotesk',
      fontBody: 'Inter',
      radiusBase: '0.75rem',
      containerWidth: 'wide',
    },
    dark: {
      colorPrimary: '#8b5cf6',
      colorPrimaryForeground: '#0b0716',
      colorAccent: '#22d3ee',
      colorBackground: '#0a0712',
      colorForeground: '#ede9f7',
      colorMuted: '#130c24',
      colorBorder: '#241a3d',
      fontHeading: 'Space Grotesk',
      fontBody: 'Inter',
      radiusBase: '0.75rem',
      containerWidth: 'wide',
    },
  },
  v2: {
    shared: {
      fontHeading: 'Space Grotesk',
      fontBody: 'Inter',
      radiusSelector: '9999px',
      radiusField: '0.5rem',
      radiusBox: '0.75rem',
      borderWidth: '1px',
      spaceBase: '0.25rem',
      sizeField: '2.875rem',
      sizeSelector: '2.125rem',
      depth: 1.4,
      containerWidth: 'wide',
    },
    light: {
      base100: '#ffffff',
      base200: '#faf9fe',
      base300: '#f3f0fb',
      baseContent: '#18122b',
      primary: '#6d28d9',
      primaryContent: '#ffffff',
      secondary: '#db2777',
      accent: '#06b6d4',
      neutral: '#18122b',
      border: '#e4def5',
      info: '#0284c7',
      success: '#16a34a',
      warning: '#d97706',
      danger: '#dc2626',
    },
    dark: {
      base100: '#0a0712',
      base200: '#130c24',
      base300: '#1c1335',
      baseContent: '#ede9f7',
      primary: '#8b5cf6',
      primaryContent: '#0b0716',
      secondary: '#f472b6',
      accent: '#22d3ee',
      neutral: '#ede9f7',
      border: '#241a3d',
      info: '#38bdf8',
      success: '#4ade80',
      warning: '#fbbf24',
      danger: '#f87171',
    },
  },
};
