// sparx marketplace component — 'Things worth reading' (Writing). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-200 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-col gap-3',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                children: ['Worth reading first'],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 gap-6 @2xl:grid-cols-2 @4xl:grid-cols-3',
            children: [
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3 rounded-box border border-base-300 bg-base-100 p-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['Choosing a timber'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: ['What each one is actually good at, and what it costs.'],
                  },
                  {
                    kind: 'element',
                    tag: 'a',
                    class: 'text-base font-semibold text-base-content',
                    attrs: {
                      href: '#',
                    },
                    children: ['Read it →'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3 rounded-box border border-base-300 bg-base-100 p-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['What a quote should contain'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: [
                      'The six lines that should be on it, so you can compare like with like.',
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'a',
                    class: 'text-base font-semibold text-base-content',
                    attrs: {
                      href: '#',
                    },
                    children: ['Read it →'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3 rounded-box border border-base-300 bg-base-100 p-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['Living with an oiled finish'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: ['Ten minutes twice a year, and it outlasts a lacquer.'],
                  },
                  {
                    kind: 'element',
                    tag: 'a',
                    class: 'text-base font-semibold text-base-content',
                    attrs: {
                      href: '#',
                    },
                    children: ['Read it →'],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
