// Ember — a sparx first-party marketplace theme (docs/85). The payload is a
// complete DataThemePreset (v1 storefront tokens + v2 preset); the ingest
// validates it and writes it to storage as the applied-at-runtime artifact.
export default {
  v: 1,
  v1: {
    light: {
      colorPrimary: '#e8590c',
      colorPrimaryForeground: '#ffffff',
      colorAccent: '#c2255c',
      colorBackground: '#fffcf9',
      colorForeground: '#2b1a12',
      colorMuted: '#fbefe7',
      colorBorder: '#f3dccb',
      fontHeading: 'Sora',
      fontBody: 'Inter',
      radiusBase: '0.5rem',
      containerWidth: 'medium',
    },
    dark: {
      colorPrimary: '#ff7a33',
      colorPrimaryForeground: '#1a0e07',
      colorAccent: '#f35e94',
      colorBackground: '#1a0e07',
      colorForeground: '#f3e7de',
      colorMuted: '#24140c',
      colorBorder: '#3a2114',
      fontHeading: 'Sora',
      fontBody: 'Inter',
      radiusBase: '0.5rem',
      containerWidth: 'medium',
    },
  },
  v2: {
    shared: {
      fontHeading: 'Sora',
      fontBody: 'Inter',
      radiusSelector: '9999px',
      radiusField: '0.5rem',
      radiusBox: '0.625rem',
      borderWidth: '1px',
      spaceBase: '0.25rem',
      sizeField: '2.75rem',
      sizeSelector: '2rem',
      depth: 1.2,
      containerWidth: 'medium',
    },
    light: {
      base100: '#fffcf9',
      base200: '#ffffff',
      base300: '#fbefe7',
      baseContent: '#2b1a12',
      primary: '#e8590c',
      primaryContent: '#ffffff',
      secondary: '#c2255c',
      accent: '#f59f00',
      neutral: '#2b1a12',
      border: '#f3dccb',
      info: '#0284c7',
      success: '#16a34a',
      warning: '#d97706',
      danger: '#dc2626',
    },
    dark: {
      base100: '#1a0e07',
      base200: '#24140c',
      base300: '#301b10',
      baseContent: '#f3e7de',
      primary: '#ff7a33',
      primaryContent: '#1a0e07',
      secondary: '#f35e94',
      accent: '#ffc94d',
      neutral: '#f3e7de',
      border: '#3a2114',
      info: '#38bdf8',
      success: '#4ade80',
      warning: '#fbbf24',
      danger: '#f87171',
    },
  },
};
