// customColorCss — the CSS a PUBLISHED site needs for a color the author invented
// in the builder's theme editor.
//
// THE GAP THIS CLOSES. silicaui's component classes are generated by its Tailwind
// plugin from a FIXED list: `@plugin '@wizeworks/silicaui' { colors: primary, …,
// highlight; }` in each app's `globals.css`. That list is a build-time constant, so
// `.btn-primary` / `.badge-danger` / `.bg-accent` ship in the static app bundle and
// cost nothing per request. A tenant-authored color cannot be on that list — the
// name is invented at runtime, long after the bundle was built.
//
// The builder's theme editor lets an author add one anyway ("brand", "sunset", …):
// `addColor` slugs the name to `[a-z0-9-]` and writes a single `--color-<name>`
// token into `theme.tokens`. The canvas then hydrates it live — silicaui-builder's
// own `customColorCss(theme, '.sui-canvas')` injects a scoped `<style>` so the
// author sees `btn-brand` painted while they work. Nothing carried that to publish:
// `theme.tokens` reached the storefront (`buildSilicaThemeCssFromTheme` projects
// every `--*` verbatim, so `--color-brand` IS declared) but not one rule CONSUMED
// it, so `class="btn btn-brand"` rendered as an unstyled button on the live site.
// Every gate in between passes the class through silently — sparx's class validator
// only rejects viewport variants, the engine floor only rejects `fixed`/`url(…)` —
// so the failure surfaced as "my color works in the editor and vanishes on the
// site", with nothing logged anywhere.
//
// HOW. Run silicaui's own Tailwind plugin twice against a fake Tailwind context —
// once WITHOUT the custom names, once WITH — and keep the rules only the second run
// produced. That difference is, by construction, exactly what the plugin would have
// emitted had the name been in the `colors:` list at build time. Every color-aware
// component participates (41 rules per name at 0.41.0: `.btn-`, `.badge-`, `.alert-`,
// `.input-`, `.tabs-`, `.toggle-`, `.step-`, … plus the `text-`/`bg-`/`border-`
// utility trio for the color AND its `-content`), and a component silicaui adds
// later is picked up with no change here. This is strictly WIDER than the canvas's
// own preview, which covers only `.btn-<name>` + the three utilities — so a published
// `badge-brand` now works even though the canvas still previews it bare (an upstream
// gap, tracked in docs/silicaui/01).
//
// Every COMPONENT rule is a pure var-setter (`--btn-bg: var(--color-brand)`) —
// silicaui's core design, and what makes injecting them at render time safe: they
// paint nothing themselves, they only supply values the static `.btn` / `.badge`
// rules already read, so they cannot out-specify anything. The three color UTILITIES
// (`.text-`/`.bg-`/`.border-`) do set one paint property each, at the same 0-1-0 the
// plugin gives them at build time.
//
// The output is wrapped in `@layer base` so it ranks EXACTLY where the plugin's own
// `addBase` output ranks (the storefront declares the order in `app/layers.css`).
// That is load-bearing, not decorative: `soft` / `glass` are the one family that must
// OUT-rank a color rule (`bg-brand soft` paints the tint, not the flat fill), and
// silicaui puts them in `utilities` precisely so the layer order settles it. Emitting
// unlayered would beat every layer and quietly break `soft` on custom colors alone.
// Injection order is not a hazard either way: if this block is parsed before
// `layers.css`, `base` is merely established first and the rest of the order appends
// after it — `utilities` stays highest, `base` stays lowest, and the one pair that
// swaps (`base`/`theme`) can only matter on a site with no silica theme, where this
// function has already returned ''.
//
// COST. Pure object building — no Tailwind compile, no I/O. `tailwindcss/plugin` is
// a 200-byte zero-dependency shim; the plugin itself is plain rule-map builders.
// Results are memoized per name-set, and a theme with no custom color returns ''
// after a `rolesOf` scan.

// `@wizeworks/silicaui` publishes no types (it ships to be consumed from CSS by
// `@plugin`, not imported), so the declarations live in the sibling `.d.ts`. It is
// REFERENCED rather than left ambient because a consuming app's tsconfig `include`
// covers only its own tree: an unreferenced declaration file in this package is
// invisible there, and wizeworks/apps/site failed with TS7016 while this package typechecked
// clean. A path reference is the only way to carry it across — there is no import
// form for a declaration that has no module to attach to.
// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="./silicaui-plugin.d.ts" />

import silicaPlugin from '@wizeworks/silicaui';
import { rolesOf, resolveThemeTokens, SEMANTIC_ROLES, type Theme } from '@wizeworks/silicaui-html';
// The SUPPORTED path, as of silicaui 0.45.0 (docs/silicaui/01 §19) — a render-path entry
// point that imports no React and emits the full registration.
import { customColorCss, customRolesOf } from '@wizeworks/silicaui-html/theme';

import { SPARX_RESIDUAL_COLOR_ROLES } from './resolve-sparx-theme';

/**
 * The roles a sparx site already has build-time CSS for, so nothing here needs to
 * generate them: silicaui's semantic eight plus the sparx residuals every theme
 * carries (`danger`, `highlight`, `border`).
 *
 * `rolesOf` alone is NOT the answer — it reports every `--color-*` outside silicaui's
 * own eight, which on a stock sparx theme is three false positives, ~123 rules of
 * duplicate CSS on every page, and a derived `--color-border-content` nobody asked
 * for. Overridable for a caller whose `@plugin { colors: … }` list differs.
 */
export const SPARX_REGISTERED_COLOR_ROLES: readonly string[] = [
  ...SEMANTIC_ROLES,
  ...SPARX_RESIDUAL_COLOR_ROLES,
];

/**
 * The name shape a custom role may take. Mirrors silicaui-builder's `addColor`
 * slug (`toLowerCase().replace(/[^a-z0-9-]/g,'-')`, trimmed of edge dashes) and
 * silicaui's own `DECL_RE` for pasted theme CSS.
 *
 * Enforced HERE rather than trusted because a role name becomes a CSS SELECTOR
 * (`.btn-<name>`), and `theme.tokens` is not a validated surface: `SilicaThemeInput`
 * stores the key map opaquely (`z.record(z.string(), z.unknown())`), so a blueprint
 * import or an `set_silica_theme` MCP call can put any string there. A name that
 * doesn't match is dropped, not escaped — there is no legitimate color called
 * `x{}body{display:none}`.
 */
const ROLE_NAME_RE = /^[a-z][a-z0-9-]*$/;

/** Belt-and-braces cap: a name long enough to matter is a payload, not a color. */
const MAX_ROLE_NAME = 48;

/**
 * The tenant-authored color roles in a theme — every `--color-<name>` that isn't
 * already registered, isn't a surface-ramp token, and isn't a `-content` pair
 * (`rolesOf` handles the latter two), narrowed to names safe to put in a selector.
 *
 * Deduped and sorted so the memo key is stable regardless of token insertion order.
 */
export function customColorRoles(
  theme: Theme,
  registered: readonly string[] = SPARX_REGISTERED_COLOR_ROLES
): string[] {
  const known = new Set(registered);
  const names = rolesOf(theme).filter(
    (name) => !known.has(name) && name.length <= MAX_ROLE_NAME && ROLE_NAME_RE.test(name)
  );
  return [...new Set(names)].sort();
}

// ── The plugin difference ────────────────────────────────────────────────────────

type RuleMap = Record<string, unknown>;

/** Tailwind's plugin API, reduced to the three hooks silicaui actually calls. */
function runPlugin(colors: string[]): { base: RuleMap; utilities: RuleMap } {
  const base: RuleMap = {};
  const utilities: RuleMap = {};
  const { handler } = silicaPlugin({ colors });
  handler({
    addBase: (rules: RuleMap) => Object.assign(base, rules),
    addUtilities: (rules: RuleMap) => Object.assign(utilities, rules),
    // `warnUnregisteredColors` reads the Tailwind theme to flag a color declared in
    // `@theme` but left out of `colors:`. There is no `@theme` here — the tenant's
    // values arrive as a `<style>` block, not a Tailwind config — so an empty bag
    // is the honest answer and silences a warning that can't apply.
    theme: () => ({}),
  });
  return { base, utilities };
}

/**
 * The plugin output attributable to `colors`, and nothing else.
 *
 * A control run supplies a single throwaway semantic name so the *shape* of both
 * runs is identical (the plugin falls back to its full default list when `colors`
 * is empty, which would make the difference meaningless); every rule the real run
 * adds on top of that control is a `colors`-derived rule.
 */
function colorRules(colors: string[]): RuleMap {
  const control = runPlugin(['primary']);
  const actual = runPlugin(['primary', ...colors]);
  const out: RuleMap = {};
  for (const [selector, decls] of Object.entries(actual.base)) {
    if (!(selector in control.base)) out[selector] = decls;
  }
  // silicaui routes only the color-INDEPENDENT `soft`/`glass` families through
  // `addUtilities`, so this loop is empty today. It exists so a future color-aware
  // utility is carried rather than silently dropped.
  for (const [selector, decls] of Object.entries(actual.utilities)) {
    if (!(selector in control.utilities)) out[selector] = decls;
  }
  return out;
}

const kebab = (prop: string): string =>
  prop.startsWith('--') ? prop : prop.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);

function serialize(rules: RuleMap): string {
  return Object.entries(rules)
    .map(([selector, decls]) => {
      const body = Object.entries(decls as Record<string, string>)
        .map(([prop, value]) => `${kebab(prop)}:${value}`)
        .join(';');
      return `${selector}{${body}}`;
    })
    .join('');
}

/**
 * Memo keyed by the sorted role names. One entry per distinct custom palette, so a
 * storefront process holds one string per site it serves — and a site with no custom
 * color never reaches here (`buildCustomColorCss` returns early).
 */
const ruleCache = new Map<string, string>();

/**
 * The `@layer base` component + utility rules for a set of custom color names.
 *
 * ── NOW A THIN WRAPPER OVER silicaui, WHICH IS THE POINT ──────────────────────────
 *
 * This used to run the Tailwind plugin twice against a stub context — once with the
 * custom names and once without — and keep the difference (`colorRules` below, still
 * here as the FALLBACK). That recovered the full registration, and it worked, but it
 * leaned on two things silicaui publishes no types for: the shape `plugin.withOptions`
 * returns, and `addBase` being the only channel that matters. It was filed as
 * docs/silicaui/01 §19 the day it was written, for exactly that reason.
 *
 * silicaui 0.45.0 answered it: `customColorCss(theme, scope?)` from
 * `@wizeworks/silicaui-html/theme` is a real render-path entry point — no React, no
 * plugin internals — and it emits the whole registration (41 rules across 37 component
 * families, verified against 0.45.0) rather than the four this package could reach in
 * 0.41. So the supported call is what runs.
 *
 * THE DIFFING FALLBACK IS KEPT, not deleted, and it is not sentimentality. The two
 * disagree about one thing: which roles count as CUSTOM. This package decides against
 * `SPARX_REGISTERED_COLOR_ROLES` — the names actually registered in each app's
 * `globals.css`, which includes the eighteen module hues — while silicaui decides
 * against its own shipped set, and would therefore treat a module color as custom and
 * emit rules for a name the build already covers. Harmless (identical declarations,
 * later in the cascade) but wasteful, so the supported path is used when the two agree
 * on the role set and the local one when they do not.
 */
export function customColorRuleCss(roles: string[], theme?: Theme): string {
  if (roles.length === 0) return '';
  const key = roles.join(',');
  const hit = ruleCache.get(key);
  if (hit !== undefined) return hit;
  const css = theme ? fromSilica(theme, roles) : null;
  const out = css ?? wrapBase(serialize(colorRules(roles)));
  ruleCache.set(key, out);
  return out;
}

/** silicaui's own registration for this theme, when its notion of "custom" matches
 *  ours. `null` hands the caller back to the local diff rather than emitting rules for
 *  a role set nobody asked about. */
function fromSilica(theme: Theme, roles: string[]): string | null {
  const theirs = [...customRolesOf(theme)].sort();
  const ours = [...roles].sort();
  if (theirs.length !== ours.length || theirs.some((r, i) => r !== ours[i])) return null;
  // Unscoped on purpose: these stand in for colors a build-time registration would have
  // declared globally, and the published page is not a preview of anything.
  return wrapBase(customColorCss(theme));
}

function wrapBase(css: string): string {
  return css ? `@layer base{${css}}` : '';
}

// ── Derived `-content` foregrounds ───────────────────────────────────────────────

/**
 * The MEASURED foreground for each custom role that didn't get an authored one.
 *
 * `addColor` writes only `--color-<name>`, so the pair is normally absent. Two
 * things then read it, and only one of them copes: every component rule resolves
 * `var(--color-<name>-content, oklch(from … ))`, whose fallback is silicaui's
 * documented LAST RESORT — a lightness-threshold approximation it explicitly says
 * should never be reached by anything a build step could measure; while the
 * `.text-<name>-content` / `.bg-<name>-content` utilities reference the var with NO
 * fallback and simply produce nothing.
 *
 * silicaui-html's `resolveThemeTokens` is the real contrast engine (the same one the
 * canvas paints with, via `themeVars`), so deriving here both fixes the dead
 * utilities and upgrades every component from the approximation to the measured ink
 * — closing a canvas-vs-site divergence in the same pass.
 *
 * EVERY role, not only the invented ones. The semantic eight reach the same dead
 * `.text-primary-content` utility and the same last-resort approximation when a
 * theme leaves their pair unset, and a theme editor that reports one ink while the
 * page paints another is reporting nothing. An authored value still wins outright —
 * this only ever fills a gap, and says nothing where the theme has spoken.
 *
 * (This paragraph read "scoped deliberately to CUSTOM roles" while the caller was
 * already passing `rolesOf`, which is all of them. The prose was left behind by the
 * change, not the behaviour.)
 */
function contentVars(
  theme: Theme,
  roles: string[],
  mode: 'light' | 'dark'
): Record<string, string> {
  const resolved = resolveThemeTokens(theme, mode);
  // What the theme's OWN stylesheet already puts in force for this mode, which is
  // the only thing worth comparing against — this block is emitted after it and
  // at the same specificity, so a var it repeats verbatim is dead weight and a
  // var it omits leaves whatever was there.
  const inForce = mode === 'dark' ? { ...theme.tokens, ...theme.dark } : theme.tokens;
  const out: Record<string, string> = {};
  for (const role of roles) {
    const key = `--color-${role}-content`;
    const value = resolved[key];
    // Compared, never merely tested for presence. `if (authored[key]) continue`
    // read the merged map, so a theme that authored its ink in LIGHT and only
    // re-pointed the color in DARK — the ordinary shape, because the ink usually
    // needs no thought — was treated as having authored the dark ink too, and no
    // override was emitted. `resolveThemeTokens` had already re-derived it (a
    // light ink is stale the moment the dark bag moves the color under it); we
    // threw that answer away and painted the light ink on the dark fill. Measured
    // on a #1d4ed8 → #bfdbfe primary: 1.42:1 where silica resolves 13.84:1.
    if (!value || inForce[key] === value) continue;
    out[key] = value;
  }
  return out;
}

/** `--color-x:val;` pairs, dropping any value that could terminate the block. */
function declBlock(vars: Record<string, string>): string {
  return Object.entries(vars)
    .filter(([, value]) => !/[;{}<]/.test(value))
    .map(([key, value]) => `${key}:${value};`)
    .join('');
}

export interface BuildCustomColorCssOptions {
  /** Selector the derived `-content` tokens are declared on. Default `:root`. */
  rootSelector?: string;
  /** Roles the consuming app's bundle already covers, so nothing is generated for
   *  them. Default `SPARX_REGISTERED_COLOR_ROLES`. */
  registered?: readonly string[];
}

/**
 * The complete per-tenant custom-color stylesheet: the derived `-content` tokens,
 * then the component + utility rules that consume them.
 *
 * Injected AFTER the theme's own token block (which declares `--color-<name>`
 * itself) and reading only from it, so the two compose the way a build-time
 * registration would. Returns `''` for a theme with no custom color — the common
 * case, and the only cost is one `rolesOf` pass.
 *
 * Selectors mirror `buildSilicaThemeCssFromTheme`'s exactly (`:root`,
 * `:root[data-theme="dark"]`, and the `prefers-color-scheme` companion that honors
 * an explicit light opt-out) so a custom color tracks the theme through a dark-mode
 * toggle just like a semantic one.
 */
export function buildCustomColorCss(theme: Theme, opts: BuildCustomColorCssOptions = {}): string {
  const roles = customColorRoles(theme, opts.registered);
  if (roles.length === 0) return '';

  const root = opts.rootSelector ?? ':root';
  const out: string[] = [];

  const lightVars = contentVars(theme, roles, 'light');
  const light = declBlock(lightVars);
  if (light) out.push(`${root}{${light}}`);

  if (theme.dark && Object.keys(theme.dark).length > 0) {
    // Only the roles whose ink actually MOVES in dark mode. A custom color the
    // author didn't restate in the dark map keeps its light value, so its derived
    // foreground is identical — and repeating it would cost three copies (the
    // attribute block, the media block, and the light one) for no change.
    const darkVars = Object.fromEntries(
      Object.entries(contentVars(theme, roles, 'dark')).filter(([k, v]) => lightVars[k] !== v)
    );
    const dark = declBlock(darkVars);
    if (dark) {
      out.push(`${root}[data-theme="dark"]{${dark}}`);
      out.push(`@media (prefers-color-scheme:dark){${root}:not([data-theme="light"]){${dark}}}`);
    }
  }

  out.push(customColorRuleCss(roles, theme));
  return out.join('');
}

/**
 * The MEASURED foreground for EVERY role a theme leaves unset — the semantic ones
 * as well as the custom ones.
 *
 * Without this, silicaui's CSS resolves `var(--color-<role>-content, oklch(from …))`
 * through its documented LAST RESORT: a lightness-threshold approximation. On a
 * mid-tone brand color the approximation and the measurement disagree — a theme
 * editor that reports the measured ink ("we would put near-black on this orange")
 * while the page paints the approximated one (white) is describing a site that
 * does not exist.
 *
 * Emitted as tokens rather than baked into the stored `Theme` on purpose: a stored
 * pair goes stale the moment the author edits the role color, and nothing in the
 * schema records whether it was authored or derived. An AUTHORED `-content` always
 * wins — this only fills gaps.
 */
export function buildDerivedContentCss(theme: Theme, opts: { rootSelector?: string } = {}): string {
  const roles = rolesOf(theme);
  if (roles.length === 0) return '';

  const root = opts.rootSelector ?? ':root';
  const out: string[] = [];

  const lightVars = contentVars(theme, roles, 'light');
  const light = declBlock(lightVars);
  if (light) out.push(`${root}{${light}}`);

  if (theme.dark && Object.keys(theme.dark).length > 0) {
    // Only the inks that actually MOVE in dark mode; a role the author did not
    // restate keeps its light value and its derivation is identical.
    const darkVars = Object.fromEntries(
      Object.entries(contentVars(theme, roles, 'dark')).filter(([k, v]) => lightVars[k] !== v)
    );
    const dark = declBlock(darkVars);
    if (dark) {
      out.push(`${root}[data-theme="dark"]{${dark}}`);
      out.push(`@media (prefers-color-scheme:dark){${root}:not([data-theme="light"]){${dark}}}`);
    }
  }

  return out.join('');
}
