// Linen — a sparx first-party marketplace theme (docs/85). The payload is a
// complete DataThemePreset (v1 storefront tokens + v2 preset); the ingest
// validates it and writes it to storage as the applied-at-runtime artifact.
export default {
  v: 1,
  v1: {
    light: {
      colorPrimary: '#44403c',
      colorPrimaryForeground: '#faf8f5',
      colorAccent: '#a8755a',
      colorBackground: '#faf8f4',
      colorForeground: '#292524',
      colorMuted: '#f1ede6',
      colorBorder: '#e4ddd2',
      fontHeading: 'Libre Baskerville',
      fontBody: 'Inter',
      radiusBase: '0.25rem',
      containerWidth: 'wide',
    },
    dark: {
      colorPrimary: '#e7e2da',
      colorPrimaryForeground: '#1c1a17',
      colorAccent: '#c18f73',
      colorBackground: '#161412',
      colorForeground: '#ece7df',
      colorMuted: '#201d18',
      colorBorder: '#322d25',
      fontHeading: 'Libre Baskerville',
      fontBody: 'Inter',
      radiusBase: '0.25rem',
      containerWidth: 'wide',
    },
  },
  v2: {
    shared: {
      fontHeading: 'Libre Baskerville',
      fontBody: 'Inter',
      radiusSelector: '0.25rem',
      radiusField: '0.25rem',
      radiusBox: '0.25rem',
      borderWidth: '1px',
      spaceBase: '0.28rem',
      sizeField: '2.875rem',
      sizeSelector: '2.125rem',
      depth: 0.4,
      containerWidth: 'wide',
    },
    light: {
      base100: '#faf8f4',
      base200: '#ffffff',
      base300: '#f1ede6',
      baseContent: '#292524',
      primary: '#44403c',
      primaryContent: '#faf8f5',
      secondary: '#78716c',
      accent: '#a8755a',
      neutral: '#292524',
      border: '#e4ddd2',
      info: '#0284c7',
      success: '#16a34a',
      warning: '#d97706',
      danger: '#dc2626',
    },
    dark: {
      base100: '#161412',
      base200: '#201d18',
      base300: '#2a261f',
      baseContent: '#ece7df',
      primary: '#e7e2da',
      primaryContent: '#1c1a17',
      secondary: '#a8a29e',
      accent: '#c18f73',
      neutral: '#ece7df',
      border: '#322d25',
      info: '#38bdf8',
      success: '#4ade80',
      warning: '#fbbf24',
      danger: '#f87171',
    },
  },
};
