// sparx — Writer Portfolio: a personal-portfolio SITE TEMPLATE, composed distinct — its own home,
// a live work index, a bespoke case-study page, about + contact — dressed in the bespoke
// theme its persona pins.
//
// GENERATED by marketplace-catalog/_gen/gen-portfolio-writer.ts via the
// shared _gen/portfolio-sites/harness.ts — do NOT hand-edit; edit the generator and
// regenerate. A blueprint is PURE DATA: the loader `import()`s this module with no
// workspace resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import content from './content.json' with { type: 'json' };
import authors from './authors.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };
import emails from './emails.json' with { type: 'json' };

const blueprint = {
  key: 'sparx-portfolio-writer',
  version: '1.1.0',
  name: 'sparx — Writer Portfolio',
  summary:
    'A read-me portfolio for a working writer: a type-only editorial masthead, selected writing as a hairline-ruled index (not cards), reading pages that give an essay room, and a plain about + contact. The words are the work — warm-paper page, serif across, one oxblood on rubrics and links. Shipped as Iris Bellamy.',
  vertical: 'content',
  preview: 'media/preview.png',
  requiresModules: ['builder', 'cms', 'email'],

  // Identity only (person's name + tagline + fonts + the theme's hex colours). The look
  // itself rides site.theme + the theme decl below; the installing tenant rebrands the name.
  brand: {
    businessName: 'Iris Bellamy',
    tagline: 'Essays and reporting on work, cities, and attention.',
    colors: {
      primary: '#8f3222',
      primaryForeground: '#fff6f4',
      accent: '#8f3222',
      secondary: '#5a493d',
    },
    fonts: {
      heading: 'Fraunces',
      body: 'Spectral',
    },
  },

  // The provisioned SiteTheme the installer creates + applies — the bespoke portfolio look
  // as a tenant-editable saved theme (base preset = the template's own theme key, plus its
  // brand snapshot).
  theme: {
    name: 'portfolio-writer',
    basePresetKey: 'portfolio-writer',
    presentation: {
      v: 2,
      containerWidth: '1152px',
    },
    brand: {
      colorPrimary: '#8f3222',
      colorAccent: '#8f3222',
      colorSecondary: '#5a493d',
      fontHeading: 'Fraunces',
      fontBody: 'Spectral',
      tokens: {},
    },
    apply: true,
  },

  assets,
  contentTypes: [],
  authors,
  content,

  // A portfolio has no commerce. The projects are CMS `blog_post` records (see content).
  emails,
  sequences: [],

  // The composed distinct site (frame + home + a live /work index + about/contact + the
  // /blog/:slug case-study template), in the bespoke theme, fully stamped.
  site,
};

export default blueprint;
