// Sage — a Sparx first-party marketplace theme (docs/85). The payload is a
// complete DataThemePreset (v1 storefront tokens + v2 preset); the ingest
// validates it and writes it to storage as the applied-at-runtime artifact.
export default {
  v: 1,
  v1: {
    light: {
      colorPrimary: '#4d7c5a',
      colorPrimaryForeground: '#ffffff',
      colorAccent: '#a3b18a',
      colorBackground: '#fbfcfa',
      colorForeground: '#1f2a22',
      colorMuted: '#eef2ea',
      colorBorder: '#dce5d5',
      fontHeading: 'Fraunces',
      fontBody: 'Nunito Sans',
      radiusBase: '0.75rem',
      containerWidth: 'medium',
    },
    dark: {
      colorPrimary: '#6fa67e',
      colorPrimaryForeground: '#0e1611',
      colorAccent: '#b6c49c',
      colorBackground: '#0e1611',
      colorForeground: '#e7ede3',
      colorMuted: '#16211a',
      colorBorder: '#233127',
      fontHeading: 'Fraunces',
      fontBody: 'Nunito Sans',
      radiusBase: '0.75rem',
      containerWidth: 'medium',
    },
  },
  v2: {
    shared: {
      fontHeading: 'Fraunces',
      fontBody: 'Nunito Sans',
      radiusSelector: '9999px',
      radiusField: '0.5rem',
      radiusBox: '0.75rem',
      borderWidth: '1px',
      spaceBase: '0.26rem',
      sizeField: '2.75rem',
      sizeSelector: '2rem',
      depth: 0.9,
      containerWidth: 'medium',
    },
    light: {
      base100: '#fbfcfa',
      base200: '#ffffff',
      base300: '#eef2ea',
      baseContent: '#1f2a22',
      primary: '#4d7c5a',
      primaryContent: '#ffffff',
      secondary: '#7a8b6f',
      accent: '#a3b18a',
      neutral: '#1f2a22',
      border: '#dce5d5',
      info: '#0284c7',
      success: '#16a34a',
      warning: '#d97706',
      danger: '#dc2626',
    },
    dark: {
      base100: '#0e1611',
      base200: '#141f18',
      base300: '#1c2a21',
      baseContent: '#e7ede3',
      primary: '#6fa67e',
      primaryContent: '#0e1611',
      secondary: '#8ba07d',
      accent: '#b6c49c',
      neutral: '#e7ede3',
      border: '#233127',
      info: '#38bdf8',
      success: '#4ade80',
      warning: '#fbbf24',
      danger: '#f87171',
    },
  },
};
