// sparx marketplace component — 'In numbers' (Page structure). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-200 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 gap-6 @2xl:grid-cols-2 @4xl:grid-cols-3',
            children: [
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3 rounded-box border border-base-300 bg-base-100 p-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-4xl font-semibold text-base-content',
                    children: ['26'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-lg font-semibold text-base-content',
                    children: ['kitchens last year'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: ['Every one finished on the date we first gave.'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3 rounded-box border border-base-300 bg-base-100 p-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-4xl font-semibold text-base-content',
                    children: ['4 weeks'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-lg font-semibold text-base-content',
                    children: ['typical lead time'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: ['Because we dry our own timber rather than waiting on a supplier.'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3 rounded-box border border-base-300 bg-base-100 p-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-4xl font-semibold text-base-content',
                    children: ['10 years'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-lg font-semibold text-base-content',
                    children: ['guarantee'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: [
                      'On anything made in our workshop. Two claims so far, both fixed free.',
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
