// Public media variants — serves the world-readable derivative renditions
// generated by media-worker.
//
//   GET /v1/public/media/variants/:tenantId/:assetId/:filename
//     where :filename = `${format}-${width}.${ext}` (e.g. `webp-800.webp`)
//
// Why this exists: the org enforces iam.allowedPolicyMemberDomains, which
// forbids granting allUsers:objectViewer on any GCS bucket. So variants
// live in a private bucket and api-rest reads them with the app SA + pipes
// the bytes back to the client with long-cache headers. Cloudflare in front
// of api.sparx.works absorbs all repeat traffic at the edge; api-rest only
// sees first-miss requests per (variant, edge POP).
//
// No auth required. The key shape is deterministic (tenantId + assetId +
// format/width), so enumerating across tenants buys you nothing — without
// the assetId you can't construct a hit, and assetIds are UUIDs we issued.

import type { FastifyPluginAsync } from 'fastify';
import { z } from 'zod';
import { prisma, withTenant } from '@sparx/db';
import { getStorage, variantKey } from '../../../lib/storage.js';
import { notFound } from '@sparx/api-core/errors';
import { env } from '../../../env.js';

// Filename pattern matches what variantKey() emits in storage.ts:
//   `${format}-${width}.${ext}` → e.g. webp-800.webp, avif-1200.avif, jpeg-400.jpg
const FILENAME_RE = /^([a-z]+)-(\d+)\.([a-z0-9]+)$/;

const PathParams = z.object({
  tenantId: z.string().uuid(),
  assetId: z.string().uuid(),
  filename: z.string().regex(FILENAME_RE),
});

// Content-type sniff from the variant filename extension. We trust the
// extension because the worker is the only writer and writes deterministic
// names; the bucket-level GCS metadata is also set, but reading it would
// cost a second round-trip.
const CONTENT_TYPES: Record<string, string> = {
  avif: 'image/avif',
  webp: 'image/webp',
  jpeg: 'image/jpeg',
  jpg: 'image/jpeg',
  png: 'image/png',
};

// Resolve a media asset id → its public URL and 302 there. This is the resolver
// the storefront <img>/<Image> and email templates point at
// (GET /v1/public/media/<id>?tenant=<slug>, see apps/site/lib/media.ts +
// services/api-rest/src/lib/email-data.ts). mediaPublicUrl() returns the CDN/
// bucket URL for stored objects and passes HOT-LINKED external keys through
// verbatim (blueprint installs, docs/54 §6) — so this is the one path that makes
// both kinds of media render. Tenant resolved by slug (tenants is non-RLS), then
// an RLS-scoped asset lookup so an id can't leak another tenant's media.
const RedirectQuery = z.object({ tenant: z.string().min(1).max(63) });
const RedirectParams = z.object({ id: z.string().uuid() });

const publicMediaRoutes: FastifyPluginAsync = (app) => {
  app.get('/v1/public/media/:id', async (request, reply) => {
    const { id } = RedirectParams.parse(request.params);
    const { tenant: slug } = RedirectQuery.parse(request.query);
    const tenant = await prisma.tenant.findUnique({ where: { slug }, select: { id: true } });
    if (!tenant) throw notFound('Tenant', slug);
    const asset = await withTenant({ tenantId: tenant.id }, (tx) =>
      tx.mediaAsset.findFirst({ where: { id }, select: { key: true } })
    );
    if (!asset?.key) throw notFound('MediaAsset', id);
    // Inline `data:` asset (a blueprint shipping a self-contained image — e.g. an SVG
    // product placeholder or logo): a 302 can't target a data URI, so SERVE the bytes
    // here with their declared content-type instead of redirecting. Reusable by any
    // blueprint that wants reliable, network-free imagery.
    if (asset.key.startsWith('data:')) {
      const comma = asset.key.indexOf(',');
      const meta = comma >= 0 ? asset.key.slice(5, comma) : '';
      const isB64 = /;base64$/i.test(meta);
      const mime = meta.replace(/;base64$/i, '') || 'application/octet-stream';
      const raw = comma >= 0 ? asset.key.slice(comma + 1) : '';
      const body = isB64
        ? Buffer.from(raw, 'base64')
        : Buffer.from(decodeURIComponent(raw), 'utf8');
      return reply
        .header('content-type', mime)
        .header('cache-control', 'public, max-age=86400')
        .send(body);
    }
    // Resolve the redirect target for the asset's stored key:
    //   · external hot-linked URL (blueprint installs) → pass through verbatim.
    //   · local-dev (no GCS) → the original bytes are served by api-rest's own
    //     /v1/public/media/file/* route via LocalStorage.publicUrl().
    //   · GCS mode → a transcoded PUBLIC variant, served by the variant route
    //     below (api-rest pipes the bytes; the org forbids allUsers on the
    //     bucket, so a direct storage.googleapis.com URL 403s).
    const storage = getStorage();

    if (/^https?:\/\//i.test(asset.key)) {
      return reply.header('cache-control', 'public, max-age=86400').redirect(asset.key, 302);
    }
    if (storage.mode === 'local') {
      return reply
        .header('cache-control', 'public, max-age=86400')
        .redirect(storage.publicUrl(asset.key), 302);
    }

    // GCS: redirect to the best transcoded variant. Never mediaPublicUrl(originalsKey)
    // — that mints a direct storage.googleapis.com URL that is (a) allUsers-blocked
    // and (b) an /originals/ path in the PUBLIC bucket (originals live in the PRIVATE
    // bucket), so it 403s. The variant route (below) serves the bytes instead.
    const variants = await withTenant({ tenantId: tenant.id }, (tx) =>
      tx.mediaVariant.findMany({
        where: { assetId: id },
        select: { format: true, width: true, key: true },
      })
    );
    if (variants.length > 0) {
      // Prefer webp (universal support + strong compression); widest available.
      const webp = variants.filter((v) => v.format === 'webp');
      const pool = webp.length > 0 ? webp : variants;
      const best = pool.reduce((a, b) => (b.width > a.width ? b : a));
      // Stored key is `<tenantId>/variants/<assetId>/<filename>`; the route is
      // /v1/public/media/variants/:tenantId/:assetId/:filename — drop the middle
      // `/variants/` segment so the 3-param route matches.
      const path = best.key.replace('/variants/', '/');
      return reply
        .header('cache-control', 'public, max-age=86400')
        .redirect(`${env.MEDIA_PUBLIC_URL}/v1/public/media/variants/${path}`, 302);
    }
    // No variants yet (still transcoding) or a non-raster original the worker
    // serves as-is (SVG): sign a short-lived read of the ORIGINAL so the image
    // still displays instead of 403ing. Short cache so it flips to the variant
    // once transcoding completes.
    const signed = await storage.presignGet(asset.key);
    return reply.header('cache-control', 'public, max-age=300').redirect(signed, 302);
  });

  app.get<{ Params: z.infer<typeof PathParams> }>(
    '/v1/public/media/variants/:tenantId/:assetId/:filename',
    async (request, reply) => {
      const params = PathParams.parse(request.params);
      // PathParams.regex already validated the filename matches FILENAME_RE,
      // so the re-exec cannot return null. Re-execing is just to destructure.
      const match = FILENAME_RE.exec(params.filename)!;
      const [, format, widthStr, ext] = match;

      const key = variantKey(params.tenantId, params.assetId, format!, Number(widthStr), ext!);

      let obj;
      try {
        obj = await getStorage().readObject(key);
      } catch {
        // GCS returns 404 by surfacing an ENOENT-shaped error inside the
        // node SDK. Anything else (auth, network) bubbles up to the
        // generic error handler as 500.
        throw notFound('MediaVariant', `${params.assetId}/${params.filename}`);
      }

      // Long-cache aggressively — variant content for a given key is
      // immutable (the worker re-encodes to a new key on re-process).
      // Cloudflare honours these headers; first edge miss hits api-rest,
      // every subsequent request is served from CF cache.
      reply
        .header('cache-control', 'public, max-age=31536000, immutable')
        .header(
          'content-type',
          CONTENT_TYPES[ext!] ?? obj.contentType ?? 'application/octet-stream'
        );
      if (obj.size !== null) reply.header('content-length', String(obj.size));

      return reply.send(obj.body);
    }
  );

  return Promise.resolve();
};

export default publicMediaRoutes;
