// sparx marketplace component — 'Article header' (Writing). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-3xl flex-col gap-8',
        children: [
          {
            kind: 'element',
            tag: 'h1',
            class: 'text-4xl font-semibold leading-tight text-base-content @3xl:text-5xl',
            children: ['Why we stopped buying kiln-dried timber'],
          },
          {
            kind: 'element',
            tag: 'p',
            class: 'text-xl text-base-content',
            children: [
              'It cost more, arrived wetter than the label said, and moved after we had fitted it. So we built a drying shed and learned to do it ourselves.',
            ],
          },
          {
            kind: 'element',
            tag: 'p',
            class: 'text-base text-base-content',
            children: ['Ada Mercer · 18 July 2026 · 6 minute read'],
          },
          {
            kind: 'element',
            tag: 'img',
            class:
              'aspect-video w-full rounded-box border border-base-300 bg-base-200 object-cover',
            attrs: {
              src: '',
              alt: 'The drying shed at Mill Lane',
              loading: 'lazy',
            },
          },
        ],
      },
    ],
  },
} as const;
