// sparx marketplace component — 'Menu' (Where & when). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-200 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-col gap-3',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                children: ['Today’s menu'],
              },
              {
                kind: 'element',
                tag: 'p',
                class: 'max-w-2xl text-lg text-base-content',
                children: ['Written every morning. If it is on here, we have it.'],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 gap-10 @3xl:grid-cols-2',
            children: [
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-2',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-2xl font-semibold text-base-content',
                    children: ['To start'],
                  },
                  {
                    kind: 'element',
                    tag: 'ul',
                    class: 'flex flex-col',
                    children: [
                      {
                        kind: 'element',
                        tag: 'li',
                        class:
                          'flex items-baseline justify-between gap-6 border-t border-base-300 py-4',
                        children: [
                          {
                            kind: 'element',
                            tag: 'div',
                            class: 'flex flex-col gap-1',
                            children: [
                              {
                                kind: 'element',
                                tag: 'p',
                                class: 'text-base font-semibold text-base-content',
                                children: ['Soda bread and cultured butter'],
                              },
                              {
                                kind: 'element',
                                tag: 'p',
                                class: 'text-base text-base-content',
                                children: ['Baked at six this morning'],
                              },
                            ],
                          },
                          {
                            kind: 'element',
                            tag: 'p',
                            class: 'text-base font-semibold text-base-content',
                            children: ['$5'],
                          },
                        ],
                      },
                      {
                        kind: 'element',
                        tag: 'li',
                        class:
                          'flex items-baseline justify-between gap-6 border-t border-base-300 py-4',
                        children: [
                          {
                            kind: 'element',
                            tag: 'div',
                            class: 'flex flex-col gap-1',
                            children: [
                              {
                                kind: 'element',
                                tag: 'p',
                                class: 'text-base font-semibold text-base-content',
                                children: ['Smoked mackerel'],
                              },
                              {
                                kind: 'element',
                                tag: 'p',
                                class: 'text-base text-base-content',
                                children: ['Beetroot, horseradish, dill'],
                              },
                            ],
                          },
                          {
                            kind: 'element',
                            tag: 'p',
                            class: 'text-base font-semibold text-base-content',
                            children: ['$9'],
                          },
                        ],
                      },
                      {
                        kind: 'element',
                        tag: 'li',
                        class:
                          'flex items-baseline justify-between gap-6 border-t border-base-300 py-4',
                        children: [
                          {
                            kind: 'element',
                            tag: 'div',
                            class: 'flex flex-col gap-1',
                            children: [
                              {
                                kind: 'element',
                                tag: 'p',
                                class: 'text-base font-semibold text-base-content',
                                children: ['Roast squash'],
                              },
                              {
                                kind: 'element',
                                tag: 'p',
                                class: 'text-base text-base-content',
                                children: ['Sage, hazelnut, aged cheese'],
                              },
                            ],
                          },
                          {
                            kind: 'element',
                            tag: 'p',
                            class: 'text-base font-semibold text-base-content',
                            children: ['$8'],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-2',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-2xl font-semibold text-base-content',
                    children: ['Mains'],
                  },
                  {
                    kind: 'element',
                    tag: 'ul',
                    class: 'flex flex-col',
                    children: [
                      {
                        kind: 'element',
                        tag: 'li',
                        class:
                          'flex items-baseline justify-between gap-6 border-t border-base-300 py-4',
                        children: [
                          {
                            kind: 'element',
                            tag: 'div',
                            class: 'flex flex-col gap-1',
                            children: [
                              {
                                kind: 'element',
                                tag: 'p',
                                class: 'text-base font-semibold text-base-content',
                                children: ['Braised shin of beef'],
                              },
                              {
                                kind: 'element',
                                tag: 'p',
                                class: 'text-base text-base-content',
                                children: ['Mash, greens, red wine'],
                              },
                            ],
                          },
                          {
                            kind: 'element',
                            tag: 'p',
                            class: 'text-base font-semibold text-base-content',
                            children: ['$22'],
                          },
                        ],
                      },
                      {
                        kind: 'element',
                        tag: 'li',
                        class:
                          'flex items-baseline justify-between gap-6 border-t border-base-300 py-4',
                        children: [
                          {
                            kind: 'element',
                            tag: 'div',
                            class: 'flex flex-col gap-1',
                            children: [
                              {
                                kind: 'element',
                                tag: 'p',
                                class: 'text-base font-semibold text-base-content',
                                children: ['Whole plaice'],
                              },
                              {
                                kind: 'element',
                                tag: 'p',
                                class: 'text-base text-base-content',
                                children: ['Brown butter, capers, new potatoes'],
                              },
                            ],
                          },
                          {
                            kind: 'element',
                            tag: 'p',
                            class: 'text-base font-semibold text-base-content',
                            children: ['$24'],
                          },
                        ],
                      },
                      {
                        kind: 'element',
                        tag: 'li',
                        class:
                          'flex items-baseline justify-between gap-6 border-t border-base-300 py-4',
                        children: [
                          {
                            kind: 'element',
                            tag: 'div',
                            class: 'flex flex-col gap-1',
                            children: [
                              {
                                kind: 'element',
                                tag: 'p',
                                class: 'text-base font-semibold text-base-content',
                                children: ['Barley and root vegetables'],
                              },
                              {
                                kind: 'element',
                                tag: 'p',
                                class: 'text-base text-base-content',
                                children: ['Slow-cooked, herb oil'],
                              },
                            ],
                          },
                          {
                            kind: 'element',
                            tag: 'p',
                            class: 'text-base font-semibold text-base-content',
                            children: ['$17'],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'p',
            class: 'text-sm text-base-content',
            children: ['Please tell us about any allergies — everything is cooked to order.'],
          },
        ],
      },
    ],
  },
} as const;
