// sparx marketplace component — 'What's included' (Comparison). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-200 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-col gap-3',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                children: ["What's included"],
              },
              {
                kind: 'element',
                tag: 'p',
                class: 'max-w-2xl text-lg text-base-content',
                children: ['Everything below is part of the price. Nothing is an extra.'],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'ul',
            class: 'flex flex-col',
            children: [
              {
                kind: 'element',
                tag: 'li',
                class: 'flex items-start gap-3 border-t border-base-300 py-4',
                children: [
                  {
                    kind: 'element',
                    tag: 'span',
                    class: 'text-base-content',
                    children: ['✓'],
                  },
                  {
                    kind: 'element',
                    tag: 'span',
                    class: 'text-base text-base-content',
                    children: ['A visit to measure up, at a time that suits you'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'li',
                class: 'flex items-start gap-3 border-t border-base-300 py-4',
                children: [
                  {
                    kind: 'element',
                    tag: 'span',
                    class: 'text-base-content',
                    children: ['✓'],
                  },
                  {
                    kind: 'element',
                    tag: 'span',
                    class: 'text-base text-base-content',
                    children: ['A written quote with every line itemised'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'li',
                class: 'flex items-start gap-3 border-t border-base-300 py-4',
                children: [
                  {
                    kind: 'element',
                    tag: 'span',
                    class: 'text-base-content',
                    children: ['✓'],
                  },
                  {
                    kind: 'element',
                    tag: 'span',
                    class: 'text-base text-base-content',
                    children: ['All materials, delivered to site'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'li',
                class: 'flex items-start gap-3 border-t border-base-300 py-4',
                children: [
                  {
                    kind: 'element',
                    tag: 'span',
                    class: 'text-base-content',
                    children: ['✓'],
                  },
                  {
                    kind: 'element',
                    tag: 'span',
                    class: 'text-base text-base-content',
                    children: ['Fitting by the same people who made it'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'li',
                class: 'flex items-start gap-3 border-t border-base-300 py-4',
                children: [
                  {
                    kind: 'element',
                    tag: 'span',
                    class: 'text-base-content',
                    children: ['✓'],
                  },
                  {
                    kind: 'element',
                    tag: 'span',
                    class: 'text-base text-base-content',
                    children: ['Removal and disposal of the old fittings'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'li',
                class: 'flex items-start gap-3 border-t border-base-300 py-4',
                children: [
                  {
                    kind: 'element',
                    tag: 'span',
                    class: 'text-base-content',
                    children: ['✓'],
                  },
                  {
                    kind: 'element',
                    tag: 'span',
                    class: 'text-base text-base-content',
                    children: ['A tidy site at the end of every day'],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
