// sparx marketplace component — 'Two options' (Comparison). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-200 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-col gap-3',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                children: ['Two ways to work with us'],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 gap-6 @2xl:grid-cols-2',
            children: [
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3 rounded-box border border-base-300 bg-base-100 p-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['By the hour'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-3xl font-semibold text-base-content',
                    children: ['$65 / hour'],
                  },
                  {
                    kind: 'element',
                    tag: 'ul',
                    class: 'flex flex-col gap-2',
                    children: [
                      {
                        kind: 'element',
                        tag: 'li',
                        class: 'text-base text-base-content',
                        children: ['✓  No minimum booking'],
                      },
                      {
                        kind: 'element',
                        tag: 'li',
                        class: 'text-base text-base-content',
                        children: ['✓  Pay only for time on site'],
                      },
                      {
                        kind: 'element',
                        tag: 'li',
                        class: 'text-base text-base-content',
                        children: ['✓  Materials billed at cost'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'div',
                    class: 'flex flex-wrap items-center gap-3',
                    children: [
                      {
                        kind: 'element',
                        tag: 'a',
                        class: 'btn btn-neutral btn-outline btn-lg',
                        attrs: {
                          href: '#',
                        },
                        children: ['Book an hour'],
                      },
                    ],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3 rounded-box border border-base-300 bg-base-100 p-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['Fixed price'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-3xl font-semibold text-base-content',
                    children: ['Quoted per job'],
                  },
                  {
                    kind: 'element',
                    tag: 'ul',
                    class: 'flex flex-col gap-2',
                    children: [
                      {
                        kind: 'element',
                        tag: 'li',
                        class: 'text-base text-base-content',
                        children: ['✓  Price agreed before we start'],
                      },
                      {
                        kind: 'element',
                        tag: 'li',
                        class: 'text-base text-base-content',
                        children: ['✓  No surprises on the invoice'],
                      },
                      {
                        kind: 'element',
                        tag: 'li',
                        class: 'text-base text-base-content',
                        children: ['✓  Includes materials'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'div',
                    class: 'flex flex-wrap items-center gap-3',
                    children: [
                      {
                        kind: 'element',
                        tag: 'a',
                        class: 'btn btn-primary btn-lg',
                        attrs: {
                          href: '#',
                        },
                        children: ['Get a quote'],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
