// sparx — Restaurant Equipment (B2B / Wholesale): a reference-driven SITE TEMPLATE (docs/templates/*),
// composed distinct — its own home section sequence, example commerce, and journal —
// and dressed in the bespoke theme its DESIGN.md pins.
//
// GENERATED by marketplace-catalog/_gen/gen-template-b2b-restaurant-equipment.ts
// via the shared _gen/template-sites/harness.ts — do NOT hand-edit; edit the generator
// and regenerate. A blueprint is PURE DATA: the loader `import()`s this module with no
// workspace resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import content from './content.json' with { type: 'json' };
import authors from './authors.json' with { type: 'json' };
import commerce from './commerce.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };
import emails from './emails.json' with { type: 'json' };

const blueprint = {
  key: 'sparx-b2b-restaurant-equipment',
  version: '1.3.0',
  name: 'sparx — Restaurant Equipment (B2B / Wholesale)',
  summary:
    'A complete, working wholesale shop for a commercial kitchen & restaurant-equipment distributor: a real trade catalogue sold by the unit and the case — prep tables, cooking gear, food storage, front-of-house service and smallwares — with categories, collections, a bespoke trade PDP (per-unit/per-case pricing, volume breaks, net-30), and a full merchandised home page. Kitchen-grade theme — warm steel ground, deep graphite, an ember copper accent. Shipped as Pass Supply Co.',
  vertical: 'b2b',
  preview: 'media/preview.png',
  requiresModules: ['builder', 'commerce', 'cms', 'crm', 'email'],

  // Identity only (business name + tagline + fonts + the theme's hex colours). The look
  // itself rides site.theme + the theme decl below; the installing tenant rebrands the name.
  brand: {
    businessName: 'Pass Supply Co.',
    tagline: 'Kit out the line. Keep it running.',
    colors: {
      primary: '#4a3d33',
      primaryForeground: '#fef7f2',
      accent: '#a74a04',
      secondary: '#5a4d42',
    },
    fonts: {
      heading: 'Space Grotesk',
      body: 'Inter',
    },
  },

  // The provisioned SiteTheme the installer creates + applies — the bespoke template
  // look as a tenant-editable saved theme (base preset = the template's own theme key,
  // plus its brand snapshot).
  theme: {
    name: 'b2b-restaurant-equipment',
    basePresetKey: 'b2b-restaurant-equipment',
    presentation: {
      v: 2,
      containerWidth: '1152px',
    },
    brand: {
      colorPrimary: '#4a3d33',
      colorAccent: '#a74a04',
      colorSecondary: '#5a4d42',
      fontHeading: 'Space Grotesk',
      fontBody: 'Inter',
      tokens: {},
    },
    apply: true,
  },

  assets,
  contentTypes: [],
  authors,
  content,
  commerce,

  // A shop's brand-voiced MARKETING starters (a welcome + a win-back), tokenized so a fork
  // re-themes to the tenant and installed as DRAFTS — the platform's keyed transactional
  // defaults (order/shipping/dunning) are separate and never duplicated here. Content
  // templates ship an empty set.
  emails,
  sequences: [],

  // The composed distinct site (frame + a template-specific home + standard commerce/
  // cms/about/contact pages + the /journal index), in the bespoke theme, fully stamped.
  site,
};

export default blueprint;
