// sparx marketplace component — 'Where to next' (Page structure). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-col gap-3',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                children: ['Where to next'],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 gap-6 @2xl:grid-cols-2 @4xl:grid-cols-3',
            children: [
              {
                kind: 'element',
                tag: 'a',
                class:
                  'flex flex-col gap-2 rounded-box border border-base-300 bg-base-100 p-6 hover:border-primary',
                attrs: {
                  href: '#',
                },
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['See our work'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: ['Photographs of everything we finished this year.'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'a',
                class:
                  'flex flex-col gap-2 rounded-box border border-base-300 bg-base-100 p-6 hover:border-primary',
                attrs: {
                  href: '#',
                },
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['What we charge'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: ['Fixed prices, published, including fitting.'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'a',
                class:
                  'flex flex-col gap-2 rounded-box border border-base-300 bg-base-100 p-6 hover:border-primary',
                attrs: {
                  href: '#',
                },
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['Talk to us'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: ['A call, a message, or a visit — whichever suits.'],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
