import { Card, CardBody, Progress } from '@wizeworks/silicaui-react';
import type { CapacityReport, MeterReading } from '@wizeworks/usage';
import { METER_LABEL, meterHeadline, meterNote, meterTone } from '@/lib/capacity-copy';

// What this business is using, against what its plan includes.
//
// Get Piggles owns the full picture; the console carries only the one meter that
// is in somebody's way. Nothing here shows a price — expansion is a separate
// decision on a separate screen.

/** Absolute UTC-safe day, so "measured" never reads as a different date than the
 *  one the snapshot was filed under. */
function measuredLabel(at: Date): string {
  return at.toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
    timeZone: 'UTC',
  });
}

/** Literal classes, not `text-${tone}` — Tailwind scans source text, so an
 *  interpolated class name is generated by nothing and arrives unstyled. */
const NOTE_CLASS = {
  danger: 'text-danger',
  warning: 'text-warning',
  primary: '',
} as const;

function Meter({ reading }: { reading: MeterReading }) {
  const note = meterNote(reading);
  const tone = meterTone(reading);
  return (
    <div>
      <p className="text-base font-semibold">{METER_LABEL[reading.meter]}</p>
      <p className="mt-1 text-2xl font-extrabold">{meterHeadline(reading)}</p>
      {/* A bar needs both a value and a ceiling. Drawing one against an
          undecided limit would invent the limit. */}
      {reading.fraction !== null ? (
        <Progress className="mt-2" color={tone} value={Math.min(reading.fraction * 100, 100)} />
      ) : null}
      {note ? <p className={`mt-2 text-sm ${NOTE_CLASS[tone]}`}>{note}</p> : null}
    </div>
  );
}

export function Capacity({ report }: { report: CapacityReport }) {
  return (
    <Card>
      <CardBody>
        <h2 className="text-xl font-bold">What you are using</h2>
        <p className="mt-1 text-base">
          Piggles includes every app at one price. What changes your bill is scale — how many
          people, how much you store, how much you send.
        </p>

        <div className="mt-6 grid gap-6 sm:grid-cols-2">
          {report.meters.map((m) => (
            <Meter key={m.meter} reading={m} />
          ))}
        </div>

        <p className="mt-6 text-sm">
          {report.measuredAt
            ? `Photos, files and customers were counted on ${measuredLabel(report.measuredAt)}. Everything else is live.`
            : 'Your first overnight count has not run yet, so some of these are still blank.'}
        </p>
      </CardBody>
    </Card>
  );
}
