// Token Model v2 preset defaults (docs/33-token-model-v2.md §3, build §2).
//
// One v2 default set per theme, carrying each preset's v1 identity (primary/
// accent/fonts/container/radius) forward and adding the v2 surface tiers
// (base-100/200/300), neutral fill, themeable status colors, the radius trio,
// rhythm scale, and depth. Lives alongside the v1 `tokenDefaults` until the
// read path cuts over (§3). Values are intentionally hand-tuned per theme
// personality; snapshot tests lock them so the visual defaults don't drift.

import type { ThemeKey } from '../types';
import type { ThemePresetV2 } from '../v2/types';

// Status colors are themeable in v2 but ship sensible cross-theme defaults
// (tenants/presets can override per slot). Dark variants are brightened for
// legibility on dark surfaces. `-content` pairs are auto-derived.
const STATUS_LIGHT = { info: '#0284c7', success: '#16a34a', warning: '#d97706', danger: '#dc2626' };
const STATUS_DARK = { info: '#38bdf8', success: '#4ade80', warning: '#fbbf24', danger: '#f87171' };

export const THEME_DEFAULTS_V2: Record<ThemeKey, ThemePresetV2> = {
  // ── Apex — clean, modern, versatile default ──────────────────────────────
  apex: {
    shared: {
      fontHeading: 'Inter',
      fontBody: 'Inter',
      radiusSelector: '9999px',
      radiusField: '0.375rem',
      radiusBox: '0.5rem',
      borderWidth: '1px',
      spaceBase: '0.25rem',
      sizeField: '2.75rem',
      sizeSelector: '2rem',
      depth: 1,
      containerWidth: 'medium',
    },
    light: {
      base100: '#ffffff',
      base200: '#f8fafc',
      base300: '#eef2f7',
      baseContent: '#0f172a',
      primary: '#4f46e5',
      primaryContent: '#ffffff',
      secondary: '#14b8a6',
      accent: '#0ea5e9',
      neutral: '#0f172a',
      border: '#e2e8f0',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#0b1120',
      base200: '#111827',
      base300: '#1b2538',
      baseContent: '#e2e8f0',
      primary: '#5b57ef',
      primaryContent: '#ffffff',
      secondary: '#2dd4bf',
      accent: '#38bdf8',
      neutral: '#e2e8f0',
      border: '#1f2937',
      ...STATUS_DARK,
    },
  },

  // ── Industrial — bold, high-contrast, technical (Gillett reference) ──────
  industrial: {
    shared: {
      fontHeading: 'Oswald',
      fontBody: 'Inter',
      radiusSelector: '0.125rem',
      radiusField: '0.125rem',
      radiusBox: '0.125rem',
      borderWidth: '2px',
      spaceBase: '0.25rem',
      sizeField: '2.875rem',
      sizeSelector: '2.125rem',
      depth: 0.6,
      containerWidth: 'wide',
    },
    light: {
      base100: '#ffffff',
      base200: '#fafafa',
      base300: '#f4f4f5',
      baseContent: '#18181b',
      primary: '#cc1010',
      primaryContent: '#ffffff',
      secondary: '#475569',
      accent: '#f59e0b',
      neutral: '#18181b',
      border: '#d4d4d8',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#0a0a0a',
      base200: '#141414',
      base300: '#1f1f22',
      baseContent: '#fafafa',
      primary: '#dc2626',
      primaryContent: '#ffffff',
      secondary: '#64748b',
      accent: '#fbbf24',
      neutral: '#fafafa',
      border: '#27272a',
      ...STATUS_DARK,
    },
  },

  // ── Drift — editorial, image-forward, minimal ────────────────────────────
  drift: {
    shared: {
      fontHeading: 'Playfair Display',
      fontBody: 'Inter',
      radiusSelector: '0px',
      radiusField: '0px',
      radiusBox: '0px',
      borderWidth: '1px',
      spaceBase: '0.28rem',
      sizeField: '2.875rem',
      sizeSelector: '2.125rem',
      depth: 0.4,
      containerWidth: 'wide',
    },
    light: {
      base100: '#fafafa',
      base200: '#ffffff',
      base300: '#f0ede8',
      baseContent: '#1a1a1a',
      primary: '#111111',
      primaryContent: '#ffffff',
      secondary: '#6b7280',
      accent: '#b08968',
      neutral: '#1a1a1a',
      border: '#e5e0d8',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#141414',
      base200: '#1c1c1c',
      base300: '#262626',
      baseContent: '#f0f0f0',
      primary: '#f5f5f5',
      primaryContent: '#111111',
      secondary: '#9ca3af',
      accent: '#c9a27e',
      neutral: '#f0f0f0',
      border: '#2a2a2a',
      ...STATUS_DARK,
    },
  },

  // ── Market — warm, artisan, community ────────────────────────────────────
  market: {
    shared: {
      fontHeading: 'Fraunces',
      fontBody: 'Nunito Sans',
      radiusSelector: '9999px',
      radiusField: '0.5rem',
      radiusBox: '0.75rem',
      borderWidth: '1px',
      spaceBase: '0.26rem',
      sizeField: '2.75rem',
      sizeSelector: '2rem',
      depth: 1.1,
      containerWidth: 'medium',
    },
    light: {
      base100: '#fffdf7',
      base200: '#fffdfa',
      base300: '#f5ecd9',
      baseContent: '#3a2e1f',
      primary: '#b45309',
      primaryContent: '#fffaf0',
      secondary: '#9a3412',
      accent: '#65a30d',
      neutral: '#3a2e1f',
      border: '#e7d8b8',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#1a1206',
      base200: '#221608',
      base300: '#2e2010',
      baseContent: '#f5ecd9',
      primary: '#d97706',
      primaryContent: '#1a1206',
      secondary: '#c2410c',
      accent: '#84cc16',
      neutral: '#f5ecd9',
      border: '#3a2a14',
      ...STATUS_DARK,
    },
  },

  // ── Fleet — data-dense, professional, dashboard-like ─────────────────────
  fleet: {
    shared: {
      fontHeading: 'IBM Plex Sans',
      fontBody: 'IBM Plex Sans',
      radiusSelector: '0.25rem',
      radiusField: '0.25rem',
      radiusBox: '0.25rem',
      borderWidth: '1px',
      spaceBase: '0.22rem',
      sizeField: '2.5rem',
      sizeSelector: '1.875rem',
      depth: 0.5,
      containerWidth: 'full',
    },
    light: {
      base100: '#ffffff',
      base200: '#f8fafc',
      base300: '#eef2f7',
      baseContent: '#0f172a',
      primary: '#1d4ed8',
      primaryContent: '#ffffff',
      secondary: '#0e7490',
      accent: '#0891b2',
      neutral: '#0f172a',
      border: '#cbd5e1',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#0f172a',
      base200: '#172033',
      base300: '#1e293b',
      baseContent: '#e2e8f0',
      primary: '#2563eb',
      primaryContent: '#ffffff',
      secondary: '#06b6d4',
      accent: '#22d3ee',
      neutral: '#e2e8f0',
      border: '#334155',
      ...STATUS_DARK,
    },
  },

  // ── Drop — bright, punchy, grid-first ────────────────────────────────────
  drop: {
    shared: {
      fontHeading: 'Poppins',
      fontBody: 'Inter',
      radiusSelector: '9999px',
      radiusField: '0.625rem',
      radiusBox: '1rem',
      borderWidth: '1px',
      spaceBase: '0.25rem',
      sizeField: '2.875rem',
      sizeSelector: '2.125rem',
      depth: 1.3,
      containerWidth: 'wide',
    },
    light: {
      base100: '#ffffff',
      base200: '#faf9fc',
      base300: '#f3f0f7',
      baseContent: '#18181b',
      primary: '#7c3aed',
      primaryContent: '#ffffff',
      secondary: '#06b6d4',
      accent: '#ec4899',
      neutral: '#18181b',
      border: '#e4e4e7',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#0c0a13',
      base200: '#131019',
      base300: '#1d1827',
      baseContent: '#ededf0',
      primary: '#7c3aed',
      primaryContent: '#ffffff',
      secondary: '#22d3ee',
      accent: '#f472b6',
      neutral: '#ededf0',
      border: '#272233',
      ...STATUS_DARK,
    },
  },

  // ── Noir — dark luxe, high-contrast, gold accent ─────────────────────────
  noir: {
    shared: {
      fontHeading: 'Cormorant Garamond',
      fontBody: 'Inter',
      radiusSelector: '0px',
      radiusField: '0px',
      radiusBox: '0px',
      borderWidth: '1px',
      spaceBase: '0.28rem',
      sizeField: '2.875rem',
      sizeSelector: '2.125rem',
      depth: 0.5,
      containerWidth: 'wide',
    },
    light: {
      base100: '#fafaf8',
      base200: '#ffffff',
      base300: '#f0eee9',
      baseContent: '#1a1a1a',
      primary: '#0a0a0a',
      primaryContent: '#f5f0e6',
      secondary: '#6b6256',
      accent: '#b08d57',
      neutral: '#0a0a0a',
      border: '#e2ded4',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#0b0b0c',
      base200: '#141416',
      base300: '#1d1d20',
      baseContent: '#eceae4',
      primary: '#f5f0e6',
      primaryContent: '#0a0a0a',
      secondary: '#a89b85',
      accent: '#c9a86a',
      neutral: '#eceae4',
      border: '#26262a',
      ...STATUS_DARK,
    },
  },

  // ── Sage — botanical calm, soft greens ───────────────────────────────────
  sage: {
    shared: {
      fontHeading: 'Fraunces',
      fontBody: 'Nunito Sans',
      radiusSelector: '9999px',
      radiusField: '0.5rem',
      radiusBox: '0.75rem',
      borderWidth: '1px',
      spaceBase: '0.26rem',
      sizeField: '2.75rem',
      sizeSelector: '2rem',
      depth: 0.9,
      containerWidth: 'medium',
    },
    light: {
      base100: '#fbfcfa',
      base200: '#ffffff',
      base300: '#eef2ea',
      baseContent: '#1f2a22',
      primary: '#4d7c5a',
      primaryContent: '#ffffff',
      secondary: '#7a8b6f',
      accent: '#a3b18a',
      neutral: '#1f2a22',
      border: '#dce5d5',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#0e1611',
      base200: '#141f18',
      base300: '#1c2a21',
      baseContent: '#e7ede3',
      primary: '#6fa67e',
      primaryContent: '#0e1611',
      secondary: '#8ba07d',
      accent: '#b6c49c',
      neutral: '#e7ede3',
      border: '#233127',
      ...STATUS_DARK,
    },
  },

  // ── Coast — airy coastal, teal-blue + sand ───────────────────────────────
  coast: {
    shared: {
      fontHeading: 'Poppins',
      fontBody: 'Inter',
      radiusSelector: '9999px',
      radiusField: '0.625rem',
      radiusBox: '1rem',
      borderWidth: '1px',
      spaceBase: '0.27rem',
      sizeField: '2.75rem',
      sizeSelector: '2rem',
      depth: 1.0,
      containerWidth: 'wide',
    },
    light: {
      base100: '#fbfdfe',
      base200: '#ffffff',
      base300: '#e8f3f6',
      baseContent: '#11303a',
      primary: '#0e7490',
      primaryContent: '#ffffff',
      secondary: '#2a9d8f',
      accent: '#f4a259',
      neutral: '#11303a',
      border: '#cfe6ec',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#06212a',
      base200: '#0b2c36',
      base300: '#123a46',
      baseContent: '#ddeef2',
      primary: '#22a7c4',
      primaryContent: '#052730',
      secondary: '#2dd4bf',
      accent: '#f4a259',
      neutral: '#ddeef2',
      border: '#144450',
      ...STATUS_DARK,
    },
  },

  // ── Ember — warm energetic, orange + raspberry ───────────────────────────
  ember: {
    shared: {
      fontHeading: 'Sora',
      fontBody: 'Inter',
      radiusSelector: '9999px',
      radiusField: '0.5rem',
      radiusBox: '0.625rem',
      borderWidth: '1px',
      spaceBase: '0.25rem',
      sizeField: '2.75rem',
      sizeSelector: '2rem',
      depth: 1.2,
      containerWidth: 'medium',
    },
    light: {
      base100: '#fffcf9',
      base200: '#ffffff',
      base300: '#fbefe7',
      baseContent: '#2b1a12',
      primary: '#e8590c',
      primaryContent: '#ffffff',
      secondary: '#c2255c',
      accent: '#f59f00',
      neutral: '#2b1a12',
      border: '#f3dccb',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#1a0e07',
      base200: '#24140c',
      base300: '#301b10',
      baseContent: '#f3e7de',
      primary: '#ff7a33',
      primaryContent: '#1a0e07',
      secondary: '#f35e94',
      accent: '#ffc94d',
      neutral: '#f3e7de',
      border: '#3a2114',
      ...STATUS_DARK,
    },
  },

  // ── Mono — strict monochrome, square edges ───────────────────────────────
  mono: {
    shared: {
      fontHeading: 'Archivo',
      fontBody: 'Inter',
      radiusSelector: '0px',
      radiusField: '0px',
      radiusBox: '0px',
      borderWidth: '1px',
      spaceBase: '0.25rem',
      sizeField: '2.75rem',
      sizeSelector: '2rem',
      depth: 0.3,
      containerWidth: 'wide',
    },
    light: {
      base100: '#ffffff',
      base200: '#fafafa',
      base300: '#f4f4f5',
      baseContent: '#111111',
      primary: '#111111',
      primaryContent: '#ffffff',
      secondary: '#52525b',
      accent: '#111111',
      neutral: '#111111',
      border: '#e4e4e7',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#0a0a0a',
      base200: '#141414',
      base300: '#1f1f1f',
      baseContent: '#fafafa',
      primary: '#fafafa',
      primaryContent: '#111111',
      secondary: '#a1a1aa',
      accent: '#fafafa',
      neutral: '#fafafa',
      border: '#262626',
      ...STATUS_DARK,
    },
  },

  // ── Bloom — playful pastel, pink + violet ────────────────────────────────
  bloom: {
    shared: {
      fontHeading: 'Quicksand',
      fontBody: 'Nunito',
      radiusSelector: '9999px',
      radiusField: '0.875rem',
      radiusBox: '1.25rem',
      borderWidth: '1px',
      spaceBase: '0.27rem',
      sizeField: '2.75rem',
      sizeSelector: '2rem',
      depth: 1.3,
      containerWidth: 'medium',
    },
    light: {
      base100: '#fffbfe',
      base200: '#ffffff',
      base300: '#fbeef6',
      baseContent: '#3a1e33',
      primary: '#db2777',
      primaryContent: '#ffffff',
      secondary: '#ec4899',
      accent: '#8b5cf6',
      neutral: '#3a1e33',
      border: '#f4d9ea',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#1c0e18',
      base200: '#271020',
      base300: '#34182b',
      baseContent: '#f6e6f0',
      primary: '#f472b6',
      primaryContent: '#2a0e1f',
      secondary: '#f9a8d4',
      accent: '#a78bfa',
      neutral: '#f6e6f0',
      border: '#3d1c33',
      ...STATUS_DARK,
    },
  },

  // ── Meridian — corporate professional, navy + sky ────────────────────────
  meridian: {
    shared: {
      fontHeading: 'Manrope',
      fontBody: 'Inter',
      radiusSelector: '0.375rem',
      radiusField: '0.375rem',
      radiusBox: '0.5rem',
      borderWidth: '1px',
      spaceBase: '0.24rem',
      sizeField: '2.625rem',
      sizeSelector: '2rem',
      depth: 0.6,
      containerWidth: 'wide',
    },
    light: {
      base100: '#ffffff',
      base200: '#f8fafc',
      base300: '#f1f5fb',
      baseContent: '#0f1b33',
      primary: '#1e3a8a',
      primaryContent: '#ffffff',
      secondary: '#0e7490',
      accent: '#0ea5e9',
      neutral: '#0f1b33',
      border: '#dce5f1',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#0a1124',
      base200: '#111a33',
      base300: '#18233f',
      baseContent: '#dce6f5',
      primary: '#3b5bdb',
      primaryContent: '#ffffff',
      secondary: '#22d3ee',
      accent: '#38bdf8',
      neutral: '#dce6f5',
      border: '#1e2a48',
      ...STATUS_DARK,
    },
  },

  // ── Terra — earthy artisan, terracotta + olive ───────────────────────────
  terra: {
    shared: {
      fontHeading: 'Fraunces',
      fontBody: 'Inter',
      radiusSelector: '0.5rem',
      radiusField: '0.375rem',
      radiusBox: '0.5rem',
      borderWidth: '1px',
      spaceBase: '0.26rem',
      sizeField: '2.75rem',
      sizeSelector: '2rem',
      depth: 0.9,
      containerWidth: 'medium',
    },
    light: {
      base100: '#fdfbf7',
      base200: '#ffffff',
      base300: '#f4ebdf',
      baseContent: '#2e2016',
      primary: '#9a3412',
      primaryContent: '#fff7ed',
      secondary: '#b45309',
      accent: '#4d7c0f',
      neutral: '#2e2016',
      border: '#e6d6c2',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#1a120a',
      base200: '#241910',
      base300: '#312316',
      baseContent: '#efe3d5',
      primary: '#c2410c',
      primaryContent: '#fff7ed',
      secondary: '#d97706',
      accent: '#84cc16',
      neutral: '#efe3d5',
      border: '#382616',
      ...STATUS_DARK,
    },
  },

  // ── Pulse — neon electric, violet + cyan on ink ──────────────────────────
  pulse: {
    shared: {
      fontHeading: 'Space Grotesk',
      fontBody: 'Inter',
      radiusSelector: '9999px',
      radiusField: '0.5rem',
      radiusBox: '0.75rem',
      borderWidth: '1px',
      spaceBase: '0.25rem',
      sizeField: '2.875rem',
      sizeSelector: '2.125rem',
      depth: 1.4,
      containerWidth: 'wide',
    },
    light: {
      base100: '#ffffff',
      base200: '#faf9fe',
      base300: '#f3f0fb',
      baseContent: '#18122b',
      primary: '#6d28d9',
      primaryContent: '#ffffff',
      secondary: '#db2777',
      accent: '#06b6d4',
      neutral: '#18122b',
      border: '#e4def5',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#0a0712',
      base200: '#130c24',
      base300: '#1c1335',
      baseContent: '#ede9f7',
      primary: '#8b5cf6',
      primaryContent: '#0b0716',
      secondary: '#f472b6',
      accent: '#22d3ee',
      neutral: '#ede9f7',
      border: '#241a3d',
      ...STATUS_DARK,
    },
  },

  // ── Linen — soft editorial, charcoal + clay on cream ─────────────────────
  linen: {
    shared: {
      fontHeading: 'Libre Baskerville',
      fontBody: 'Inter',
      radiusSelector: '0.25rem',
      radiusField: '0.25rem',
      radiusBox: '0.25rem',
      borderWidth: '1px',
      spaceBase: '0.28rem',
      sizeField: '2.875rem',
      sizeSelector: '2.125rem',
      depth: 0.4,
      containerWidth: 'wide',
    },
    light: {
      base100: '#faf8f4',
      base200: '#ffffff',
      base300: '#f1ede6',
      baseContent: '#292524',
      primary: '#44403c',
      primaryContent: '#faf8f5',
      secondary: '#78716c',
      accent: '#a8755a',
      neutral: '#292524',
      border: '#e4ddd2',
      ...STATUS_LIGHT,
    },
    dark: {
      base100: '#161412',
      base200: '#201d18',
      base300: '#2a261f',
      baseContent: '#ece7df',
      primary: '#e7e2da',
      primaryContent: '#1c1a17',
      secondary: '#a8a29e',
      accent: '#c18f73',
      neutral: '#ece7df',
      border: '#322d25',
      ...STATUS_DARK,
    },
  },
};

export const DEFAULT_THEME_KEY_V2: ThemeKey = 'apex';

/** Resolve a theme key to its v2 defaults, falling back to apex for an unknown
 *  key (mirrors the v1 getTheme contract). */
export function getThemePresetV2(key: string): ThemePresetV2 {
  return THEME_DEFAULTS_V2[key as ThemeKey] ?? THEME_DEFAULTS_V2[DEFAULT_THEME_KEY_V2];
}

export const THEME_KEYS_V2: ThemeKey[] = [
  'apex',
  'industrial',
  'drift',
  'market',
  'fleet',
  'drop',
  'noir',
  'sage',
  'coast',
  'ember',
  'mono',
  'bloom',
  'meridian',
  'terra',
  'pulse',
  'linen',
];
