// sparx — Couture Serif: a reference-driven SITE TEMPLATE (docs/templates/*),
// composed distinct — its own home section sequence, example commerce, and journal —
// and dressed in the bespoke theme its DESIGN.md pins.
//
// GENERATED by marketplace-catalog/_gen/gen-template-couture-serif.ts
// via the shared _gen/template-sites/harness.ts — do NOT hand-edit; edit the generator
// and regenerate. A blueprint is PURE DATA: the loader `import()`s this module with no
// workspace resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import content from './content.json' with { type: 'json' };
import commerce from './commerce.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };

const blueprint = {
  key: 'sparx-couture-serif',
  version: '1.1.0',
  name: 'sparx — Couture Serif',
  summary:
    'A high-fashion luxury-serif storefront where restraint is the premium — a centered-overlay campaign hero over collection tiles, a featured carousel and an editorial lookbook, all pure black on white in a classical serif. Modelled on the couture-serif archetype; shipped as Vérane, a fine-jewellery & fragrance maison.',
  vertical: 'retail',
  preview: 'media/preview.png',
  requiresModules: ['builder', 'commerce', 'cms', 'crm', 'email'],

  // Identity only (business name + tagline + fonts + the theme's hex colours). The look
  // itself rides site.theme + the theme decl below; the installing tenant rebrands the name.
  brand: {
    businessName: 'Vérane',
    tagline: 'Cut and composed in small numbers.',
    colors: {
      primary: '#020202',
      primaryForeground: '#f8f8f8',
      accent: '#605d59',
      secondary: '#47484a',
    },
    fonts: {
      heading: 'Libre Baskerville',
      body: 'Libre Baskerville',
    },
  },

  // The provisioned SiteTheme the installer creates + applies — the bespoke template
  // look as a tenant-editable saved theme (base preset = the template's own theme key,
  // plus its brand snapshot).
  theme: {
    name: 'couture-serif',
    basePresetKey: 'couture-serif',
    presentation: {
      v: 2,
      containerWidth: '1152px',
    },
    brand: {
      colorPrimary: '#020202',
      colorAccent: '#605d59',
      colorSecondary: '#47484a',
      fontHeading: 'Libre Baskerville',
      fontBody: 'Libre Baskerville',
      tokens: {},
    },
    apply: true,
  },

  assets,
  contentTypes: [],
  content,
  commerce,

  // Reference site templates ship no marketing emails of their own — the platform's
  // keyed transactional defaults cover the sends a fresh install needs.
  emails: [],
  sequences: [],

  // The composed distinct site (frame + a template-specific home + standard commerce/
  // cms/about/contact pages + the /journal index), in the bespoke theme, fully stamped.
  site,
};

export default blueprint;
