// sparx marketplace component — 'Policy text' (Page structure). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-3xl flex-col gap-8',
        children: [
          {
            kind: 'element',
            tag: 'h2',
            class: 'text-2xl font-semibold text-base-content',
            children: ['1. Who we are'],
          },
          {
            kind: 'element',
            tag: 'p',
            class: 'text-base text-base-content',
            children: [
              'These terms apply to everything we sell and every job we quote. "We" means the business named at the bottom of this page; "you" means the person or company placing the order.',
            ],
          },
          {
            kind: 'element',
            tag: 'h2',
            class: 'text-2xl font-semibold text-base-content',
            children: ['2. Quotes and prices'],
          },
          {
            kind: 'element',
            tag: 'p',
            class: 'text-base text-base-content',
            children: [
              'A written quote is valid for sixty days and includes materials, fitting and disposal unless it says otherwise. The price does not change after you accept it.',
            ],
          },
          {
            kind: 'element',
            tag: 'p',
            class: 'text-sm text-base-content',
            children: ['Last updated 18 July 2026.'],
          },
        ],
      },
    ],
  },
} as const;
