// sparx marketplace component — 'Three quotes' (People & proof). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-col gap-3',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                children: ['What customers say'],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 gap-6 @2xl:grid-cols-2 @4xl:grid-cols-3',
            children: [
              {
                kind: 'element',
                tag: 'figure',
                class: 'flex flex-col gap-3 rounded-box border border-base-300 bg-base-100 p-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'blockquote',
                    class: 'text-lg text-base-content',
                    children: [
                      '“Quoted on a Tuesday, started the following month, finished early.”',
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'figcaption',
                    class: 'flex flex-col gap-1',
                    children: [
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-base font-semibold text-base-content',
                        children: ['Helen Voss'],
                      },
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-sm text-base-content',
                        children: ['Riverside kitchen'],
                      },
                    ],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'figure',
                class: 'flex flex-col gap-3 rounded-box border border-base-300 bg-base-100 p-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'blockquote',
                    class: 'text-lg text-base-content',
                    children: [
                      '“The only trade I have used who left the house tidier than they found it.”',
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'figcaption',
                    class: 'flex flex-col gap-1',
                    children: [
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-base font-semibold text-base-content',
                        children: ['Michael Adeyemi'],
                      },
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-sm text-base-content',
                        children: ['Loft conversion'],
                      },
                    ],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'figure',
                class: 'flex flex-col gap-3 rounded-box border border-base-300 bg-base-100 p-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'blockquote',
                    class: 'text-lg text-base-content',
                    children: [
                      '“They talked me out of the expensive option. That is why I went back to them.”',
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'figcaption',
                    class: 'flex flex-col gap-1',
                    children: [
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-base font-semibold text-base-content',
                        children: ['Sara Lindqvist'],
                      },
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-sm text-base-content',
                        children: ['Garden room'],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
