// sparx marketplace component — 'Where we cover' (Where & when). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-col gap-3',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                children: ['Where we work'],
              },
              {
                kind: 'element',
                tag: 'p',
                class: 'max-w-2xl text-lg text-base-content',
                children: ['We cover these towns as standard. Further afield, ask — we often can.'],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'ul',
            class: 'grid grid-cols-2 gap-3 @2xl:grid-cols-3 @4xl:grid-cols-4',
            children: [
              {
                kind: 'element',
                tag: 'li',
                class: 'rounded-box border border-base-300 px-4 py-3 text-base text-base-content',
                children: ['Ashford'],
              },
              {
                kind: 'element',
                tag: 'li',
                class: 'rounded-box border border-base-300 px-4 py-3 text-base text-base-content',
                children: ['Canterbury'],
              },
              {
                kind: 'element',
                tag: 'li',
                class: 'rounded-box border border-base-300 px-4 py-3 text-base text-base-content',
                children: ['Faversham'],
              },
              {
                kind: 'element',
                tag: 'li',
                class: 'rounded-box border border-base-300 px-4 py-3 text-base text-base-content',
                children: ['Folkestone'],
              },
              {
                kind: 'element',
                tag: 'li',
                class: 'rounded-box border border-base-300 px-4 py-3 text-base text-base-content',
                children: ['Maidstone'],
              },
              {
                kind: 'element',
                tag: 'li',
                class: 'rounded-box border border-base-300 px-4 py-3 text-base text-base-content',
                children: ['Sittingbourne'],
              },
              {
                kind: 'element',
                tag: 'li',
                class: 'rounded-box border border-base-300 px-4 py-3 text-base text-base-content',
                children: ['Tenterden'],
              },
              {
                kind: 'element',
                tag: 'li',
                class: 'rounded-box border border-base-300 px-4 py-3 text-base text-base-content',
                children: ['Whitstable'],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'p',
            class: 'text-sm text-base-content',
            children: [
              'Outside these? Call us — a longer trip is usually still worth it for a bigger job.',
            ],
          },
        ],
      },
    ],
  },
} as const;
