// sparx — Fine Dining: a BOOKING-BACKED service-business SITE TEMPLATE.
//
// GENERATED by marketplace-catalog/_gen/gen-sparx-restaurant-fine-dining.ts via the shared
// _gen/service-sites/harness.ts — do NOT hand-edit; edit the generator and regenerate.
// A blueprint is PURE DATA: the loader `import()`s this module with no workspace
// resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import scheduling from './scheduling.json' with { type: 'json' };
import emails from './emails.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };

const blueprint = {
  key: 'sparx-restaurant-fine-dining',
  version: '1.3.1',
  name: 'sparx — Fine Dining',
  summary:
    'A complete, working site for a tasting-menu restaurant: a real seven-course menu with à la carte and wine pairing, and a live reservations flow (tables and a chef’s counter as bookable resources, party-size services, dinner-only hours, a per-cover deposit) on the /reserve page. Dark, candle-lit theme — warm charcoal, gold, copper. Pages: Home, Menu, Reserve, About, Visit. Shipped as Vesper.',
  vertical: 'services',
  preview: 'media/preview.png',
  requiresModules: ['builder', 'scheduling', 'crm', 'email'],

  // Identity only (business name + tagline + fonts + the theme's hex colors). The look
  // rides site.theme + the theme decl below; the installing tenant rebrands the name.
  brand: {
    businessName: 'Vesper',
    tagline: 'Dinner as an occasion.',
    colors: {
      primary: '#e1b767',
      primaryForeground: '#0f0a03',
      accent: '#ef9f67',
      secondary: '#bcb3a7',
    },
    fonts: {
      heading: 'Playfair Display',
      body: 'Inter',
    },
  },

  // The provisioned SiteTheme the installer creates + applies — an editable saved theme
  // over a foundation base + the template's brand snapshot. The LIVE storefront look is
  // site.theme (the flat bespoke tokens), written last.
  theme: {
    name: 'vesper-fine',
    basePresetKey: 'apex',
    presentation: {
      v: 2,
      containerWidth: '1152px',
    },
    brand: {
      colorPrimary: '#e1b767',
      colorAccent: '#ef9f67',
      colorSecondary: '#bcb3a7',
      fontHeading: 'Playfair Display',
      fontBody: 'Inter',
      tokens: {},
    },
    apply: true,
  },

  assets,
  contentTypes: [],

  // The booking spine — policies, bookable resources (staff/rooms/stations) with weekly
  // hours, and the service menu. The installer's scheduling slice replays it into a live
  // booking flow that the site's /book page renders.
  scheduling,

  // Brand-voiced MARKETING starters (a welcome + a come-back), installed as DRAFTS the
  // tenant switches on. The transactional booking sends — confirmation, reminder,
  // reschedule, cancellation, waitlist — are platform KEYED defaults, so they are covered
  // on email-module activation and are deliberately NOT duplicated here.
  emails,
  sequences: [],

  // The composed distinct site (frame + Home + Book + About + Contact) in the bespoke
  // theme, fully stamped.
  site,
};

export default blueprint;
