// sparx marketplace component — 'Enquiry form' (Get in touch). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 gap-10 @3xl:grid-cols-2',
            children: [
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-4',
                children: [
                  {
                    kind: 'element',
                    tag: 'h2',
                    class: 'text-3xl font-semibold text-base-content',
                    children: ['Tell us what you need'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: [
                      'A real person reads every one of these and replies, usually the same day. There is no obligation and we will not add you to anything.',
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-sm text-base-content',
                    children: ['Or call 01233 000000, Monday to Friday, 8am to 5pm.'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'form',
                class: 'flex flex-col gap-5',
                children: [
                  {
                    kind: 'element',
                    tag: 'label',
                    class: 'flex flex-col gap-2',
                    children: [
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-base font-medium text-base-content',
                        children: ['Your name'],
                      },
                      {
                        kind: 'element',
                        tag: 'input',
                        class: 'input input-bordered w-full',
                        attrs: {
                          type: 'text',
                          name: 'name',
                          placeholder: '',
                          required: true,
                        },
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'label',
                    class: 'flex flex-col gap-2',
                    children: [
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-base font-medium text-base-content',
                        children: ['Email address'],
                      },
                      {
                        kind: 'element',
                        tag: 'input',
                        class: 'input input-bordered w-full',
                        attrs: {
                          type: 'email',
                          name: 'email',
                          placeholder: '',
                          required: true,
                        },
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'label',
                    class: 'flex flex-col gap-2',
                    children: [
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-base font-medium text-base-content',
                        children: ['Phone number'],
                      },
                      {
                        kind: 'element',
                        tag: 'input',
                        class: 'input input-bordered w-full',
                        attrs: {
                          type: 'tel',
                          name: 'phone',
                          placeholder: '',
                          required: true,
                        },
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'label',
                    class: 'flex flex-col gap-2',
                    children: [
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-base font-medium text-base-content',
                        children: ['What are you thinking of?'],
                      },
                      {
                        kind: 'element',
                        tag: 'textarea',
                        class: 'textarea textarea-bordered min-h-32 w-full',
                        attrs: {
                          name: 'message',
                          placeholder: 'A rough idea is plenty to start with.',
                        },
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'button',
                    class: 'btn btn-primary btn-lg',
                    attrs: {
                      type: 'submit',
                    },
                    children: ['Send this'],
                  },
                ],
                behavior: {
                  type: 'form',
                },
                data: {
                  kind: 'action',
                  ref: 'submit',
                },
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
