// Bloom — a sparx first-party marketplace theme (docs/85). The payload is a
// complete DataThemePreset (v1 storefront tokens + v2 preset); the ingest
// validates it and writes it to storage as the applied-at-runtime artifact.
export default {
  v: 1,
  v1: {
    light: {
      colorPrimary: '#db2777',
      colorPrimaryForeground: '#ffffff',
      colorAccent: '#8b5cf6',
      colorBackground: '#fffbfe',
      colorForeground: '#3a1e33',
      colorMuted: '#fbeef6',
      colorBorder: '#f4d9ea',
      fontHeading: 'Quicksand',
      fontBody: 'Nunito',
      radiusBase: '1.25rem',
      containerWidth: 'medium',
    },
    dark: {
      colorPrimary: '#f472b6',
      colorPrimaryForeground: '#2a0e1f',
      colorAccent: '#a78bfa',
      colorBackground: '#1c0e18',
      colorForeground: '#f6e6f0',
      colorMuted: '#271020',
      colorBorder: '#3d1c33',
      fontHeading: 'Quicksand',
      fontBody: 'Nunito',
      radiusBase: '1.25rem',
      containerWidth: 'medium',
    },
  },
  v2: {
    shared: {
      fontHeading: 'Quicksand',
      fontBody: 'Nunito',
      radiusSelector: '9999px',
      radiusField: '0.875rem',
      radiusBox: '1.25rem',
      borderWidth: '1px',
      spaceBase: '0.27rem',
      sizeField: '2.75rem',
      sizeSelector: '2rem',
      depth: 1.3,
      containerWidth: 'medium',
    },
    light: {
      base100: '#fffbfe',
      base200: '#ffffff',
      base300: '#fbeef6',
      baseContent: '#3a1e33',
      primary: '#db2777',
      primaryContent: '#ffffff',
      secondary: '#ec4899',
      accent: '#8b5cf6',
      neutral: '#3a1e33',
      border: '#f4d9ea',
      info: '#0284c7',
      success: '#16a34a',
      warning: '#d97706',
      danger: '#dc2626',
    },
    dark: {
      base100: '#1c0e18',
      base200: '#271020',
      base300: '#34182b',
      baseContent: '#f6e6f0',
      primary: '#f472b6',
      primaryContent: '#2a0e1f',
      secondary: '#f9a8d4',
      accent: '#a78bfa',
      neutral: '#f6e6f0',
      border: '#3d1c33',
      info: '#38bdf8',
      success: '#4ade80',
      warning: '#fbbf24',
      danger: '#f87171',
    },
  },
};
