// Handyman (Modern): a BOOKING-BACKED service-business SITE TEMPLATE.
//
// GENERATED by marketplace-catalog/_gen/gen-sparx-handyman-modern.ts via the shared
// _gen/service-sites/harness.ts — do NOT hand-edit; edit the generator and regenerate.
// A blueprint is PURE DATA: the loader `import()`s this module with no workspace
// resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import scheduling from './scheduling.json' with { type: 'json' };
import emails from './emails.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };

const blueprint = {
  key: 'sparx-handyman-modern',
  version: '1.4.0',
  name: 'Handyman (Modern)',
  summary:
    'A bright, techy handyman site for on-demand home repairs — book a vetted pro online in minutes at a flat hourly rate. Installs a working booking flow: a real task menu (mounting, assembly, smart-home, half-day projects), three vetted pros dispatched as bookable resources with long weekday and weekend hours, and same-day scheduling. Ships as "FixList", a modern on-demand handyman service.',
  vertical: 'services',
  preview: 'media/preview.png',
  requiresModules: ['builder', 'scheduling', 'crm', 'email'],

  // Identity only (business name + tagline + fonts + the theme's hex colors). The look
  // rides site.theme + the theme decl below; the installing tenant rebrands the name.
  brand: {
    businessName: 'FixList',
    tagline: 'Home fixed, booked from your phone.',
    colors: {
      primary: '#009d9e',
      primaryForeground: '#020e0e',
      accent: '#eea743',
      secondary: '#303b4a',
    },
    fonts: {
      heading: 'Space Grotesk',
      body: 'Inter',
    },
  },

  // The provisioned SiteTheme the installer creates + applies — an editable saved theme
  // over a foundation base + the template's brand snapshot. The LIVE storefront look is
  // site.theme (the flat bespoke tokens), written last.
  theme: {
    name: 'fixlist',
    basePresetKey: 'apex',
    presentation: {
      v: 2,
      containerWidth: '1152px',
    },
    brand: {
      colorPrimary: '#009d9e',
      colorAccent: '#eea743',
      colorSecondary: '#303b4a',
      fontHeading: 'Space Grotesk',
      fontBody: 'Inter',
      tokens: {},
    },
    apply: true,
  },

  assets,
  contentTypes: [],

  // The booking spine — policies, bookable resources (staff/rooms/stations) with weekly
  // hours, and the service menu. The installer's scheduling slice replays it into a live
  // booking flow that the site's /book page renders.
  scheduling,

  // Brand-voiced MARKETING starters (a welcome + a come-back), installed as DRAFTS the
  // tenant switches on. The transactional booking sends — confirmation, reminder,
  // reschedule, cancellation, waitlist — are platform KEYED defaults, so they are covered
  // on email-module activation and are deliberately NOT duplicated here.
  emails,
  sequences: [],

  // The composed distinct site (frame + Home + Book + About + Contact) in the bespoke
  // theme, fully stamped.
  site,
};

export default blueprint;
