// sparx — News Feed: a reference-driven SITE TEMPLATE (docs/templates/*),
// composed distinct — its own home section sequence, example commerce, and journal —
// and dressed in the bespoke theme its DESIGN.md pins.
//
// GENERATED by marketplace-catalog/_gen/gen-template-news-feed.ts
// via the shared _gen/template-sites/harness.ts — do NOT hand-edit; edit the generator
// and regenerate. A blueprint is PURE DATA: the loader `import()`s this module with no
// workspace resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import content from './content.json' with { type: 'json' };
import authors from './authors.json' with { type: 'json' };
import commerce from './commerce.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };

const blueprint = {
  key: 'sparx-news-feed',
  version: '1.1.0',
  name: 'sparx — News Feed',
  summary:
    'A dense front-page feed for a technology & business publication — a full-width lead over a rail of the day’s stories, a live journal, and a bespoke bylined article page, in a white-ground one-accent theme. Modelled on the tech-newsroom archetype; shipped as Frequency. Ships a light store (reports, a book, membership) to demonstrate content + commerce together.',
  vertical: 'content',
  preview: 'media/preview.png',
  requiresModules: ['builder', 'commerce', 'cms', 'crm', 'email'],

  // Identity only (business name + tagline + fonts + the theme's hex colours). The look
  // itself rides site.theme + the theme decl below; the installing tenant rebrands the name.
  brand: {
    businessName: 'Frequency',
    tagline: 'The signal in the noise.',
    colors: {
      primary: '#007e4b',
      primaryForeground: '#f3fbf6',
      accent: '#007e4b',
      secondary: '#4a545d',
    },
    fonts: {
      heading: 'Space Grotesk',
      body: 'Inter',
    },
  },

  // The provisioned SiteTheme the installer creates + applies — the bespoke template
  // look as a tenant-editable saved theme (base preset = the template's own theme key,
  // plus its brand snapshot).
  theme: {
    name: 'news-feed',
    basePresetKey: 'news-feed',
    presentation: {
      v: 2,
      containerWidth: '1152px',
    },
    brand: {
      colorPrimary: '#007e4b',
      colorAccent: '#007e4b',
      colorSecondary: '#4a545d',
      fontHeading: 'Space Grotesk',
      fontBody: 'Inter',
      tokens: {},
    },
    apply: true,
  },

  assets,
  contentTypes: [],
  authors,
  content,
  commerce,

  // Reference site templates ship no marketing emails of their own — the platform's
  // keyed transactional defaults cover the sends a fresh install needs.
  emails: [],
  sequences: [],

  // The composed distinct site (frame + a template-specific home + standard commerce/
  // cms/about/contact pages + the /journal index), in the bespoke theme, fully stamped.
  site,
};

export default blueprint;
