// sparx marketplace component — 'Callout' (Writing). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-3xl flex-col gap-8',
        children: [
          {
            kind: 'element',
            tag: 'aside',
            class: 'flex flex-col gap-2 rounded-box border border-warning bg-warning/10 p-6',
            children: [
              {
                kind: 'element',
                tag: 'p',
                class: 'text-base font-semibold text-warning',
                children: ['Worth knowing'],
              },
              {
                kind: 'element',
                tag: 'p',
                class: 'text-base text-base-content',
                children: [
                  'Moisture readings taken on a cold morning read low. Bring the piece indoors for an hour before you trust the number.',
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
