// sparx — Chiropractic (Sports & Rehab): a BOOKING-BACKED service-business SITE TEMPLATE.
//
// GENERATED by marketplace-catalog/_gen/gen-sparx-chiro-sports.ts via the shared
// _gen/service-sites/harness.ts — do NOT hand-edit; edit the generator and regenerate.
// A blueprint is PURE DATA: the loader `import()`s this module with no workspace
// resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import scheduling from './scheduling.json' with { type: 'json' };
import emails from './emails.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };

const blueprint = {
  key: 'sparx-chiro-sports',
  version: '1.2.0',
  name: 'sparx — Chiropractic (Sports & Rehab)',
  summary:
    'A bold, athletic chiropractic & performance site — electric-blue palette, sturdy condensed type, built for athletes and active people. Installs a working booking flow: sports-injury visits, active-release, dry needling, rehab and a free performance consult, with providers AND treatment rooms as multi-requirement resources. Ships as "Kinetic Spine & Sport", a sports/rehab clinic that books online from day one.',
  vertical: 'services',
  preview: 'media/preview.png',
  requiresModules: ['builder', 'scheduling', 'crm', 'email'],

  // Identity only (business name + tagline + fonts + the theme's hex colours). The look
  // rides site.theme + the theme decl below; the installing tenant rebrands the name.
  brand: {
    businessName: 'Kinetic Spine & Sport',
    tagline: 'Fix the cause. Build it back.',
    colors: {
      primary: '#0071e0',
      primaryForeground: '#ffffff',
      accent: '#9ad335',
      secondary: '#2d384a',
    },
    fonts: {
      heading: 'Oswald',
      body: 'Inter',
    },
  },

  // The provisioned SiteTheme the installer creates + applies — an editable saved theme
  // over a foundation base + the template's brand snapshot. The LIVE storefront look is
  // site.theme (the flat bespoke tokens), written last.
  theme: {
    name: 'kinetic',
    basePresetKey: 'apex',
    presentation: {
      v: 2,
      containerWidth: '1152px',
    },
    brand: {
      colorPrimary: '#0071e0',
      colorAccent: '#9ad335',
      colorSecondary: '#2d384a',
      fontHeading: 'Oswald',
      fontBody: 'Inter',
      tokens: {},
    },
    apply: true,
  },

  assets,
  contentTypes: [],

  // The booking spine — policies, bookable resources (staff/rooms/stations) with weekly
  // hours, and the service menu. The installer's scheduling slice replays it into a live
  // booking flow that the site's /book page renders.
  scheduling,

  // Brand-voiced MARKETING starters (a welcome + a come-back), installed as DRAFTS the
  // tenant switches on. The transactional booking sends — confirmation, reminder,
  // reschedule, cancellation, waitlist — are platform KEYED defaults, so they are covered
  // on email-module activation and are deliberately NOT duplicated here.
  emails,
  sequences: [],

  // The composed distinct site (frame + Home + Book + About + Contact) in the bespoke
  // theme, fully stamped.
  site,
};

export default blueprint;
