// The British spellings this repo refuses, and what each one is in American
// English. ONE list, because there are two guards over it and they had already
// drifted apart twice: `scripts/check-american-spelling.mjs` reads the servers,
// packages, seed data and catalog, and each console's own
// `lib/console/american-spelling.test.ts` reads its surfaces. A word added to
// one and not the other is a word half-guarded, which is how "ready to fulfil"
// shipped in both consoles while the server list already knew "fulfilment".
//
// Plain data, no side effects, so a vitest file can import it as safely as the
// CLI script does.
//
// A word that cannot appear costs nothing to list, and `metre` does NOT
// match inside "millimetre" — the letter before it is a word character, so
// there is no boundary. List the compounds and the bare forms both. Issue 767.

export const BRITISH_WORDS = {
  licence: 'license',
  licences: 'licenses',
  colour: 'color',
  colours: 'colors',
  coloured: 'colored',
  favourite: 'favorite',
  favourites: 'favorites',
  favourited: 'favorited',
  behaviour: 'behavior',
  behaviours: 'behaviors',
  // The whole -ise family this list already knew in two other verbs, and not
  // in this one. "not anonymised, not ever" sat in the privacy page, the terms,
  // the data-processing record and the account app's own assurance panel: the
  // most carefully worded copy on the site, in the wrong English (issue 880).
  anonymise: 'anonymize',
  anonymised: 'anonymized',
  anonymises: 'anonymizes',
  anonymising: 'anonymizing',
  anonymisation: 'anonymization',
  organise: 'organize',
  organised: 'organized',
  organising: 'organizing',
  organisation: 'organization',
  organisations: 'organizations',
  catalogue: 'catalog',
  catalogues: 'catalogs',
  fulfilment: 'fulfillment',
  fulfilments: 'fulfillments',
  // THE BARE VERB, which this list did not have. `fulfilment` cannot match
  // "fulfil" — the noun is a longer word, so the shorter one never comes up
  // against the boundary — exactly the way `metre` could not see
  // "millimetre" (above). A toast shipped "ready to fulfil" in both consoles
  // under a guard whose whole job is that word. Issue 767.
  fulfil: 'fulfill',
  fulfils: 'fulfills',
  // Same shape: the list held the -ment noun and not the verb it comes from.
  enrol: 'enroll',
  enrols: 'enrolls',
  // "Enquiry" is the British half of a pair American English does not make:
  // over there an enquiry is a question and an inquiry is an investigation, and
  // here "inquiry" is both. It was missing from this list, so every guard that
  // reads it was honestly green while **38 lines of copy** said it — a saved
  // view's placeholder ("New enquiries"), a notification group ("Customers &
  // enquiries"), the empty state on Form replies in BOTH consoles, the deal
  // title the server writes for a website lead ("Website enquiry"), a silica
  // section's own label ("Enquiry form"), and eleven paragraphs of marketing.
  // Measured 2026-09-25 over 6,760 files. [[feedback_structural_checks_go_blind]]
  //
  // Four things keep the British spelling and are not defects: the funnel stage
  // KEY `enquired` (history is recorded against it), the silica catalog key
  // `enquiry_form` (stamped into published pages), the FAQ anchor id
  // `tattoo-enquiry`, and the search keywords, which list BOTH so that somebody
  // who types either still finds the pane.
  enquiry: 'inquiry',
  enquiries: 'inquiries',
  enquire: 'inquire',
  enquires: 'inquires',
  enquired: 'inquired',
  enquiring: 'inquiring',
  instal: 'install',
  instals: 'installs',
  analyse: 'analyze',
  analysed: 'analyzed',
  whilst: 'while',
  cancelled: 'canceled',
  cancelling: 'canceling',
  cheque: 'check',
  cheques: 'checks',
  postcode: 'postal code',
  postcodes: 'postal codes',
  centre: 'center',
  centres: 'centers',
  labelled: 'labeled',
  labelling: 'labeling',
  travelled: 'traveled',
  travelling: 'traveling',
  modelling: 'modeling',
  enrolment: 'enrollment',
  enrolments: 'enrollments',
  instalment: 'installment',
  instalments: 'installments',
  labour: 'labor',
  neighbour: 'neighbor',
  neighbours: 'neighbors',
  honour: 'honor',
  flavour: 'flavor',
  flavours: 'flavors',
  humour: 'humor',
  recognise: 'recognize',
  recognised: 'recognized',
  recognises: 'recognizes',
  customise: 'customize',
  customised: 'customized',
  personalise: 'personalize',
  personalised: 'personalized',
  prioritise: 'prioritize',
  prioritised: 'prioritized',
  summarise: 'summarize',
  summarised: 'summarized',
  authorise: 'authorize',
  authorised: 'authorized',
  apologise: 'apologize',
  utilise: 'utilize',
  utilised: 'utilized',
  optimise: 'optimize',
  optimised: 'optimized',
  optimises: 'optimizes',
  // The -ise family the list had started but not finished. Every one of these
  // is British-only: none is an accepted American spelling, so listing one that
  // never appears costs nothing and listing one that does is the point.
  realise: 'realize',
  realised: 'realized',
  realises: 'realizes',
  minimise: 'minimize',
  minimised: 'minimized',
  maximise: 'maximize',
  maximised: 'maximized',
  finalise: 'finalize',
  finalised: 'finalized',
  specialise: 'specialize',
  specialised: 'specialized',
  standardise: 'standardize',
  standardised: 'standardized',
  emphasise: 'emphasize',
  emphasised: 'emphasized',
  categorise: 'categorize',
  categorised: 'categorized',
  normalise: 'normalize',
  normalised: 'normalized',
  itemise: 'itemize',
  itemised: 'itemized',
  initialise: 'initialize',
  initialised: 'initialized',
  serialise: 'serialize',
  serialised: 'serialized',
  synchronise: 'synchronize',
  synchronised: 'synchronized',
  visualise: 'visualize',
  visualised: 'visualized',
  localise: 'localize',
  localised: 'localized',
  digitise: 'digitize',
  digitised: 'digitized',
  apologised: 'apologized',
  organises: 'organizes',
  analysing: 'analyzing',
  recognising: 'recognizing',
  customises: 'customizes',
  summarises: 'summarizes',
  authorises: 'authorizes',
  prioritises: 'prioritizes',
  defence: 'defense',
  offence: 'offense',
  grey: 'gray',
  programme: 'program',
  programmes: 'programs',
  metre: 'meter',
  metres: 'meters',
  litre: 'liter',
  litres: 'liters',
  millimetre: 'millimeter',
  millimetres: 'millimeters',
  centimetre: 'centimeter',
  centimetres: 'centimeters',
  kilometre: 'kilometer',
  kilometres: 'kilometers',
  millilitre: 'milliliter',
  millilitres: 'milliliters',
  judgement: 'judgment',
  acknowledgement: 'acknowledgment',
  storey: 'story',
  tyre: 'tire',
  aluminium: 'aluminum',
  // Words a shop's own catalog, copy or theme could plausibly hold. A textile
  // tenant writes about fibre and woollens; a food one about savoury and
  // yoghurt; a jeweller about jewellery. None of these has an American reading.
  fibre: 'fiber',
  fibres: 'fibers',
  woollen: 'woolen',
  woollens: 'woolens',
  jewellery: 'jewelry',
  jewellers: 'jewelers',
  speciality: 'specialty',
  specialities: 'specialties',
  savoury: 'savory',
  yoghurt: 'yogurt',
  omelette: 'omelet',
  theatre: 'theater',
  theatres: 'theaters',
  calibre: 'caliber',
  moulding: 'molding',
  mouldings: 'moldings',
  ageing: 'aging',
  artefact: 'artifact',
  artefacts: 'artifacts',
  practise: 'practice',
  practised: 'practiced',
  practising: 'practicing',
  pretence: 'pretense',
  sceptical: 'skeptical',
  manoeuvre: 'maneuver',
  manoeuvres: 'maneuvers',
  marvellous: 'marvelous',
  moustache: 'mustache',
  counsellor: 'counselor',
  counsellors: 'counselors',
  counselling: 'counseling',
  councillor: 'councilor',
  cataloguing: 'cataloging',
  totalled: 'totaled',
  totalling: 'totaling',
  levelled: 'leveled',
  levelling: 'leveling',
  fuelled: 'fueled',
  fuelling: 'fueling',
  signalled: 'signaled',
  signalling: 'signaling',
  channelled: 'channeled',
  channelling: 'channeling',
  dialled: 'dialed',
  dialling: 'dialing',
  // -our nouns, the family `colour`/`labour`/`honour` already opened.
  labours: 'labors',
  laboured: 'labored',
  honours: 'honors',
  honoured: 'honored',
  flavoured: 'flavored',
  harbour: 'harbor',
  parlour: 'parlor',
  parlours: 'parlors',
  savour: 'savor',
  endeavour: 'endeavor',
  endeavours: 'endeavors',
  rumour: 'rumor',
  rumours: 'rumors',
  vapour: 'vapor',
  vigour: 'vigor',
  armour: 'armor',
  odour: 'odor',
  odours: 'odors',
  splendour: 'splendor',
  candour: 'candor',
  valour: 'valor',
  saviour: 'savior',
  demeanour: 'demeanor',
};
