// sparx marketplace component — 'Opening hours' (Where & when). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-col gap-3',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                children: ['Opening hours'],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'table',
            class: 'w-full max-w-md border-collapse',
            children: [
              {
                kind: 'element',
                tag: 'tbody',
                children: [
                  {
                    kind: 'element',
                    tag: 'tr',
                    children: [
                      {
                        kind: 'element',
                        tag: 'th',
                        class:
                          'border-t border-base-300 py-3 pr-6 text-left text-base font-medium text-base-content',
                        children: ['Monday'],
                      },
                      {
                        kind: 'element',
                        tag: 'td',
                        class: 'border-t border-base-300 py-3 text-base text-base-content',
                        children: ['8am – 5pm'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'tr',
                    children: [
                      {
                        kind: 'element',
                        tag: 'th',
                        class:
                          'border-t border-base-300 py-3 pr-6 text-left text-base font-medium text-base-content',
                        children: ['Tuesday'],
                      },
                      {
                        kind: 'element',
                        tag: 'td',
                        class: 'border-t border-base-300 py-3 text-base text-base-content',
                        children: ['8am – 5pm'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'tr',
                    children: [
                      {
                        kind: 'element',
                        tag: 'th',
                        class:
                          'border-t border-base-300 py-3 pr-6 text-left text-base font-medium text-base-content',
                        children: ['Wednesday'],
                      },
                      {
                        kind: 'element',
                        tag: 'td',
                        class: 'border-t border-base-300 py-3 text-base text-base-content',
                        children: ['8am – 5pm'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'tr',
                    children: [
                      {
                        kind: 'element',
                        tag: 'th',
                        class:
                          'border-t border-base-300 py-3 pr-6 text-left text-base font-medium text-base-content',
                        children: ['Thursday'],
                      },
                      {
                        kind: 'element',
                        tag: 'td',
                        class: 'border-t border-base-300 py-3 text-base text-base-content',
                        children: ['8am – 7pm'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'tr',
                    children: [
                      {
                        kind: 'element',
                        tag: 'th',
                        class:
                          'border-t border-base-300 py-3 pr-6 text-left text-base font-medium text-base-content',
                        children: ['Friday'],
                      },
                      {
                        kind: 'element',
                        tag: 'td',
                        class: 'border-t border-base-300 py-3 text-base text-base-content',
                        children: ['8am – 5pm'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'tr',
                    children: [
                      {
                        kind: 'element',
                        tag: 'th',
                        class:
                          'border-t border-base-300 py-3 pr-6 text-left text-base font-medium text-base-content',
                        children: ['Saturday'],
                      },
                      {
                        kind: 'element',
                        tag: 'td',
                        class: 'border-t border-base-300 py-3 text-base text-base-content',
                        children: ['9am – 1pm'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'tr',
                    children: [
                      {
                        kind: 'element',
                        tag: 'th',
                        class:
                          'border-t border-base-300 py-3 pr-6 text-left text-base font-medium text-base-content',
                        children: ['Sunday'],
                      },
                      {
                        kind: 'element',
                        tag: 'td',
                        class: 'border-t border-base-300 py-3 text-base text-base-content',
                        children: ['Closed'],
                      },
                    ],
                  },
                ],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'p',
            class: 'text-sm text-base-content',
            children: ['Bank holidays vary — call ahead if you are making a special trip.'],
          },
        ],
      },
    ],
  },
} as const;
