// Inventory — knowing what you have and where it is.

import {
  ArrowLeftRight,
  BarChart3,
  Boxes,
  ClipboardCheck,
  ClipboardList,
  History,
  Layers,
  Link2,
  PackageCheck,
  RefreshCw,
  Truck,
  Warehouse,
} from 'lucide-react';
import type { SurfaceDefinition } from '../registry';
import { stub } from './stub';

export const INVENTORY_SURFACES: SurfaceDefinition[] = [
  stub({
    key: 'inventory.stock.list',
    title: 'Stock',
    module: 'inventory',
    icon: Boxes,
    order: 1,
    keywords: ['on hand', 'levels', 'quantity', 'availability'],
    body: 'How much of each thing you have right now, everywhere you keep it.',
  }),

  /* ── Where it lives ────────────────────────────────────────────────────── */
  stub({
    key: 'inventory.warehouses.list',
    title: 'Locations',
    module: 'inventory',
    icon: Warehouse,
    section: 'Where it lives',
    order: 10,
    keywords: ['warehouses', 'shops', 'sites', 'storage'],
    body: 'Every place you hold stock — a warehouse, a shop floor, a van.',
  }),
  stub({
    key: 'inventory.transfers.list',
    title: 'Transfers',
    module: 'inventory',
    icon: ArrowLeftRight,
    section: 'Where it lives',
    order: 11,
    keywords: ['move', 'between locations'],
    body: 'Stock on its way from one of your locations to another.',
  }),
  stub({
    key: 'inventory.counts.list',
    title: 'Stock counts',
    module: 'inventory',
    icon: ClipboardCheck,
    section: 'Where it lives',
    order: 12,
    keywords: ['stocktake', 'audit', 'physical count'],
    body: 'Counting what is actually on the shelf and correcting the numbers when they disagree.',
  }),
  stub({
    key: 'inventory.movements.list',
    title: 'Movements',
    module: 'inventory',
    icon: History,
    section: 'Where it lives',
    order: 13,
    keywords: ['history', 'ledger', 'changes', 'why'],
    body: 'Every change to a stock number and what caused it — a sale, a delivery, a correction.',
  }),
  stub({
    key: 'inventory.lots.list',
    title: 'Lots & serials',
    module: 'inventory',
    icon: Layers,
    section: 'Where it lives',
    order: 14,
    keywords: ['batch', 'serial number', 'expiry', 'traceability'],
    body: 'Tracking individual batches or serial numbers, so you can trace exactly which one a customer got.',
  }),

  /* ── Buying ────────────────────────────────────────────────────────────── */
  stub({
    key: 'inventory.suppliers.list',
    title: 'Suppliers',
    module: 'inventory',
    icon: Truck,
    section: 'Buying',
    order: 20,
    keywords: ['vendors', 'wholesalers'],
    body: 'The businesses you buy from, and what you buy from each one.',
  }),
  stub({
    key: 'inventory.purchase-orders.list',
    title: 'Purchase orders',
    module: 'inventory',
    icon: ClipboardList,
    section: 'Buying',
    order: 21,
    keywords: ['po', 'ordering', 'restock'],
    body: 'Orders you have placed with a supplier, and what is still outstanding.',
  }),
  stub({
    key: 'inventory.receiving.list',
    title: 'Receiving',
    module: 'inventory',
    icon: PackageCheck,
    section: 'Buying',
    order: 22,
    keywords: ['delivery', 'goods in', 'check in'],
    body: 'Booking in a delivery when it arrives, including when what turned up is not what you ordered.',
  }),
  stub({
    key: 'inventory.reorder',
    title: 'Reorder',
    module: 'inventory',
    icon: RefreshCw,
    section: 'Buying',
    order: 23,
    keywords: ['low stock', 'replenish', 'buy more'],
    body: 'What is running low and needs buying again, worked out from how fast it sells.',
  }),

  /* ── Reporting / Setup ─────────────────────────────────────────────────── */
  stub({
    key: 'inventory.reports',
    title: 'Reports',
    module: 'inventory',
    icon: BarChart3,
    section: 'Reporting',
    order: 30,
    keywords: ['analytics', 'value', 'ageing', 'turnover'],
    body: 'What your stock is worth, what is sitting still, and what moves fastest.',
  }),
  stub({
    key: 'inventory.sources',
    title: 'Stock sources',
    module: 'inventory',
    icon: Link2,
    section: 'Setup',
    order: 40,
    keywords: ['feeds', 'sync', 'external'],
    body: 'Where stock numbers come from when something outside sparx is the one keeping count.',
  }),
];
