// sparx marketplace component — 'Featured offer' (Selling). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 items-center gap-10 @3xl:grid-cols-2',
            children: [
              {
                kind: 'element',
                tag: 'img',
                class:
                  'aspect-square w-full rounded-box border border-base-300 bg-base-200 object-cover',
                attrs: {
                  src: '',
                  alt: 'The featured piece',
                  loading: 'lazy',
                },
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col items-start gap-5',
                children: [
                  {
                    kind: 'element',
                    tag: 'div',
                    class: 'flex flex-wrap items-center gap-2',
                    children: [
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'badge badge-success badge-soft',
                        children: ['In stock'],
                      },
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'badge badge-info badge-soft',
                        children: ['Made here'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'h2',
                    class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                    children: ['The Mill Lane table'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-lg text-base-content',
                    children: [
                      'Solid oak, 40mm, made to your length. The one we have built more of than anything else.',
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-3xl font-semibold text-base-content',
                    children: ['$1,480'],
                  },
                  {
                    kind: 'element',
                    tag: 'div',
                    class: 'flex flex-wrap items-center gap-3',
                    children: [
                      {
                        kind: 'element',
                        tag: 'a',
                        class: 'btn btn-primary btn-lg',
                        attrs: {
                          href: '#',
                        },
                        children: ['Add to basket'],
                      },
                      {
                        kind: 'element',
                        tag: 'a',
                        class: 'btn btn-neutral btn-outline btn-lg',
                        attrs: {
                          href: '#',
                        },
                        children: ['Ask a question'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-sm text-base-content',
                    children: ['Free delivery within 50 miles. Four to six weeks from order.'],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
