// sparx — Chocolate & Sweets (Playful): a reference-driven SITE TEMPLATE (docs/templates/*),
// composed distinct — its own home section sequence, example commerce, and journal —
// and dressed in the bespoke theme its DESIGN.md pins.
//
// GENERATED by marketplace-catalog/_gen/gen-template-retail-chocolate-playful.ts
// via the shared _gen/template-sites/harness.ts — do NOT hand-edit; edit the generator
// and regenerate. A blueprint is PURE DATA: the loader `import()`s this module with no
// workspace resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import content from './content.json' with { type: 'json' };
import authors from './authors.json' with { type: 'json' };
import commerce from './commerce.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };
import emails from './emails.json' with { type: 'json' };

const blueprint = {
    key: 'sparx-retail-chocolate-playful',
    version: '1.4.0',
    name: 'sparx — Chocolate & Sweets (Playful)',
    summary:
        'A complete, working shop for a bright, gift-forward chocolate & sweets maker: colorful bonbon boxes, a build-your-own selection, hot-cocoa bombs, dipped treats, a birthday box, a kids’ bundle and a flexible subscription, with categories, collections, a bespoke PDP and a fully merchandised home page. Joyful sweet-shop theme — vanilla cream, a raspberry candy primary, a berry-grape pop accent, a rounded display and playful hovers. Shipped as Sweet Tooth Co.',
    vertical: 'retail',
    preview: 'media/preview.png',
    requiresModules: ['builder', 'commerce', 'cms', 'crm', 'email'],

    // Identity only (business name + tagline + fonts + the theme's hex colors). The look
    // itself rides site.theme + the theme decl below; the installing tenant rebrands the name.
    brand: {
        businessName: 'Sweet Tooth Co.',
        tagline: 'Chocolate, but make it fun.',
        colors: {
            primary: '#cd285e',
            primaryForeground: '#fff6f7',
            accent: '#862c81',
            secondary: '#68432f',
        },
        fonts: {
            heading: 'Fredoka',
            body: 'Nunito',
        },
    },

    // The provisioned SiteTheme the installer creates + applies — the bespoke template
    // look as a tenant-editable saved theme (base preset = the template's own theme key,
    // plus its brand snapshot).
    theme: {
        name: 'retail-chocolate-playful',
        basePresetKey: 'retail-chocolate-playful',
        presentation: {
            v: 2,
            containerWidth: '1152px',
        },
        brand: {
            colorPrimary: '#cd285e',
            colorAccent: '#862c81',
            colorSecondary: '#68432f',
            fontHeading: 'Fredoka',
            fontBody: 'Nunito',
            tokens: {},
        },
        apply: true,
    },

    assets,
    contentTypes: [],
    authors,
    content,
    commerce,

    // A shop's brand-voiced MARKETING starters (a welcome + a win-back), tokenized so a fork
    // re-themes to the tenant and installed as DRAFTS — the platform's keyed transactional
    // defaults (order/shipping/dunning) are separate and never duplicated here. Content
    // templates ship an empty set.
    emails,
    sequences: [],

    // The composed distinct site (frame + a template-specific home + standard commerce/
    // cms/about/contact pages + the /journal index), in the bespoke theme, fully stamped.
    site,
};

export default blueprint;
