// Chocolatier (Artisan): a reference-driven SITE TEMPLATE (docs/templates/*),
// composed distinct — its own home section sequence, example commerce, and journal —
// and dressed in the bespoke theme its DESIGN.md pins.
//
// GENERATED by marketplace-catalog/_gen/gen-template-retail-chocolate.ts
// via the shared _gen/template-sites/harness.ts — do NOT hand-edit; edit the generator
// and regenerate. A blueprint is PURE DATA: the loader `import()`s this module with no
// workspace resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import content from './content.json' with { type: 'json' };
import authors from './authors.json' with { type: 'json' };
import commerce from './commerce.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };
import emails from './emails.json' with { type: 'json' };

const blueprint = {
  key: 'sparx-retail-chocolate',
  version: '1.4.3',
  name: 'Chocolatier (Artisan)',
  summary:
    'A complete, working shop for a bean-to-bar chocolatier: a real catalogue of single-origin bars, truffle and confection boxes, drinking chocolate, gift sets and a flexible subscription, with categories, collections, a bespoke PDP and a fully merchandised home page. Rich, low-lit chocolate-room theme — deep cocoa grounds, a burgundy primary, a warm gold accent. Shipped as Cacao & Co.',
  vertical: 'retail',
  preview: 'media/preview.png',
  requiresModules: ['builder', 'commerce', 'cms', 'crm', 'email'],

  // Identity only (business name + tagline + fonts + the theme's hex colors). The look
  // itself rides site.theme + the theme decl below; the installing tenant rebrands the name.
  brand: {
    businessName: 'Cacao & Co.',
    tagline: 'Bean to bar, one small batch at a time.',
    colors: {
      primary: '#a73445',
      primaryForeground: '#fff6f6',
      accent: '#f2b95a',
      secondary: '#c5a38d',
    },
    fonts: {
      heading: 'Playfair Display',
      body: 'Outfit',
    },
  },

  // The provisioned SiteTheme the installer creates + applies — the bespoke template
  // look as a tenant-editable saved theme (base preset = the template's own theme key,
  // plus its brand snapshot).
  theme: {
    name: 'retail-chocolate',
    basePresetKey: 'retail-chocolate',
    presentation: {
      v: 2,
      containerWidth: '1152px',
    },
    brand: {
      colorPrimary: '#a73445',
      colorAccent: '#f2b95a',
      colorSecondary: '#c5a38d',
      fontHeading: 'Playfair Display',
      fontBody: 'Outfit',
      tokens: {},
    },
    apply: true,
  },

  assets,
  contentTypes: [],
  authors,
  content,
  commerce,

  // A shop's brand-voiced MARKETING starters (a welcome + a win-back), tokenized so a fork
  // re-themes to the tenant and installed as DRAFTS — the platform's keyed transactional
  // defaults (order/shipping/dunning) are separate and never duplicated here. Content
  // templates ship an empty set.
  emails,
  sequences: [],

  // The composed distinct site (frame + a template-specific home + standard commerce/
  // cms/about/contact pages + the /journal index), in the bespoke theme, fully stamped.
  site,
};

export default blueprint;
