// sparx marketplace component — 'Bundle' (Selling). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-col gap-3',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                children: ['The starter set'],
              },
              {
                kind: 'element',
                tag: 'p',
                class: 'max-w-2xl text-lg text-base-content',
                children: ['Everything for a first fit-out, at less than the parts add up to.'],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 gap-10 @3xl:grid-cols-2',
            children: [
              {
                kind: 'element',
                tag: 'ul',
                class: 'flex flex-col',
                children: [
                  {
                    kind: 'element',
                    tag: 'li',
                    class: 'flex items-start gap-3 border-t border-base-300 py-4',
                    children: [
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-success',
                        children: ['✓'],
                      },
                      {
                        kind: 'element',
                        tag: 'div',
                        class: 'flex flex-col gap-1',
                        children: [
                          {
                            kind: 'element',
                            tag: 'p',
                            class: 'text-base font-semibold text-base-content',
                            children: ['Worktop, 3m'],
                          },
                          {
                            kind: 'element',
                            tag: 'p',
                            class: 'text-base text-base-content',
                            children: ['Solid oak, oiled, cut to your length'],
                          },
                        ],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'li',
                    class: 'flex items-start gap-3 border-t border-base-300 py-4',
                    children: [
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-success',
                        children: ['✓'],
                      },
                      {
                        kind: 'element',
                        tag: 'div',
                        class: 'flex flex-col gap-1',
                        children: [
                          {
                            kind: 'element',
                            tag: 'p',
                            class: 'text-base font-semibold text-base-content',
                            children: ['Four base units'],
                          },
                          {
                            kind: 'element',
                            tag: 'p',
                            class: 'text-base text-base-content',
                            children: ['Painted to your colour'],
                          },
                        ],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'li',
                    class: 'flex items-start gap-3 border-t border-base-300 py-4',
                    children: [
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-success',
                        children: ['✓'],
                      },
                      {
                        kind: 'element',
                        tag: 'div',
                        class: 'flex flex-col gap-1',
                        children: [
                          {
                            kind: 'element',
                            tag: 'p',
                            class: 'text-base font-semibold text-base-content',
                            children: ['Handles and hinges'],
                          },
                          {
                            kind: 'element',
                            tag: 'p',
                            class: 'text-base text-base-content',
                            children: ['Solid brass, not plated'],
                          },
                        ],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'li',
                    class: 'flex items-start gap-3 border-t border-base-300 py-4',
                    children: [
                      {
                        kind: 'element',
                        tag: 'span',
                        class: 'text-success',
                        children: ['✓'],
                      },
                      {
                        kind: 'element',
                        tag: 'div',
                        class: 'flex flex-col gap-1',
                        children: [
                          {
                            kind: 'element',
                            tag: 'p',
                            class: 'text-base font-semibold text-base-content',
                            children: ['Fitting'],
                          },
                          {
                            kind: 'element',
                            tag: 'p',
                            class: 'text-base text-base-content',
                            children: ['Two days on site, waste taken away'],
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class:
                  'flex flex-col items-start gap-4 rounded-box border border-base-300 bg-base-100 p-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: ['Bought separately: $4,120'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-4xl font-semibold text-base-content',
                    children: ['$3,450'],
                  },
                  {
                    kind: 'element',
                    tag: 'div',
                    class: 'flex flex-wrap items-center gap-3',
                    children: [
                      {
                        kind: 'element',
                        tag: 'a',
                        class: 'btn btn-primary btn-lg',
                        attrs: {
                          href: '#',
                        },
                        children: ['Order the set'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-sm text-base-content',
                    children: ['Price held for 60 days from your quote.'],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
