// sparx marketplace component — 'Opening (words only)' (Page structure). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'mx-auto flex max-w-3xl flex-col items-center gap-6',
            children: [
              {
                kind: 'element',
                tag: 'h1',
                class:
                  'text-center text-4xl font-semibold leading-tight text-base-content @3xl:text-6xl',
                children: ['Furniture that outlives the room it was made for'],
              },
              {
                kind: 'element',
                tag: 'p',
                class: 'max-w-2xl text-center text-xl text-base-content',
                children: [
                  'Made in our own workshop from timber we dried ourselves. Quoted fixed, delivered when we said, guaranteed for ten years.',
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-wrap items-center gap-3',
                children: [
                  {
                    kind: 'element',
                    tag: 'a',
                    class: 'btn btn-primary btn-lg',
                    attrs: {
                      href: '#',
                    },
                    children: ['Get a quote'],
                  },
                  {
                    kind: 'element',
                    tag: 'a',
                    class: 'btn btn-neutral btn-outline btn-lg',
                    attrs: {
                      href: '#',
                    },
                    children: ['See our work'],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
