// sparx marketplace component — 'Trust facts' (People & proof). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 gap-6 @2xl:grid-cols-2',
            children: [
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3 rounded-box border border-base-300 bg-base-100 p-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['Trading since 2016'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: ['Same owners, same workshop, same phone number.'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-col gap-3 rounded-box border border-base-300 bg-base-100 p-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['Fully insured to $5M'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: ['Certificates on request, before you book, not after.'],
                  },
                ],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-wrap items-center gap-3',
            children: [
              {
                kind: 'element',
                tag: 'a',
                class: 'btn btn-primary btn-lg',
                attrs: {
                  href: '#',
                },
                children: ['Talk to us'],
              },
              {
                kind: 'element',
                tag: 'a',
                class: 'btn btn-neutral btn-outline btn-lg',
                attrs: {
                  href: '#',
                },
                children: ['See our work'],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
