// sparx marketplace component — 'Jobs' (People & proof). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-col gap-3',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                children: ['Working here'],
              },
              {
                kind: 'element',
                tag: 'p',
                class: 'max-w-2xl text-lg text-base-content',
                children: ['We hire rarely and keep people a long time. These are open now.'],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'ul',
            class: 'flex flex-col',
            children: [
              {
                kind: 'element',
                tag: 'li',
                class:
                  'flex flex-col gap-3 border-t border-base-300 py-6 @2xl:flex-row @2xl:items-center @2xl:justify-between',
                children: [
                  {
                    kind: 'element',
                    tag: 'div',
                    class: 'flex flex-col gap-1',
                    children: [
                      {
                        kind: 'element',
                        tag: 'h3',
                        class: 'text-xl font-semibold text-base-content',
                        children: ['Bench joiner'],
                      },
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-base text-base-content',
                        children: ['Mill Lane workshop · Full time'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'a',
                    class: 'btn btn-neutral btn-outline',
                    attrs: {
                      href: '#',
                    },
                    children: ['See the role'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'li',
                class:
                  'flex flex-col gap-3 border-t border-base-300 py-6 @2xl:flex-row @2xl:items-center @2xl:justify-between',
                children: [
                  {
                    kind: 'element',
                    tag: 'div',
                    class: 'flex flex-col gap-1',
                    children: [
                      {
                        kind: 'element',
                        tag: 'h3',
                        class: 'text-xl font-semibold text-base-content',
                        children: ['Fitter'],
                      },
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-base text-base-content',
                        children: ['On site, within 50 miles · Full time'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'a',
                    class: 'btn btn-neutral btn-outline',
                    attrs: {
                      href: '#',
                    },
                    children: ['See the role'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'li',
                class:
                  'flex flex-col gap-3 border-t border-base-300 py-6 @2xl:flex-row @2xl:items-center @2xl:justify-between',
                children: [
                  {
                    kind: 'element',
                    tag: 'div',
                    class: 'flex flex-col gap-1',
                    children: [
                      {
                        kind: 'element',
                        tag: 'h3',
                        class: 'text-xl font-semibold text-base-content',
                        children: ['Apprentice'],
                      },
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-base text-base-content',
                        children: ['Mill Lane workshop · Three-year apprenticeship'],
                      },
                    ],
                  },
                  {
                    kind: 'element',
                    tag: 'a',
                    class: 'btn btn-neutral btn-outline',
                    attrs: {
                      href: '#',
                    },
                    children: ['See the role'],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
