// sparx — Print & Sign Supply (B2B / Wholesale): a reference-driven SITE TEMPLATE (docs/templates/*),
// composed distinct — its own home section sequence, example commerce, and journal —
// and dressed in the bespoke theme its DESIGN.md pins.
//
// GENERATED by marketplace-catalog/_gen/gen-template-b2b-print-supply.ts
// via the shared _gen/template-sites/harness.ts — do NOT hand-edit; edit the generator
// and regenerate. A blueprint is PURE DATA: the loader `import()`s this module with no
// workspace resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import content from './content.json' with { type: 'json' };
import authors from './authors.json' with { type: 'json' };
import commerce from './commerce.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };
import emails from './emails.json' with { type: 'json' };

const blueprint = {
  key: 'sparx-b2b-print-supply',
  version: '1.2.0',
  name: 'sparx — Print & Sign Supply (B2B / Wholesale)',
  summary:
    'A complete, working wholesale shop for a print, signage & sublimation trade supplier: a real catalogue sold by the roll, box and case — cast vinyl & HTV, banner & board, eco-solvent & dye-sub ink, and sublimation blanks — with pack quantities, MOQs, categories, collections, a bespoke trade PDP (per-unit pricing, bulk breaks, net-30), and a full merchandised home page. Clean CMYK-adjacent theme — cool paper, press-ink primary, a magenta signal accent. Shipped as Inkyard Trade Supply.',
  vertical: 'b2b',
  preview: 'media/preview.png',
  requiresModules: ['builder', 'commerce', 'cms', 'crm', 'email'],

  // Identity only (business name + tagline + fonts + the theme's hex colours). The look
  // itself rides site.theme + the theme decl below; the installing tenant rebrands the name.
  brand: {
    businessName: 'Inkyard Trade Supply',
    tagline: 'Media, ink and blanks that run clean, priced for the shop.',
    colors: {
      primary: '#30406d',
      primaryForeground: '#f5f8ff',
      accent: '#b50070',
      secondary: '#494f61',
    },
    fonts: {
      heading: 'Space Grotesk',
      body: 'Inter',
    },
  },

  // The provisioned SiteTheme the installer creates + applies — the bespoke template
  // look as a tenant-editable saved theme (base preset = the template's own theme key,
  // plus its brand snapshot).
  theme: {
    name: 'b2b-print-supply',
    basePresetKey: 'b2b-print-supply',
    presentation: {
      v: 2,
      containerWidth: '1152px',
    },
    brand: {
      colorPrimary: '#30406d',
      colorAccent: '#b50070',
      colorSecondary: '#494f61',
      fontHeading: 'Space Grotesk',
      fontBody: 'Inter',
      tokens: {},
    },
    apply: true,
  },

  assets,
  contentTypes: [],
  authors,
  content,
  commerce,

  // A shop's brand-voiced MARKETING starters (a welcome + a win-back), tokenized so a fork
  // re-themes to the tenant and installed as DRAFTS — the platform's keyed transactional
  // defaults (order/shipping/dunning) are separate and never duplicated here. Content
  // templates ship an empty set.
  emails,
  sequences: [],

  // The composed distinct site (frame + a template-specific home + standard commerce/
  // cms/about/contact pages + the /journal index), in the bespoke theme, fully stamped.
  site,
};

export default blueprint;
