// sparx marketplace component — 'Photo grid' (Pictures). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-col gap-3',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                children: ['Recent work'],
              },
              {
                kind: 'element',
                tag: 'p',
                class: 'max-w-2xl text-lg text-base-content',
                children: [
                  'A few of the projects we have finished this year. Every photograph is our own.',
                ],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'div',
            class: 'grid grid-cols-1 gap-6 @2xl:grid-cols-2 @4xl:grid-cols-3',
            children: [
              {
                kind: 'element',
                tag: 'figure',
                class: 'flex flex-col gap-3',
                children: [
                  {
                    kind: 'element',
                    tag: 'img',
                    class:
                      'aspect-square w-full rounded-box border border-base-300 bg-base-200 object-cover',
                    attrs: {
                      src: '',
                      alt: 'A finished project',
                      loading: 'lazy',
                    },
                  },
                  {
                    kind: 'element',
                    tag: 'figcaption',
                    class: 'flex flex-col gap-1',
                    children: [
                      {
                        kind: 'element',
                        tag: 'h3',
                        class: 'text-base font-semibold text-base-content',
                        children: ['Riverside kitchen'],
                      },
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-sm text-base-content',
                        children: ['Completed March'],
                      },
                    ],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'figure',
                class: 'flex flex-col gap-3',
                children: [
                  {
                    kind: 'element',
                    tag: 'img',
                    class:
                      'aspect-square w-full rounded-box border border-base-300 bg-base-200 object-cover',
                    attrs: {
                      src: '',
                      alt: 'A finished project',
                      loading: 'lazy',
                    },
                  },
                  {
                    kind: 'element',
                    tag: 'figcaption',
                    class: 'flex flex-col gap-1',
                    children: [
                      {
                        kind: 'element',
                        tag: 'h3',
                        class: 'text-base font-semibold text-base-content',
                        children: ['Oak staircase'],
                      },
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-sm text-base-content',
                        children: ['Completed April'],
                      },
                    ],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'figure',
                class: 'flex flex-col gap-3',
                children: [
                  {
                    kind: 'element',
                    tag: 'img',
                    class:
                      'aspect-square w-full rounded-box border border-base-300 bg-base-200 object-cover',
                    attrs: {
                      src: '',
                      alt: 'A finished project',
                      loading: 'lazy',
                    },
                  },
                  {
                    kind: 'element',
                    tag: 'figcaption',
                    class: 'flex flex-col gap-1',
                    children: [
                      {
                        kind: 'element',
                        tag: 'h3',
                        class: 'text-base font-semibold text-base-content',
                        children: ['Garden room'],
                      },
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-sm text-base-content',
                        children: ['Completed June'],
                      },
                    ],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'figure',
                class: 'flex flex-col gap-3',
                children: [
                  {
                    kind: 'element',
                    tag: 'img',
                    class:
                      'aspect-square w-full rounded-box border border-base-300 bg-base-200 object-cover',
                    attrs: {
                      src: '',
                      alt: 'A finished project',
                      loading: 'lazy',
                    },
                  },
                  {
                    kind: 'element',
                    tag: 'figcaption',
                    class: 'flex flex-col gap-1',
                    children: [
                      {
                        kind: 'element',
                        tag: 'h3',
                        class: 'text-base font-semibold text-base-content',
                        children: ['Loft conversion'],
                      },
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-sm text-base-content',
                        children: ['Completed June'],
                      },
                    ],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'figure',
                class: 'flex flex-col gap-3',
                children: [
                  {
                    kind: 'element',
                    tag: 'img',
                    class:
                      'aspect-square w-full rounded-box border border-base-300 bg-base-200 object-cover',
                    attrs: {
                      src: '',
                      alt: 'A finished project',
                      loading: 'lazy',
                    },
                  },
                  {
                    kind: 'element',
                    tag: 'figcaption',
                    class: 'flex flex-col gap-1',
                    children: [
                      {
                        kind: 'element',
                        tag: 'h3',
                        class: 'text-base font-semibold text-base-content',
                        children: ['Shopfront rebuild'],
                      },
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-sm text-base-content',
                        children: ['Completed July'],
                      },
                    ],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'figure',
                class: 'flex flex-col gap-3',
                children: [
                  {
                    kind: 'element',
                    tag: 'img',
                    class:
                      'aspect-square w-full rounded-box border border-base-300 bg-base-200 object-cover',
                    attrs: {
                      src: '',
                      alt: 'A finished project',
                      loading: 'lazy',
                    },
                  },
                  {
                    kind: 'element',
                    tag: 'figcaption',
                    class: 'flex flex-col gap-1',
                    children: [
                      {
                        kind: 'element',
                        tag: 'h3',
                        class: 'text-base font-semibold text-base-content',
                        children: ['Barn restoration'],
                      },
                      {
                        kind: 'element',
                        tag: 'p',
                        class: 'text-sm text-base-content',
                        children: ['Completed August'],
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
