// sparx — Pressure Washing (Commercial): a BOOKING-BACKED service-business SITE TEMPLATE.
//
// GENERATED by marketplace-catalog/_gen/gen-sparx-pressurewash-commercial.ts via the shared
// _gen/service-sites/harness.ts — do NOT hand-edit; edit the generator and regenerate.
// A blueprint is PURE DATA: the loader `import()`s this module with no workspace
// resolution, so it imports ONLY sibling JSON, never `@sparx/*`.
import site from './site.json' with { type: 'json' };
import scheduling from './scheduling.json' with { type: 'json' };
import emails from './emails.json' with { type: 'json' };
import assets from './assets.json' with { type: 'json' };

const blueprint = {
    key: 'sparx-pressurewash-commercial',
    version: '1.3.0',
    name: 'sparx — Pressure Washing (Commercial)',
    summary:
        'A professional commercial exterior-cleaning site — a deep slate palette with a sharp amber accent, built around online booking. Property managers book a free site assessment, quote or service consultation in about a minute; three crew leads carry their own skills and hours as dispatchable resources. Leads with insured, scheduled service contracts from storefronts to fleets. Ships as "ProWash Exterior Cleaning", a commercial pressure-washing company.',
    vertical: 'services',
    preview: 'media/preview.png',
    requiresModules: ['builder', 'scheduling', 'crm', 'email'],

    // Identity only (business name + tagline + fonts + the theme's hex colors). The look
    // rides site.theme + the theme decl below; the installing tenant rebrands the name.
    brand: {
        businessName: 'ProWash Exterior Cleaning',
        tagline: 'Commercial exteriors, kept sharp.',
        colors: {
            primary: '#25364c',
            primaryForeground: '#f4f9ff',
            accent: '#e1901f',
            secondary: '#3b434d',
        },
        fonts: {
            heading: 'Archivo',
            body: 'Inter',
        },
    },

    // The provisioned SiteTheme the installer creates + applies — an editable saved theme
    // over a foundation base + the template's brand snapshot. The LIVE storefront look is
    // site.theme (the flat bespoke tokens), written last.
    theme: {
        name: 'slateworks',
        basePresetKey: 'apex',
        presentation: {
            v: 2,
            containerWidth: '1152px',
        },
        brand: {
            colorPrimary: '#25364c',
            colorAccent: '#e1901f',
            colorSecondary: '#3b434d',
            fontHeading: 'Archivo',
            fontBody: 'Inter',
            tokens: {},
        },
        apply: true,
    },

    assets,
    contentTypes: [],

    // The booking spine — policies, bookable resources (staff/rooms/stations) with weekly
    // hours, and the service menu. The installer's scheduling slice replays it into a live
    // booking flow that the site's /book page renders.
    scheduling,

    // Brand-voiced MARKETING starters (a welcome + a come-back), installed as DRAFTS the
    // tenant switches on. The transactional booking sends — confirmation, reminder,
    // reschedule, cancellation, waitlist — are platform KEYED defaults, so they are covered
    // on email-module activation and are deliberately NOT duplicated here.
    emails,
    sequences: [],

    // The composed distinct site (frame + Home + Book + About + Contact) in the bespoke
    // theme, fully stamped.
    site,
};

export default blueprint;
