// sparx marketplace component — 'Opening with a wide picture' (Page structure). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex max-w-3xl flex-col gap-5',
            children: [
              {
                kind: 'element',
                tag: 'h1',
                class: 'text-4xl font-semibold leading-tight text-base-content @3xl:text-6xl',
                children: ['Twenty-six kitchens last year. Every one on time.'],
              },
              {
                kind: 'element',
                tag: 'p',
                class: 'text-xl text-base-content',
                children: [
                  'We book a date before you commit, not after. It is the whole reason people come back to us.',
                ],
              },
              {
                kind: 'element',
                tag: 'div',
                class: 'flex flex-wrap items-center gap-3',
                children: [
                  {
                    kind: 'element',
                    tag: 'a',
                    class: 'btn btn-primary btn-lg',
                    attrs: {
                      href: '#',
                    },
                    children: ['Talk to us'],
                  },
                ],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'img',
            class:
              'aspect-video w-full rounded-box border border-base-300 bg-base-200 object-cover',
            attrs: {
              src: '',
              alt: 'A finished kitchen',
              loading: 'lazy',
            },
          },
        ],
      },
    ],
  },
} as const;
