// sparx marketplace component — 'Steps' (How it works). The silica
// section this listing surfaces: the exact node tree the Builder inserts from its
// Insert palette. GENERATED by marketplace-catalog/_gen/gen-silica-components.ts from
// SPARX_CATALOG — do NOT hand-edit. Pure data (no imports): the ingest resolves this
// module with no workspace resolution.
export default {
  tree: {
    kind: 'element',
    tag: 'section',
    class: 'bg-base-100 @container px-6 py-16',
    children: [
      {
        kind: 'element',
        tag: 'div',
        class: 'mx-auto flex w-full max-w-6xl flex-col gap-10',
        children: [
          {
            kind: 'element',
            tag: 'div',
            class: 'flex flex-col gap-3',
            children: [
              {
                kind: 'element',
                tag: 'h2',
                class: 'text-3xl font-semibold text-base-content @3xl:text-4xl',
                children: ['How it works'],
              },
              {
                kind: 'element',
                tag: 'p',
                class: 'max-w-2xl text-lg text-base-content',
                children: ['Four steps, and you can stop after any of them.'],
              },
            ],
          },
          {
            kind: 'element',
            tag: 'ol',
            class: 'grid grid-cols-1 gap-8 @2xl:grid-cols-2 @4xl:grid-cols-4',
            children: [
              {
                kind: 'element',
                tag: 'li',
                class: 'flex flex-col gap-2 border-t border-base-300 pt-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['Tell us what you need'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: ['A phone call or a message. No forms to fill in, no obligation.'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'li',
                class: 'flex flex-col gap-2 border-t border-base-300 pt-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['We come and look'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: [
                      'We measure up and talk through the options, on a day that suits you.',
                    ],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'li',
                class: 'flex flex-col gap-2 border-t border-base-300 pt-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['You get a written price'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: ['Itemised, fixed, and valid for sixty days. No pressure to decide.'],
                  },
                ],
              },
              {
                kind: 'element',
                tag: 'li',
                class: 'flex flex-col gap-2 border-t border-base-300 pt-6',
                children: [
                  {
                    kind: 'element',
                    tag: 'h3',
                    class: 'text-xl font-semibold text-base-content',
                    children: ['We do the work'],
                  },
                  {
                    kind: 'element',
                    tag: 'p',
                    class: 'text-base text-base-content',
                    children: ['Booked in when you are ready, finished when we said it would be.'],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
} as const;
